<h3><?php echo __( 'Delete theme', 'thrive-theme' ); ?></h3>
<p>
	<?php echo __( 'Are you sure you want to delete the theme? ', 'thrive-theme' ); ?>
	"<span class="ttd-delete-skin-name"></span>"?
	<?php echo __( 'This cannot be undone.', 'thrive-theme' ); ?>
</p>

<div class="ttd-modal-footer">
	<button class="ttd-left grey click" data-fn="close"><?php echo __( 'Cancel', 'thrive-theme' ); ?></button>
	<button class="ttd-right red click" data-fn="delete"><?php echo __( 'Delete theme', 'thrive-theme' ); ?></button>
</div>
