<div class="flex-mid pb-10 space-between">
	<div class="flex-mid boxes pr-15">
		<div class="border-boxes">
			<div class="tve-border-side click top" data-fn="borderSide" data-value="top"></div>
			<div class="tve-border-side click left" data-fn="borderSide" data-value="left"></div>
			<div class="tve-border-side click right" data-fn="borderSide" data-value="right"></div>
			<div class="tve-border-side click bottom" data-fn="borderSide" data-value="bottom"></div>
			<div class="tve-border-side default center click" data-fn="borderSide" data-value=""></div>
		</div>
	</div>
	<div class="tve-border-settings">
		<div class="flex pb-10 space-between">
			<div class="tve-border-color hide-input mr-10"></div>
			<div class="tve-border-width no-space input-small"></div>
		</div>
		<div class="tve-border-style no-space"></div>
	</div>
</div>
