<div>
	<div class="tcb-page-map click mouseenter mouseleave mouseover" data-fn="boxHover" data-fn-click="selectSection" data-section="body.tve_lp">
		<div class="tsp-header tsp-box click mouseenter mouseleave mouseover has-visibility-icon" data-fn-click="selectSection" data-fn="boxHover" data-section="header" data-selector=".thrv_header">
			<span><?php echo __( 'Header', 'thrive-cb' ); ?></span>
		</div>

		<div class="lp-content tsp-content"></div>

		<div class="tsp-footer tsp-box click mouseenter mouseleave mouseover has-visibility-icon" data-fn-click="selectSection" data-fn="boxHover" data-section="footer" data-selector=".thrv_footer">
			<span><?php echo __( 'Footer', 'thrive-cb' ); ?></span>
		</div>
	</div>
</div>
