<div class="symbol-item modal-item">
	<div class="card click" data-id="<#= item.id #>" data-fn="select_item" data-type="symbol">
		<div class="thrive-shortcode-config" style="display: none !important"><#= item.config #></div>
		<div class="symbol-template-thumbnail" style="background-image: url('<#= item.thumb.url #>');"></div>
		<div class="modal-item-name"><#= item.post_title #></div>
		<div class="selected"></div>
	</div>
</div>