<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-visual-editor
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden!
}
?>
<div class="click tcb-close-notification" data-fn="onApply">
	<?php tcb_icon( 'close2' ); ?>
</div>
<p class="tooltip-header"><?php echo __( 'New Header States Available', 'thrive-cb' ); ?></p>
<p class="tooltip-text"><?php echo __( 'Switch between header states by using the dropdown menu:', 'thrive-cb' ); ?></p>