<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-apprentice
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden!
}
?>
<div class="tva-wiz-left">
	<h1>
		<?php echo __( 'LMS Visual Editing for WordPress', 'thrive-apprentice' ); ?>
		<br>
		<span><?php echo __( 'is Finally Here!', 'thrive-apprentice' ); ?></span>
	</h1>

	<a class="mt-20" target="_blank" rel="noopener" href="http://help.thrivethemes.com/en/articles/5341305-getting-started-with-our-new-thrive-apprentice-visual-editor"><?php echo __( 'Learn more', 'thrive-apprentice' ); ?></a>

	<button class="mt-60 click tva-btn tva-btn-blue" data-fn="gotIt"><?php echo __( 'Get started!', 'thrive-apprentice' ); ?></button>

</div>
<div class="tva-wiz-right"></div>
