<div class="ls-optimization-wrapper">
	<div class="page-content grey">
		<div class="page-title"><?php echo __( 'Site Analysis Results', 'thrive-cb' ); ?></div>
		<div class="page-text-wrapper">
			<span class="big-icon success"></span>
			<div class="text-title green-color">
				<?php echo __( 'All assets on your site are optimized to the latest version', 'thrive-cb' ); ?>
			</div>
		</div>
		<button class="lightspeed-button grey lightspeed-force-optimize">
			<?php echo __( 'Rerun asset optimization', 'thrive-cb' ); ?>
		</button>
	</div>
	<div class="page-footer"></div>
</div>
