<?php
/**
 * Created by PhpStorm.
 * User: Ovidiu
 * Date: 5/14/2018
 * Time: 4:23 PM
 */
?>
<div class="tve-cf-item" data-css="<#= wrapper_css #>">
	<div class="thrv-cf-input-wrapper" data-type="<#= item_type #>">
		<label data-css="<#= label_css #>"><#= label #></label>
		<div class="tve-cf-input" data-css="<#= input_css #>">
			<input placeholder="First Name" type="text" name="first_name">
		</div>
	</div>
</div>
