<p class="tqb-rel">
	<?php echo __( 'What result categories do you want to add to your quiz?', Thrive_Quiz_Builder::T ) ?>
	<span class="tqb-info-icon"></span>
	<span><?php echo __( 'Changing the list of results will impact the questions flow settings and the dynamic content on the Results Page. By eliminating results from the list, all the answers that were assigned to them will be switched to the None value and will lose the dynamic content set on the Results Page', Thrive_Quiz_Builder::T ) ?></span>
</p>

<div class="tvd-row">
	<input type="text" placeholder="Add a new category" id="tqb_add_quiz_category" data-bind="text">

	<a href="javascript:void(0)" id="tqb-add-result" class="tqb-add-quiz-category">&nbsp;</a>
</div>
