(function(){window.WPD="undefined"!==typeof window.WPD?window.WPD:{};window.WPD.ajaxsearchpro=new function(){this.prevState=null;this.firstIteration=!0;this.helpers={};this.plugin={};this.addons={addons:[],add:function(c){-1==this.addons.indexOf(c)&&(c=this.addons.push(c),this.addons[c-1].init())},remove:function(c){this.addons.filter(function(d){return d.name==c?("undefined"!=typeof d.destroy&&d.destroy(),!1):!0})}}}})();
(function(c){c.fn.extend(window.WPD.ajaxsearchpro.plugin,{addAnimation:function(){let d=this,a=0,b=1,f=!0;if(0<d.call_num||d._no_animations)return d.n.results.find(".item, .asp_group_header").removeClass("opacityZero").removeClass("asp_an_"+d.animOptions.items),!1;d.n.results.find(".item, .asp_group_header").each(function(){let g=this;1===b&&(f=c(g).inViewPort(0));if(1<b&&f&&!c(g).inViewPort(0)||80<b)return c(g).removeClass("opacityZero"),!0;"isotopic"==d.o.resultstype&&b>d.il.itemsPerPage?c(g).removeClass("opacityZero"):
(setTimeout(function(){c(g).addClass("asp_an_"+d.animOptions.items);c(g).removeClass("opacityZero")},a+25),a+=45,b++)})},removeAnimation:function(){let d=this;this.n.items.each(function(){c(this).removeClass("asp_an_"+d.animOptions.items)})}})})(WPD.dom);
(function(c){let d=window.WPD.ajaxsearchpro.helpers;c.fn.extend(window.WPD.ajaxsearchpro.plugin,{setFilterStateInput:function(a){let b=this;"undefined"==typeof a&&(a=65);let f=function(){JSON.stringify(b.originalFormData)!=JSON.stringify(d.formData(c("form",b.n.searchsettings)))?b.n.searchsettings.find("input[name=filters_initial]").val(0):b.n.searchsettings.find("input[name=filters_initial]").val(1)};0==a?f():setTimeout(function(){f()},a)},resetSearchFilters:function(){d.formData(c("form",this.n.searchsettings),
this.originalFormData);0<this.noUiSliders.length&&this.noUiSliders.forEach(function(a){if("undefined"!=typeof a.noUiSlider){let b=[];c(a).parent().find(".asp_slider_hidden").forEach(function(f){b.push(c(f).val())});0<b.length&&a.noUiSlider.set(b)}});"undefined"!=typeof this.select2jQuery&&this.select2jQuery(this.n.searchsettings.get(0)).find(".asp_gochosen,.asp_goselect2").trigger("change.asp_select2");this.n.text.val("");this.n.proloading.css("display","none");this.hideLoader();this.searchAbort();
this.setFilterStateInput(0)}})})(WPD.dom);
(function(c){c.fn.extend(window.WPD.ajaxsearchpro.plugin,{showMoreResLoader:function(){this.n.resultsDiv.addClass("asp_more_res_loading")},showLoader:function(d){d="undefined"!==typeof d?d:!1;if("none"!=this.o.loaderLocation){this.n.search.hasClass("hiddend")||"results"==this.o.loaderLocation||this.n.proloading.css({display:"block"});if(!1!==d)return!1;(!this.n.search.hasClass("hiddend")||"search"==this.o.loaderLocation)&&(this.n.search.hasClass("hiddend")||"both"!=this.o.loaderLocation&&"results"!=
this.o.loaderLocation)||this.usingLiveLoader||(0<this.n.resultsDiv.find(".asp_results_top").length&&this.n.resultsDiv.find(".asp_results_top").css("display","none"),this.showResultsBox(),c(".asp_res_loader",this.n.resultsDiv).removeClass("hiddend"),this.n.results.css("display","none"),this.n.showmore.css("display","none"),"undefined"!==typeof this.hidePagination&&this.hidePagination())}},hideLoader:function(){this.n.proloading.css({display:"none"});c(".asp_res_loader",this.n.resultsDiv).addClass("hiddend");
this.n.results.css("display","");this.n.resultsDiv.removeClass("asp_more_res_loading")}})})(WPD.dom);
(function(c){c.fn.extend(window.WPD.ajaxsearchpro.plugin,{fixClonedSelf:function(){let d=this.o.iid,a=this.o.rid;for(;!ASP.instances.set(this)&&!(++this.o.iid,50<this.o.iid););d!=this.o.iid&&(this.o.rid=this.o.id+"_"+this.o.iid,this.n.search.get(0).id="ajaxsearchpro"+this.o.rid,this.n.search.removeClass("asp_m_"+a).addClass("asp_m_"+this.o.rid),this.n.searchsettings.get(0).id=this.n.searchsettings.get(0).id.replace("settings"+a,"settings"+this.o.rid),this.n.searchsettings.hasClass("asp_s_"+a)?this.n.searchsettings.removeClass("asp_s_"+
a).addClass("asp_s_"+this.o.rid).data("instance",this.o.iid):this.n.searchsettings.removeClass("asp_sb_"+a).addClass("asp_sb_"+this.o.rid).data("instance",this.o.iid),this.n.resultsDiv.get(0).id=this.n.resultsDiv.get(0).id.replace("prores"+a,"prores"+this.o.rid),this.n.resultsDiv.removeClass("asp_r_"+a).addClass("asp_r_"+this.o.rid).data("instance",this.o.iid),this.n.container.find(".asp_init_data").data("instance",this.o.iid),this.n.container.find(".asp_init_data").get(0).id=this.n.container.find(".asp_init_data").get(0).id.replace("asp_init_id_"+
a,"asp_init_id_"+this.o.rid),this.n.prosettings.data("opened",0))},destroy:function(){let d=this;Object.keys(d.n).forEach(function(a){d.n[a].off()});"undefined"!==typeof d.n.searchsettings.get(0).referenced?(--d.n.searchsettings.get(0).referenced,0>d.n.searchsettings.get(0).referenced&&d.n.searchsettings.remove()):d.n.searchsettings.remove();"undefined"!==typeof d.n.resultsDiv.get(0).referenced?(--d.n.resultsDiv.get(0).referenced,0>d.n.resultsDiv.get(0).referenced&&d.n.resultsDiv.remove()):d.n.resultsDiv.remove();
d.n.trythis.remove();d.n.search.remove();d.n.container.remove();d.documentEventHandlers.forEach(function(a){c(a.node).off(a.event,a.handler)})}})})(WPD.dom);
(function(c){let d=window.WPD.ajaxsearchpro.helpers;c.fn.extend(window.WPD.ajaxsearchpro.plugin,{isRedirectToFirstResult:function(){return(0<c(".asp_res_url",this.n.resultsDiv).length||0<c(".asp_es_"+this.o.id+" a").length||this.o.resPage.useAjax&&0<c(this.o.resPage.selector+"a").length)&&(1==this.o.redirectOnClick&&"click"==this.ktype&&"first_result"==this.o.trigger.click||1==this.o.redirectOnEnter&&("input"==this.ktype||"keyup"==this.ktype)&&13==this.keycode&&"first_result"==this.o.trigger.return||
"button"==this.ktype&&"first_result"==this.o.sb.redirect_action)},doRedirectToFirstResult:function(){let a,b;a="click"==this.ktype?this.o.trigger.click_location:"button"==this.ktype?this.o.sb.redirect_location:this.o.trigger.return_location;0<c(".asp_res_url",this.n.resultsDiv).length?b=c(c(".asp_res_url",this.n.resultsDiv).get(0)).attr("href"):0<c(".asp_es_"+this.o.id+" a").length?b=c(c(".asp_es_"+this.o.id+" a").get(0)).attr("href"):this.o.resPage.useAjax&&0<c(this.o.resPage.selector+"a").length&&
(b=c(c(this.o.resPage.selector+"a").get(0)).attr("href"));""!=b&&("same"==a?location.href=b:d.openInNewTab(b),this.hideLoader(),this.hideResults());return!1},doRedirectToResults:function(a){let b;if(!this.reportSettingsValidity())return this.showNextInvalidFacetMessage(),!1;b="click"==a?this.o.trigger.click_location:"button"==a?this.o.sb.redirect_location:this.o.trigger.return_location;a=this.getRedirectURL(a);if(this.o.overridewpdefault){if(1==this.o.resPage.useAjax)return this.hideResults(),this.liveLoad(a,
this.o.resPage.selector),this.showLoader(),0==this.o.blocking&&this.hideSettings(),!1;"post"==this.o.override_method?d.submitToUrl(a,"post",{asp_active:1,p_asid:this.o.id,p_asp_data:c("form",this.n.searchsettings).serialize()},b):"same"==b?location.href=a:d.openInNewTab(a)}else d.submitToUrl(a,"post",{np_asid:this.o.id,np_asp_data:c("form",this.n.searchsettings).serialize()},b);this.n.proloading.css("display","none");this.hideLoader();0==this.o.blocking&&this.hideSettings();this.hideResults();this.searchAbort()},
getRedirectURL:function(a){a="undefined"!==typeof a?a:"enter";var b="click"==a?this.o.trigger.click:"button"==a?this.o.sb.redirect_action:this.o.trigger.return;"results_page"==b?a="?s="+d.nicePhrase(this.n.text.val()):"woo_results_page"==b?a="?post_type=product&s="+d.nicePhrase(this.n.text.val()):(a="button"==a?"elementor_page"==b?this.o.sb.elementor_url:this.o.sb.redirect_url:"elementor_page"==b?this.o.trigger.elementor_url:this.o.trigger.redirect_url,a=this.parseCustomRedirectURL(a,this.n.text.val()));
1<this.o.homeurl.indexOf("?")&&0===a.indexOf("?")&&(a=a.replace("?","&"));if(this.o.overridewpdefault&&"post"!=this.o.override_method){let f="&";-1!==this.o.homeurl.indexOf("?")&&"elementor_page"!=b||-1!==a.indexOf("?")||(f="?");a=a+f+"asp_active=1&p_asid="+this.o.id+"&p_asp_data=1&"+c("form",this.n.searchsettings).serialize();b="elementor_page"==b?a:this.o.homeurl+a}else b="elementor_page"==b?a:this.o.homeurl+a;b=b.replace("https://","https:///");b=b.replace("http://","http:///");b=b.replace(/\/\//g,
"/");b=d.Hooks.applyFilters("asp_redirect_url",b,this.o.id,this.o.iid);return b=d.wp_hooks_apply_filters("asp_redirect_url",b,this.o.id,this.o.iid)},parseCustomRedirectURL:function(a,b){let f=this,g=a.replace(/{phrase}/g,d.nicePhrase(b));a=g.match(/{(.*?)}/g);null!==a&&a.forEach(function(h){h=h.replace(/[{}]/g,"");var e=c('input[type=radio][name*="aspf['+h+'_"]:checked',f.n.searchsettings);0==e.length&&(e=c('input[type=text][name*="aspf['+h+'_"]',f.n.searchsettings));0==e.length&&(e=c('input[type=hidden][name*="aspf['+
h+'_"]',f.n.searchsettings));0==e.length&&(e=c('select[name*="aspf['+h+'_"]:not([multiple])',f.n.searchsettings));0==e.length&&(e=c('input[type=radio][name*="termset['+h+'"]:checked',f.n.searchsettings));0==e.length&&(e=c('input[type=text][name*="termset['+h+'"]',f.n.searchsettings));0==e.length&&(e=c('input[type=hidden][name*="termset['+h+'"]',f.n.searchsettings));0==e.length&&(e=c('select[name*="termset['+h+'"]:not([multiple])',f.n.searchsettings));if(0==e.length)return!0;e=e.val();g=g.replace("{"+
h+"}",""+e)});return g}})})(WPD.dom);
(function(c){let d=window.WPD.ajaxsearchpro.helpers;c.fn.extend(window.WPD.ajaxsearchpro.plugin,{showResults:function(){let a=this;"horizontal"==a.o.resultstype?a.createHorizontalScroll():"vertical"==a.o.resultstype&&a.createVerticalScroll();switch(a.o.resultstype){case "horizontal":a.showHorizontalResults();break;case "vertical":a.showVerticalResults();break;case "polaroid":a.showPolaroidResults();break;case "isotopic":a.showIsotopicResults();break;default:a.showHorizontalResults()}a.showAnimatedImages();a.hideLoader();
a.n.proclose.css({display:"block"});d.isMobile()&&a.o.mobile.hide_keyboard&&!a.resultsOpened&&document.activeElement.blur();a.o.settingsHideOnRes&&0==a.o.blocking&&a.hideSettings();"undefined"!=typeof WPD.lazy&&setTimeout(function(){WPD.lazy(".asp_lazy")},100);a.is_scroll&&"undefined"!==typeof a.scroll.recalculate&&setTimeout(function(){a.scroll.recalculate()},500);a.eh.resulsDivHoverMouseEnter=a.eh.resulsDivHoverMouseEnter||function(){c(".item",a.n.resultsDiv).removeClass("hovered");c(this).addClass("hovered")};
a.eh.resulsDivHoverMouseLeave=a.eh.resulsDivHoverMouseLeave||function(){c(".item",a.n.resultsDiv).removeClass("hovered")};a.n.resultsDiv.find(".item").on("mouseenter",a.eh.resulsDivHoverMouseEnter);a.n.resultsDiv.find(".item").on("mouseleave",a.eh.resulsDivHoverMouseLeave);a.fixAccessibility();a.resultsOpened=!0},hideResults:function(a){let b=this;a="undefined"==typeof a?!0:a;if(!b.resultsOpened)return!1;b.n.resultsDiv.removeClass(b.resAnim.showClass).addClass(b.resAnim.hideClass);setTimeout(function(){b.n.resultsDiv.css(b.resAnim.hideCSS)},
b.resAnim.duration);b.n.proclose.css({display:"none"});d.isMobile()&&a&&document.activeElement.blur();b.resultsOpened=!1;"undefined"!=typeof b.ptstack&&delete b.ptstack;b.hideArrowBox();b.n.s.trigger("asp_results_hide",[b.o.id,b.o.iid],!0,!0)},updateResults:function(a){if(""===a.replace(/^\s*[\r\n]/gm,"")||c(a).hasClass("asp_nores")||0<c(a).find(".asp_nores").length)this.n.showmore.css("display","none"),c("span",this.n.showmore).html("");else if("isotopic"==this.o.resultstype&&0<this.call_num&&null!=
this.isotopic&&"undefined"!=typeof this.isotopic.appended&&0<this.n.items.length){a=c(a);let b=this.n.items.last(),f=parseInt(this.n.items.last().attr("data-itemnum"));a.get().forEach(function(g){c(g).attr("data-itemnum",++f).css({width:b.css("width"),height:b.css("height")})});this.n.resdrg.append(a);this.isotopic.appended(a.get());this.n.items=0<c(".item",this.n.resultsDiv).length?c(".item",this.n.resultsDiv):c(".photostack-flip",this.n.resultsDiv)}else 0<this.call_num&&"vertical"==this.o.resultstype?
this.n.resdrg.html(this.n.resdrg.html()+'<div class="asp_v_spacer"></div>'+a):this.n.resdrg.html(this.n.resdrg.html()+a)},showResultsBox:function(){this.n.s.trigger("asp_results_show",[this.o.id,this.o.iid],!0,!0);this.n.resultsDiv.css({display:"block",height:"auto"});this.n.results.find(".item, .asp_group_header").addClass(this.animationOpacity);this.n.resultsDiv.css(this.resAnim.showCSS);this.n.resultsDiv.removeClass(this.resAnim.hideClass).addClass(this.resAnim.showClass);this.fixResultsPosition(!0)},
scrollToResults:function(){var a=Math.floor(.1*window.innerHeight);if(!(!this.resultsOpened||1<this.call_num||1!=this.o.scrollToResults.enabled||0<this.n.search.closest(".asp_preview_data").length||1==this.o.compact.enabled||this.n.resultsDiv.inViewPort(a))){a="hover"==this.o.resultsposition?this.n.probox.offset().top-20:this.n.resultsDiv.offset().top-20;a+=this.o.scrollToResults.offset;var b=c("#wpadminbar");0<b.length&&(a-=b.height());window.scrollTo({top:0>a?0:a,behavior:"smooth"})}},showAnimatedImages:function(){this.n.items.each(function(){let a=
c(this).find(".asp_image[data-src]"),b=a.data("src");if("undefined"!=typeof b&&null!=b&&""!==b&&-1<b.indexOf(".gif")&&0==a.find("canvas").length){a.prepend(c('<div class="asp_item_canvas"><canvas></canvas></div>').get(0));let f=c(this).find("canvas").get(0),g=c(this).find(".asp_item_canvas"),h=f.getContext("2d"),e=new Image;e.crossOrigin="anonymous";e.onload=function(){c(f).attr({width:e.width,height:e.height});h.drawImage(e,0,0,e.width,e.height);g.css({"background-image":"url("+f.toDataURL()+")"})};
e.src=b}})},updateInfoHeader:function(a){let b,f=this.n.resultsDiv.find(".asp_results_top"),g=this.n.text.val().trim();0<f.length&&(0>=this.n.items.length?f.css("display","none"):(""!==g&&""!==this.resInfoBoxTxt?b=this.resInfoBoxTxt:""===g&&""!==this.resInfoBoxTxtNoPhrase&&(b=this.resInfoBoxTxtNoPhrase),""!==b?(b=b.replace("{phrase}",this.n.text.val()),b=b.replace("{results_count}",this.n.items.length),b=b.replace("{results_count_total}",a),f.html(b),f.css("display","block")):f.css("display","none")))}})})(WPD.dom);
(function(c){let d=window.WPD.ajaxsearchpro.helpers;c.fn.extend(window.WPD.ajaxsearchpro.plugin,{createResultsScroll:function(a){let b=this,f,g=b.n.results;a="undefined"==typeof a?"vertical":a;0<b.o.itemscount&&b.is_scroll&&"undefined"===typeof b.scroll.recalculate&&(b.scroll=new asp_SimpleBar(b.n.results.get(0),{direction:c("body").hasClass("rtl")?"rtl":"ltr",autoHide:b.o.scrollBar.vertical.autoHide}),g=g.add(b.scroll.getScrollElement()));g.on("scroll",function(){document.dispatchEvent(new Event("wpd-lazy-trigger"));
b.o.show_more.infinite&&(clearTimeout(f),f=setTimeout(function(){b.checkAndTriggerInfiniteScroll(a)},60))})},createVerticalScroll:function(){this.createResultsScroll("vertical")},createHorizontalScroll:function(){this.createResultsScroll("horizontal")},checkAndTriggerInfiniteScroll:function(a){var b=c(".item",this.n.resultsDiv);a="undefined"==typeof a?"window":a;if(0==this.n.showmore.length||"none"==this.n.showmore.css("display"))return!1;if("window"==a||"horizontal"==a){if("isotopic"==this.o.resultstype&&
"none"!=c("nav.asp_navigation",this.n.resultsDiv).css("display"))return!1;a=b.last().inViewPort(0,this.n.resultsDiv.get(0));let f=b.last().inViewPort(0);!this.searching&&0<b.length&&a&&f&&this.n.showmore.find("a.asp_showmore").trigger("click")}else"vertical"==a?(b=0<this.n.resultsDiv.find(".asp_simplebar-content-wrapper").length?this.n.resultsDiv.find(".asp_simplebar-content-wrapper"):this.n.results,d.isScrolledToBottom(b.get(0),20)&&this.n.showmore.find("a.asp_showmore").trigger("click")):"isotopic"==
a&&!this.searching&&0<b.length&&this.n.resultsDiv.find("nav.asp_navigation ul li").last().hasClass("asp_active")&&this.n.showmore.find("a.asp_showmore").trigger("click")}})})(WPD.dom);
(function(c){let d=window.WPD.ajaxsearchpro.helpers;c.fn.extend(window.WPD.ajaxsearchpro.plugin,{isDuplicateSearchTriggered:function(){for(let a=0;25>a;a++)if(this.o.id+"_"+a!=this.o.rid&&!1!==ASP.instances.get(this.o.id,a))return ASP.instances.get(this.o.id,a).searching;return!1},searchAbort:function(){null!=this.post&&this.post.abort()},searchWithCheck:function(a){let b=this;"undefined"==typeof a&&(a=50);b.n.text.val().length<b.o.charcount||(b.searchAbort(),clearTimeout(b.timeouts.searchWithCheck),
b.timeouts.searchWithCheck=setTimeout(function(){b.search()},a))},search:function(a,b,f,g,h){let e=this,n=!1;if(e.isDuplicateSearchTriggered())return!1;f="undefined"==typeof f?!1:f;g="undefined"==typeof g?!1:g;h="undefined"==typeof h?!1:h;let l={action:"ajaxsearchpro_search",aspp:e.n.text.val(),asid:e.o.id,asp_inst_id:e.o.rid,options:c("form",e.n.searchsettings).serialize()};l=d.Hooks.applyFilters("asp_search_data",l,e.o.id,e.o.iid);l=d.wp_hooks_apply_filters("asp_search_data",l,e.o.id,e.o.iid);e.hideArrowBox();
e.isAutoP||e.reportSettingsValidity()||(h||(e.showNextInvalidFacetMessage(),e.scrollToNextInvalidFacetMessage()),n=!0);e.isAutoP&&(l.autop=1,e.isAutoP=!1);if(!f&&!g&&JSON.stringify(l)===JSON.stringify(e.lastSearchData)){e.resultsOpened||e.usingLiveLoader||e.showResults();if(e.isRedirectToFirstResult())return e.doRedirectToFirstResult(),!1;n=!0}if(n)return e.hideLoader(),e.searchAbort(),!1;e.n.s.trigger("asp_search_start",[e.o.id,e.o.iid,e.n.text.val()],!0,!0);e.searching=!0;e.n.proclose.css({display:"none"});
e.showLoader(f);0==e.o.blocking&&0==e.o.trigger.facet&&e.hideSettings();f?(e.call_num++,l.asp_call_num=e.call_num,e.autopStartedTheSearch&&(l.options+="&"+c.fn.serializeForAjax(e.autopData),--l.asp_call_num)):(e.call_num=0,e.autopStartedTheSearch=!!l.autop);g=c('form[name="asp_data"]');0<g.length&&(l.asp_preview_options=g.serialize());"undefined"!=typeof a&&!1!==a&&(l.options+="&force_count="+parseInt(a));"undefined"!=typeof b&&!1!==b&&(l.options+="&force_order="+parseInt(b));e.gaEvent("search_start");
0<c(".asp_es_"+e.o.id).length?e.liveLoad(".asp_es_"+e.o.id,e.getCurrentLiveURL(),!1):e.o.resPage.useAjax?e.liveLoad(e.o.resPage.selector,e.getRedirectURL()):e.post=c.fn.ajax({url:ASP.ajaxurl,method:"POST",data:l,success:function(k){e.gaPageview(e.n.text.val());e.searching=!1;k=k.replace(/^\s*[\r\n]/gm,"");let p=k.match(/!!ASPSTART_HTML!!(.*[\s\S]*)!!ASPEND_HTML!!/);k=k.match(/!!ASPSTART_DATA!!(.*[\s\S]*)!!ASPEND_DATA!!/);if(null==p||"object"!=typeof p||"undefined"==typeof p[1])return e.hideLoader(),
alert('Ajax Search Pro Error:\r\n\r\nPlease look up "The response data is missing" from the documentation at\r\n\r\n documentation.ajaxsearchpro.com'),!1;p=p[1];p=d.Hooks.applyFilters("asp_search_html",p,e.o.id,e.o.iid);p=d.wp_hooks_apply_filters("asp_search_html",p,e.o.id,e.o.iid);k=JSON.parse(k[1]);e.n.s.trigger("asp_search_end",[e.o.id,e.o.iid,e.n.text.val(),k],!0,!0);e.autopStartedTheSearch&&("undefined"!=typeof l.autop?(e.autopData.not_in={},e.autopData.not_in_count=0,Array.isArray(k.results)&&
k.results.forEach(function(m){"undefined"==typeof e.autopData.not_in[m.content_type]&&(e.autopData.not_in[m.content_type]=[]);e.autopData.not_in[m.content_type].push(m.id);++e.autopData.not_in_count})):k.full_results_count+=e.autopData.not_in_count);f?(e.updateResults(p),e.results_num+=k.results_count):(e.n.resdrg.html(""),e.n.resdrg.html(p),e.results_num=k.results_count,e.o.statistics&&e.stat_addKeyword(e.o.id,e.n.text.val()));c(".asp_keyword",e.n.resdrg).on("click",function(){e.n.text.val(d.decodeHTMLEntities(c(this).text()));
e.n.textAutocomplete.val("");0!=e.o.redirectOnClick&&0!=e.o.redirectOnEnter&&1!=e.o.trigger.type||e.search()});e.n.items=0<c(".item",e.n.resultsDiv).length?c(".item",e.n.resultsDiv):c(".photostack-flip",e.n.resultsDiv);e.gaEvent("search_end",{results_count:e.n.items.length});if(e.isRedirectToFirstResult())return e.doRedirectToFirstResult(),!1;e.hideLoader();e.showResults();e.scrollToResults();e.lastSuccesfulSearch=c("form",e.n.searchsettings).serialize()+e.n.text.val().trim();e.lastSearchData=l;e.updateInfoHeader(k.full_results_count);
0<e.n.showmore.length&&(0<c("span",e.n.showmore).length&&0<k.results_count&&0<k.full_results_count-e.results_num?(e.n.showmore.css("display","block"),c("span",e.n.showmore).html("("+(k.full_results_count-e.results_num)+")"),c("a",e.n.showmore).attr("href",""),c("a",e.n.showmore).off(),c("a",e.n.showmore).on(e.clickTouchend,function(m){m.preventDefault();m.stopImmediatePropagation();if("ajax"==e.o.show_more.action){if(e.searching)return!1;e.showMoreResLoader();e.search(!1,!1,!0)}else c(this).off(),
"results_page"==e.o.show_more.action?m="?s="+d.nicePhrase(e.n.text.val()):"woo_results_page"==e.o.show_more.action?m="?post_type=product&s="+d.nicePhrase(e.n.text.val()):(m="elementor_page"==e.o.show_more.action?e.parseCustomRedirectURL(e.o.show_more.elementor_url,e.n.text.val()):e.parseCustomRedirectURL(e.o.show_more.url,e.n.text.val()),m=c("<textarea />").html(m).text()),"elementor_page"!=e.o.show_more.action&&1<e.o.homeurl.indexOf("?")&&0==m.indexOf("?")&&(m=m.replace("?","&")),m="elementor_page"==
e.o.show_more.action?m:e.o.homeurl+m,e.o.overridewpdefault?"post"==e.o.override_method?d.submitToUrl(m,"post",{asp_active:1,p_asid:e.o.id,p_asp_data:c("form",e.n.searchsettings).serialize()},e.o.show_more.location):(m=m+"&asp_active=1&p_asid="+e.o.id+"&p_asp_data=1&"+c("form",e.n.searchsettings).serialize(),"same"==e.o.show_more.location?location.href=m:d.openInNewTab(m)):d.submitToUrl(m,"post",{np_asid:e.o.id,np_asp_data:c("form",e.n.searchsettings).serialize()},e.o.show_more.location)})):(e.n.showmore.css("display",
"none"),c("span",e.n.showmore).html("")))},fail:function(k){k.aborted||(e.n.resdrg.html(""),e.n.resdrg.html('<div class="asp_nores">The request failed. Please check your connection! Status: '+k.status+"</div>"),e.n.items=0<c(".item",e.n.resultsDiv).length?c(".item",e.n.resultsDiv):c(".photostack-flip",e.n.resultsDiv),e.results_num=0,e.searching=!1,e.hideLoader(),e.showResults(),e.scrollToResults())}})}})})(WPD.dom);
(function(c){let d=window.WPD.ajaxsearchpro.helpers;c.fn.extend(window.WPD.ajaxsearchpro.plugin,{searchFor:function(a){"undefined"!=typeof a&&this.n.text.val(a);this.n.textAutocomplete.val("");this.search(!1,!1,!1,!0)},searchRedirect:function(a){a=this.parseCustomRedirectURL(this.o.trigger.redirect_url,a);1<this.o.homeurl.indexOf("?")&&0==a.indexOf("?")&&(a=a.replace("?","&"));this.o.overridewpdefault?"post"==this.o.override_method?d.submitToUrl(this.o.homeurl+a,"post",{asp_active:1,p_asid:this.o.id,
p_asp_data:c("form",this.n.searchsettings).serialize()}):location.href=this.o.homeurl+a+"&asp_active=1&p_asid="+this.o.id+"&p_asp_data=1&"+c("form",this.n.searchsettings).serialize():d.submitToUrl(this.o.homeurl+a,"post",{np_asid:this.o.id,np_asp_data:c("form",this.n.searchsettings).serialize()})},toggleSettings:function(a){"undefined"!=typeof a?"show"==a?this.showSettings():this.hideSettings():1==this.n.prosettings.data("opened")?this.hideSettings():this.showSettings()},closeResults:function(a){"undefined"!=
typeof a&&a&&(this.n.text.val(""),this.n.textAutocomplete.val(""));this.hideResults();this.n.proloading.css("display","none");this.hideLoader();this.searchAbort()},getStateURL:function(){let a=location.href,b;a=a.split("p_asid");a=a[0];a=a.replace("&asp_active=1","");a=a.replace("?asp_active=1","");a="?"==a.slice(-1)?a.slice(0,-1):a;a="&"==a.slice(-1)?a.slice(0,-1):a;b=1<a.indexOf("?")?"&":"?";return a+b+"p_asid="+this.o.id+"&p_asp_data=1&"+c("form",this.n.searchsettings).serialize()},resetSearch:function(){this.resetSearchFilters()},
filtersInitial:function(){return 1==this.n.searchsettings.find("input[name=filters_initial]").val()},filtersChanged:function(){return 1==this.n.searchsettings.find("input[name=filters_changed]").val()}})})(WPD.dom);
(function(c){c.fn.extend(window.WPD.ajaxsearchpro.helpers,{Hooks:window.WPD.Hooks,deviceType:function(){let d=window.innerWidth;return 640>=d?"phone":1024>=d?"tablet":"desktop"},detectIOS:function(){return"undefined"!=typeof window.navigator&&"undefined"!=typeof window.navigator.userAgent?null!=window.navigator.userAgent.match(/(iPod|iPhone|iPad)/):!1},detectIE:function(){var d=window.navigator.userAgent;let a=d.indexOf("MSIE ");d=d.indexOf("Trident/");return 0<a||0<d?!0:!1},isMobile:function(){try{return document.createEvent("TouchEvent"),
!0}catch(d){return!1}},isTouchDevice:function(){return"ontouchstart"in window},isSafari:function(){return/^((?!chrome|android).)*safari/i.test(navigator.userAgent)},whichjQuery:function(d){let a=!1;"undefined"!=typeof window.$&&("undefined"===typeof d?a=window.$:"undefined"!=typeof window.$.fn[d]&&(a=window.$));!1===a&&"undefined"!=typeof window.jQuery&&(a=window.jQuery,"undefined"===typeof d?a=window.jQuery:"undefined"!=typeof window.jQuery.fn[d]&&(a=window.jQuery));return a},formData:function(d,
a){let b=this,f=d.find("input,textarea,select,button").get();if(1===arguments.length)return a={},f.forEach(function(g){g.name&&!g.disabled&&(g.checked||/select|textarea/i.test(g.nodeName)||/text/i.test(g.type)||c(g).hasClass("hasDatepicker")||c(g).hasClass("asp_slider_hidden"))&&(void 0==a[g.name]&&(a[g.name]=[]),c(g).hasClass("hasDatepicker")?a[g.name].push(c(g).parent().find(".asp_datepicker_hidden").val()):a[g.name].push(c(g).val()))}),JSON.stringify(a);"object"!=typeof a&&(a=JSON.parse(a));f.forEach(function(g){if(g.name)if(a[g.name]){let h=
a[g.name],e=c(g);"[object Array]"!==Object.prototype.toString.call(h)&&(h=[h]);if("checkbox"==g.type||"radio"==g.type){let n=e.val(),l=!1;for(let k=0;k<h.length;k++)if(h[k]==n){l=!0;break}e.prop("checked",l)}else e.val(h[0]),(c(g).hasClass("asp_gochosen")||c(g).hasClass("asp_goselect2"))&&WPD.intervalUntilExecute(function(n){n(g).trigger("change.asp_select2")},function(){return b.whichjQuery("asp_select2")},50,3),c(g).hasClass("hasDatepicker")&&WPD.intervalUntilExecute(function(n){let l=h[0],k=n(e.get(0)).datepicker("option",
"dateFormat");n(e.get(0)).datepicker("option","dateFormat","yy-mm-dd");n(e.get(0)).datepicker("setDate",l);n(e.get(0)).datepicker("option","dateFormat",k);n(e.get(0)).trigger("selectnochange")},function(){return b.whichjQuery("datepicker")},50,3)}else"checkbox"!=g.type&&"radio"!=g.type||c(g).prop("checked",!1)});return d},submitToUrl:function(d,a,b,f){let g;g=c('<form style="display: none;" />');g.attr("action",d);g.attr("method",a);c("body").append(g);"undefined"!==typeof b&&null!==b&&Object.keys(b).forEach(function(h){let e=
b[h],n=c('<input type="hidden" />');n.attr("name",h);n.attr("value",e);g.append(n)});"undefined"!=typeof f&&"new"==f&&g.attr("target","_blank");g.get(0).submit()},openInNewTab:function(d){Object.assign(document.createElement("a"),{target:"_blank",href:d}).click()},isScrolledToBottom:function(d,a){return d.scrollHeight-d.scrollTop-c(d).outerHeight()<a},getWidthFromCSSValue:function(d,a){d+="";d=-1<d.indexOf("px")?parseInt(d,10):-1<d.indexOf("%")?"undefined"!=typeof a&&null!=a?Math.floor(parseInt(d,
10)/100*a):parseInt(d,10):parseInt(d,10);return 100>d?100:d},nicePhrase:function(d){return encodeURIComponent(d).replace(/%20/g,"+")},unqoutePhrase:function(d){return d.replace(/["']/g,"")},decodeHTMLEntities:function(d){let a=document.createElement("div");d&&"string"===typeof d&&(d=d.replace(/<script[^>]*>([\S\s]*?)<\/script>/gmi,""),d=d.replace(/<\/?\w(?:[^"'>]|"[^"]*"|'[^']*')*>/gmi,""),a.innerHTML=d,d=a.textContent,a.textContent="");return d},isScrolledToRight:function(d){return d.scrollWidth-
c(d).outerWidth()===d.scrollLeft},isScrolledToLeft:function(d){return 0===d.scrollLeft},wp_hooks_apply_filters:function(){return"undefined"!=typeof wp&&"undefined"!=typeof wp.hooks&&"undefined"!=typeof wp.hooks.applyFilters?wp.hooks.applyFilters.apply(null,arguments):"undefined"!=typeof arguments[1]?arguments[1]:!1}})})(WPD.dom);
(function(c){let d=window.WPD.ajaxsearchpro.helpers;c.fn.extend(window.WPD.ajaxsearchpro.plugin,{detectAndFixFixedPositioning:function(){let a=!1,b=this.n.search.get(0);for(;b;)if(b=b.parentElement,null!=b&&"fixed"==window.getComputedStyle(b).position){a=!0;break}a||"fixed"==this.n.search.css("position")?("absolute"==this.n.resultsDiv.css("position")&&this.n.resultsDiv.css("position","fixed"),this.o.blocking||this.n.searchsettings.css("position","fixed")):("fixed"==this.n.resultsDiv.css("position")&&
this.n.resultsDiv.css("position","absolute"),this.o.blocking||this.n.searchsettings.css("position","absolute"))},fixAccessibility:function(){this.n.searchsettings.find("input.asp_select2-search__field").attr("aria-label","Select2 search")},fixTryThisPosition:function(){this.n.trythis.css({left:this.n.search.position().left})},fixResultsPosition:function(a){a="undefined"==typeof a?!1:a;var b=c("body");let f=0;var g=this.n.resultsDiv.css("position");if(0!=c._fn.bodyTransformY()||"static"!=b.css("position"))f=
b.offset().top;0!=c._fn.bodyTransformY()&&"fixed"==g&&(g="absolute",this.n.resultsDiv.css("position","absolute"));"fixed"==g&&(f=0);if("fixed"==g||"absolute"==g)if(1==a||"visible"==this.n.resultsDiv.css("visibility"))if(a=this.n.search.offset(),g="fixed"!=g?c("body").offset().left:0,"undefined"!=typeof a){let h=0;b="phone"==d.deviceType()?this.o.results.width_phone:"tablet"==d.deviceType()?this.o.results.width_tablet:this.o.results.width;"auto"==b&&(b=240>this.n.search.outerWidth()?240:this.n.search.outerWidth());
this.n.resultsDiv.css("width",isNaN(b)?b:b+"px");"right"==this.o.resultsSnapTo?h=this.n.resultsDiv.outerWidth()-this.n.search.outerWidth():"center"==this.o.resultsSnapTo&&(h=Math.floor((this.n.resultsDiv.outerWidth()-parseInt(this.n.search.outerWidth()))/2));this.n.resultsDiv.css({top:a.top+this.n.search.outerHeight(!0)-f+"px",left:a.left-h-g+"px"})}},fixSettingsPosition:function(a){a="undefined"==typeof a?!1:a;var b=c("body"),f=0,g=this.n.searchsettings.css("position");if(0!=c._fn.bodyTransformY()||
"static"!=b.css("position"))f=b.offset().top;0!=c._fn.bodyTransformY()&&"fixed"==g&&(g="absolute",this.n.searchsettings.css("position","absolute"));"fixed"==g&&(f=0);1!=a&&0==this.n.prosettings.data("opened")||1==this.o.blocking||(a="fixed"!=g?c("body").offset().left:0,this.fixSettingsWidth(),"undefined"!==typeof WebKitCSSMatrix&&(b=window.getComputedStyle(document.body),"undefined"!=typeof b.transform&&"undefined"!=typeof b.transform.m42&&0!=(new WebKitCSSMatrix(b.transform)).m42&&(f=c("body").offset().top)),
b="none"!=this.n.prosettings.css("display")?this.n.prosettings:this.n.promagnifier,g=b.offset(),f=g.top+b.height()-2-f+"px",b="left"==this.o.settingsimagepos?g.left:g.left+b.width()-this.n.searchsettings.width(),b=b-a+"px",this.n.searchsettings.css({display:"block",top:f,left:b}))},fixSettingsWidth:function(){if(!this.o.blocking&&"masonry"!=this.o.fss_layout&&(this.n.searchsettings.css({width:"100%"}),10<this.n.searchsettings.width()%c("fieldset",this.n.searchsettings).outerWidth(!0))){let a=Math.floor(this.n.searchsettings.width()/
c("fieldset",this.n.searchsettings).outerWidth(!0));a=0>=a?1:a;this.n.searchsettings.css({width:a*c("fieldset",this.n.searchsettings).outerWidth(!0)+8+"px"})}},hideOnInvisibleBox:function(){1!=this.o.detectVisibility||0!=this.o.compact.enabled||this.n.search.hasClass("hiddend")||this.n.search.isVisible()||(this.hideSettings(),this.hideResults())}})})(WPD.dom);
(function(c){let d=window.WPD.ajaxsearchpro.helpers;c.fn.extend(window.WPD.ajaxsearchpro.plugin,{initMagnifierEvents:function(){let a=this;a.n.promagnifier.on("click",function(b){let f=a.n.search.attr("asp-compact")||"closed";a.keycode=b.keyCode||b.which;a.ktype=b.type;if(1==a.o.compact.enabled&&("closed"==f||1==a.o.compact.closeOnMagnifier&&"open"==f))return!1;a.gaEvent("magnifier");if(a.n.text.val().length>=a.o.charcount&&1==a.o.redirectOnClick&&"first_result"!=a.o.trigger.click)return a.doRedirectToResults("click"),
clearTimeout(void 0),!1;if("ajax_search"!=a.o.trigger.click&&"first_result"!=a.o.trigger.click)return!1;a.searchAbort();clearTimeout(a.timeouts.search);a.n.proloading.css("display","none");a.n.text.val().length>=a.o.charcount&&(a.timeouts.search=setTimeout(function(){c("form",a.n.searchsettings).serialize()+a.n.text.val().trim()!=a.lastSuccesfulSearch||!a.resultsOpened&&!a.usingLiveLoader?a.search():a.isRedirectToFirstResult()?a.doRedirectToFirstResult():a.n.proclose.css("display","block")},a.o.trigger.delay))})},
initButtonEvents:function(){let a=this;a.n.searchsettings.find("button.asp_s_btn").on("click",function(b){a.ktype="button";b.preventDefault();if(a.n.text.val().length>=a.o.charcount){if("ajax_search"!=a.o.sb.redirect_action)if("first_result"!=a.o.sb.redirect_action)a.doRedirectToResults("button");else{if(a.isRedirectToFirstResult())return a.doRedirectToFirstResult(),!1;a.search()}else c("form",a.n.searchsettings).serialize()+a.n.text.val().trim()==a.lastSuccesfulSearch&&a.resultsOpened||a.search();
clearTimeout(a.timeouts.search)}});a.n.searchsettings.find("button.asp_r_btn").on("click",function(b){let f=d.formData(c("form",a.n.searchsettings)),g=a.n.text.val();b.preventDefault();a.resetSearchFilters();"live"!=a.o.rb.action||JSON.stringify(f)==JSON.stringify(d.formData(c("form",a.n.searchsettings)))&&""==g?"close"==a.o.rb.action&&a.hideResults():a.search(!1,!1,!1,!0,!0)})}})})(WPD.dom);
(function(c){let d=window.WPD.ajaxsearchpro.helpers;c.fn.extend(window.WPD.ajaxsearchpro.plugin,{initInputEvents:function(){this._initFocusInput();this._initSearchInput();this._initEnterEvent();this._initFormEvent()},_initFocusInput:function(){let a=this;a.n.text.on("click",function(b){b.stopPropagation();b.stopImmediatePropagation();c(this).trigger("focus");a.gaEvent("focus");if(c("form",a.n.searchsettings).serialize()+a.n.text.val().trim()==a.lastSuccesfulSearch)return a.resultsOpened||a.usingLiveLoader||
(a._no_animations=!0,a.showResults(),a._no_animations=!1),!1});a.n.text.on("focus input",function(b){a.searching||(""!=c(this).val()?a.n.proclose.css("display","block"):a.n.proclose.css({display:"none"}))})},_initSearchInput:function(){let a=this,b=a.n.text.val();a.n.text.on("input",function(f){a.keycode=f.keyCode||f.which;a.ktype=f.type;if(d.detectIE()){if(b==a.n.text.val())return!1;b=a.n.text.val()}if(!a.o.trigger.type)return a.searchAbort(),clearTimeout(a.timeouts.search),a.hideLoader(),!1;a.hideArrowBox();
if(a.n.text.val().length<a.o.charcount)return a.n.proloading.css("display","none"),0==a.o.blocking&&a.hideSettings(),a.hideResults(!1),a.searchAbort(),clearTimeout(a.timeouts.search),!1;a.searchAbort();clearTimeout(a.timeouts.search);a.n.proloading.css("display","none");a.timeouts.search=setTimeout(function(){c("form",a.n.searchsettings).serialize()+a.n.text.val().trim()!=a.lastSuccesfulSearch||!a.resultsOpened&&!a.usingLiveLoader?a.search():a.isRedirectToFirstResult()?a.doRedirectToFirstResult():
a.n.proclose.css("display","block")},a.o.trigger.delay)})},_initEnterEvent:function(){let a=this,b,f=!1;a.n.text.on("keyup",function(g){a.keycode=g.keyCode||g.which;a.ktype=g.type;if(13==a.keycode){clearTimeout(b);b=setTimeout(function(){f=!1},300);if(f)return!1;f=!0}g=c(this).hasClass("orig");a.n.text.val().length>=a.o.charcount&&g&&13==a.keycode&&(a.gaEvent("return"),1==a.o.redirectOnEnter?"first_result"!=a.o.trigger.return?a.doRedirectToResults(a.ktype):a.search():"ajax_search"==a.o.trigger.return&&
(c("form",a.n.searchsettings).serialize()+a.n.text.val().trim()==a.lastSuccesfulSearch&&a.resultsOpened||a.search()),clearTimeout(a.timeouts.search))})},_initFormEvent:function(){let a=this;c(a.n.text.closest("form").get(0)).on("submit",function(b,f){b.preventDefault();d.isMobile()?a.o.redirectOnEnter?(b=new Event("keyup"),b.keyCode=b.which=13,this.n.text.get(0).dispatchEvent(b)):(a.search(),document.activeElement.blur()):"undefined"!=typeof f&&"ajax"==f&&a.search()})}})})(WPD.dom);
(function(c){let d=window.WPD.ajaxsearchpro,a=window.WPD.ajaxsearchpro.helpers;c.fn.extend(window.WPD.ajaxsearchpro.plugin,{initOtherEvents:function(){let b=this;if(a.isMobile()&&a.detectIOS())b.n.text.on("touchstart",function(){b.savedScrollTop=window.scrollY;b.savedContainerTop=b.n.search.offset().top});if(b.o.focusOnPageload)c(window).on("load",function(){b.n.text.get(0).focus()},{options:{once:!0}});b.n.proclose.on(b.clickTouchend,function(g){g.preventDefault();g.stopImmediatePropagation();b.n.text.val("");
b.n.textAutocomplete.val("");b.hideResults();b.n.text.trigger("focus");b.n.proloading.css("display","none");b.hideLoader();b.searchAbort();0<c(".asp_es_"+b.o.id).length?(b.showLoader(),b.liveLoad(".asp_es_"+b.o.id,b.getCurrentLiveURL(),!1)):b.o.resPage.useAjax&&(b.showLoader(),b.liveLoad(b.o.resPage.selector,b.getRedirectURL()));b.n.text.get(0).focus()});if(a.isMobile()){var f=function(){b.orientationChange();setTimeout(function(){b.orientationChange()},600)};b.documentEventHandlers.push({node:window,
event:"orientationchange",handler:f});c(window).on("orientationchange",f)}else f=function(){b.resize()},b.documentEventHandlers.push({node:window,event:"resize",handler:f}),c(window).on("resize",f,{passive:!0});f=function(){b.scrolling(!1)};b.documentEventHandlers.push({node:window,event:"scroll",handler:f});c(window).on("scroll",f,{passive:!0});if(a.isMobile()&&""!=b.o.mobile.menu_selector)c(b.o.mobile.menu_selector).on("touchend",function(){let g=this;setTimeout(function(){let h=c(g).find("input.orig");
h=0==h.length?c(g).next().find("input.orig"):h;h=0==h.length?c(g).parent().find("input.orig"):h;h=0==h.length?b.n.text:h;b.n.search.is(":visible")&&h.get(0).focus()},300)});a.detectIOS()&&a.isMobile()&&a.isTouchDevice()&&16>parseInt(b.n.text.css("font-size"))&&(b.n.text.data("fontSize",b.n.text.css("font-size")).css("font-size","16px"),b.n.textAutocomplete.css("font-size","16px"),c("body").append("<style>#ajaxsearchpro"+b.o.rid+" input.orig::-webkit-input-placeholder{font-size: 16px !important;}</style>"))},
orientationChange:function(){this.detectAndFixFixedPositioning();this.fixSettingsPosition();this.fixResultsPosition();this.fixTryThisPosition();"isotopic"==this.o.resultstype&&"visible"==this.n.resultsDiv.css("visibility")&&(this.calculateIsotopeRows(),this.showPagination(!0),this.removeAnimation())},resize:function(){this.detectAndFixFixedPositioning();this.fixSettingsPosition();this.fixResultsPosition();this.fixTryThisPosition();this.hideArrowBox();"isotopic"==this.o.resultstype&&"visible"==this.n.resultsDiv.css("visibility")&&
(this.calculateIsotopeRows(),this.showPagination(!0),this.removeAnimation())},scrolling:function(b){this.detectAndFixFixedPositioning();this.hideOnInvisibleBox();this.fixSettingsPosition(b);this.fixResultsPosition(b)},initTryThisEvents:function(){let b=this;b.n.trythis.find("a").on("click touchend",function(f){f.preventDefault();f.stopImmediatePropagation();b.o.compact.enabled&&"closed"==(b.n.search.attr("asp-compact")||"closed")&&b.n.promagnifier.trigger("click");document.activeElement.blur();b.n.textAutocomplete.val("");
b.n.text.val(c(this).html());b.gaEvent("try_this");setTimeout(function(){b.n.text.trigger("input")},50)})},initPrevState:function(){let b=this;d.firstIteration&&null==d.prevState&&(d.prevState=localStorage.getItem("asp-"+WPD.Base64.encode(location.href)),null!=d.prevState&&(d.prevState=JSON.parse(d.prevState),d.prevState.settings=WPD.Base64.decode(d.prevState.settings)));if(null!=d.prevState&&"undefined"!=typeof d.prevState.id&&(d.prevState.trigger&&d.prevState.id==b.o.id&&d.prevState.instance==b.o.iid&&
(""!=d.prevState.phrase&&(b.triggerPrevState=!0,b.n.text.val(d.prevState.phrase)),a.formData(c("form",b.n.searchsettings))!=d.prevState.settings&&(b.triggerPrevState=!0,b.settingsChanged=!0,a.formData(c("form",b.n.searchsettings),d.prevState.settings)),null!==d.prevState.settingsOriginal&&(b.originalFormData=WPD.Base64.decode(d.prevState.settingsOriginal),b.setFilterStateInput(0))),"block"==b.o.resultsposition)){let g=!0;b.n.search.on("asp_results_show",function(){g&&(g=!1,setTimeout(function(){let h=
0<c(d.prevState.scrollTo).length?c(d.prevState.scrollTo).offset().top:b.n.resultsDiv.find(".item").last().offset().top;window.scrollTo({top:h,behavior:"instant"})},500))})}localStorage.removeItem("asp-"+WPD.Base64.encode(location.href));let f=function(){var g=b.n.text.val();g={id:b.o.id,trigger:""!=g||b.settingsChanged,instance:b.o.iid,phrase:g,settingsOriginal:"undefined"===typeof b.originalFormData?null:WPD.Base64.encode(b.originalFormData),settings:WPD.Base64.encode(a.formData(c("form",b.n.searchsettings)))};
localStorage.setItem("asp-"+WPD.Base64.encode(location.href),JSON.stringify(g))};c(".asp_es_"+b.o.id).on("click","a",f);b.n.resultsDiv.on("click",".results .item",f);b.documentEventHandlers.push({node:document.body,event:"asp_memorize_state_"+b.o.id,handler:f});c("body").on("asp_memorize_state_"+b.o.id,f)},initSelect2:function(){let b=this;window.WPD.intervalUntilExecute(function(f){"undefined"!==typeof f.fn.asp_select2&&(b.select2jQuery=f,c("select.asp_gochosen, select.asp_goselect2",b.n.searchsettings).each(function(){c(this).removeAttr("data-asp_select2-id");
c(this).find('option[value=""]').val("__any__");b.select2jQuery(this).asp_select2({width:"100%",theme:"flat",allowClear:0<c(this).find('option[value=""]').length,language:{noResults:function(){return b.o.select2.nores}}});b.select2jQuery(this).on("change",function(){c(this).trigger("change")})}))},function(){return a.whichjQuery("asp_select2")})}})})(WPD.dom);
(function(c){c.fn.extend(window.WPD.ajaxsearchpro.plugin,{initResultsEvents:function(){let d=this;d.n.resultsDiv.css({opacity:"0"});let a=function(b){let f=b.keyCode||b.which,g=b.type;if(0==c(b.target).closest(".asp_w").length&&(0!=d.o.blocking||d.dragging||0!=c(b.target).closest(".ui-datepicker").length||0!=c(b.target).closest(".noUi-handle").length||0!=c(b.target).closest(".asp_select2").length||0!=c(b.target).closest(".asp_select2-container").length||d.hideSettings(),d.hideOnInvisibleBox(),d.hideArrowBox(),
"click"!=g||"touchend"!=g||3!=f)){if(d.o.compact.enabled)b=d.n.search.attr("asp-compact")||"closed",1!=d.o.compact.closeOnDocument||"open"!=b||d.resultsOpened||(d.closeCompact(),d.searchAbort(),d.hideLoader());else if(0==d.resultsOpened||1!=d.o.closeOnDocClick)return;d.dragging||(d.hideLoader(),d.searchAbort(),d.hideResults())}};d.documentEventHandlers.push({node:document,event:d.clickTouchend,handler:a});c(document).on(d.clickTouchend,a);"isotopic"==d.o.resultstype&&(d.n.resultsDiv.on("swiped-left",
function(){d.visiblePagination()&&d.n.resultsDiv.find("a.asp_next").trigger("click")}),d.n.resultsDiv.on("swiped-right",function(){d.visiblePagination()&&d.n.resultsDiv.find("a.asp_prev").trigger("click")}))}})})(WPD.dom);(function(c){c.fn.extend(window.WPD.ajaxsearchpro.plugin,{monitorTouchMove:function(){let d=this;d.dragging=!1;c("body").on("touchmove",function(){d.dragging=!0}).on("touchstart",function(){d.dragging=!1})}})})(WPD.dom);
(function(c){let d=window.WPD.ajaxsearchpro;c.fn.extend(window.WPD.ajaxsearchpro.plugin,{initAutop:function(){let a=this;if(null!=d.prevState&&!a.o.compact.enabled&&a.triggerPrevState)return a.searchWithCheck(800),d.prevState=null,!1;if("disabled"==a.o.autop.state)return!1;let b=window.location.href;if(-1<b.indexOf("asp_ls=")||-1<b.indexOf("asp_ls&"))return!1;let f=a.o.show_more.enabled&&"ajax"==a.o.show_more.action?!1:a.o.autop.count;window.WPD.intervalUntilExecute(function(){a.isAutoP=!0;"phrase"==
a.o.autop.state?(a.o.is_results_page||a.n.text.val(a.o.autop.phrase),a.search(f)):"latest"==a.o.autop.state?a.search(f,1):a.search(f,2)},function(){return!window.ASP.css_async||"undefined"!=typeof window.ASP.css_loaded})}})})(WPD.dom);
(function(c){let d=window.WPD.ajaxsearchpro.helpers;c.fn.extend(window.WPD.ajaxsearchpro.plugin,{initEtc:function(){let a=this,b=null;a.n.trythis.css({visibility:"visible"});c("div.asp_option",a.n.searchsettings).on(a.mouseupTouchend,function(f){f.preventDefault();f.stopImmediatePropagation();if(a.dragging)return!1;c(this).find('input[type="checkbox"]').prop("checked",!c(this).find('input[type="checkbox"]').prop("checked"));clearTimeout(b);let g=this;b=setTimeout(function(){c(g).find('input[type="checkbox"]').trigger("asp_chbx_change")},
50)});c("div.asp_option label",a.n.searchsettings).on("click",function(f){f.preventDefault()});c("fieldset.asp_checkboxes_filter_box",a.n.searchsettings).each(function(){let f=!0;c(this).find('.asp_option:not(.asp_option_selectall) input[type="checkbox"]').each(function(){if(1==c(this).prop("checked"))return f=!1});f&&c(this).find('.asp_option_selectall input[type="checkbox"]').prop("checked",!1).removeAttr("data-origvalue")});c("fieldset",a.n.searchsettings).each(function(){c(this).find(".asp_option:not(.hiddend)").last().addClass("asp-o-last")});
c('.asp_option_cat input[type="checkbox"], .asp_option_cff input[type="checkbox"]',a.n.searchsettings).on("asp_chbx_change",function(){let f=c(this).data("targetclass");"string"==typeof f&&""!=f&&c("input."+f,a.n.searchsettings).prop("checked",c(this).prop("checked"))});a.n.resultsDiv.on("click",".results .item",function(){a.gaEvent("result_click",{result_title:c(this).find("a.asp_res_url").text(),result_url:c(this).find("a.asp_res_url").attr("href")});1==a.o.singleHighlight&&(localStorage.removeItem("asp_phrase_highlight"),
""!=a.n.text.val().replace(/["']/g,"")&&localStorage.setItem("asp_phrase_highlight",JSON.stringify({phrase:a.n.text.val().replace(/["']/g,""),id:a.o.id})))});a.il={columns:3,rows:a.o.isotopic.pagination?a.o.isotopic.rows:1E4,itemsPerPage:6,lastVisibleItem:-1};a.filterFns={number:function(f,g){if("undefined"===typeof g||"object"===typeof f)g=f;f=c(g).attr("data-itemnum");const h=a.currentPage,e=a.il.itemsPerPage;f%(a.il.columns*a.il.rows)<a.il.columns*(a.il.rows-1)?c(g).addClass("asp_gutter_bottom"):
c(g).removeClass("asp_gutter_bottom");return parseInt(f,10)<e*h&&parseInt(f,10)>=e*(h-1)}};d.Hooks.addFilter("asp/init/etc",a)},initInfiniteScroll:function(){let a=this;if(a.o.show_more.infinite&&"polaroid"!=a.o.resultstype){let b,f;f=function(){clearTimeout(b);b=setTimeout(function(){a.checkAndTriggerInfiniteScroll("window")},80)};a.documentEventHandlers.push({node:window,event:"scroll",handler:f});c(window).on("scroll",f);a.n.results.on("scroll",f);let g;a.n.resultsDiv.on("nav_switch",function(){clearTimeout(g);
g=setTimeout(function(){a.checkAndTriggerInfiniteScroll("isotopic")},800)})}},hooks:function(){let a=this;a.n.s.on("asp_elementor_results",function(b,f){a.o.id==f&&"function"==typeof jetpackLazyImagesModule&&setTimeout(function(){jetpackLazyImagesModule()},300)})}})})(WPD.dom);
(function(c){let d=window.WPD.ajaxsearchpro,a=window.WPD.ajaxsearchpro.helpers;c.fn.extend(window.WPD.ajaxsearchpro.plugin,{init:function(b,f){this.autopStartedTheSearch=this.isAutoP=this.triggerPrevState=this.searching=!1;this.autopData={};this.resultsOpened=this.settingsChanged=!1;this.postAuto=this.post=null;this.scroll={};this.savedContainerTop=this.savedScrollTop=0;this.is_scroll="undefined"!=typeof asp_SimpleBar;this.disableMobileScroll=!1;this.clickTouchend="click touchend";this.mouseupTouchend=
"mouseup touchend";this.noUiSliders=[];this.timeouts={compactBeforeOpen:null,compactAfterOpen:null,search:null,searchWithCheck:null};this.eh={};this.documentEventHandlers=[];this.settScroll=null;this.currentPage=1;this.sIsotope=this.isotopic=null;this.lastSuccesfulSearch="";this.lastSearchData={};this._no_animations=!1;this.results_num=this.call_num=0;this.o=c.fn.extend({},b);this.n={};this.n.search=c(f);this.initNodeVariables();"undefined"!=typeof ASP.scrollbar&&0==ASP.scrollbar&&(this.is_scroll=
!1);"horizontal"==this.o.resultstype&&0==this.o.scrollBar.horizontal.enabled&&(this.is_scroll=!1);a.isMobile()?this.animOptions=this.o.animations.mob:this.animOptions=this.o.animations.pc;this.animationOpacity=0>this.animOptions.items.indexOf("In")?"opacityOne":"opacityZero";this.resInfoBoxTxt=0<this.n.resultsDiv.find(".asp_results_top p.asp_rt_phrase").length?this.n.resultsDiv.find(".asp_results_top p.asp_rt_phrase").html():"";this.resInfoBoxTxtNoPhrase=0<this.n.resultsDiv.find(".asp_results_top p.asp_rt_nophrase").length?
this.n.resultsDiv.find(".asp_results_top p.asp_rt_nophrase").html():"";this.o.resPage.useAjax=this.o.compact.enabled?0:this.o.resPage.useAjax;a.isMobile()&&(this.o.trigger.type=this.o.mobile.trigger_on_type,this.o.trigger.click=this.o.mobile.click_action,this.o.trigger.click_location=this.o.mobile.click_action_location,this.o.trigger.return=this.o.mobile.return_action,this.o.trigger.return_location=this.o.mobile.return_action_location,this.o.trigger.redirect_url=this.o.mobile.redirect_url,this.o.trigger.elementor_url=
this.o.mobile.elementor_url);this.o.redirectOnClick="ajax_search"!=this.o.trigger.click&&"nothing"!=this.o.trigger.click;this.o.redirectOnEnter="ajax_search"!=this.o.trigger.return&&"nothing"!=this.o.trigger.return;if(this.usingLiveLoader=this.o.resPage.useAjax&&0<c(this.o.resPage.selector).length||0<c(".asp_es_"+this.o.id).length)this.o.trigger.type=this.o.resPage.trigger_type,this.o.trigger.facet=this.o.resPage.trigger_facet,this.o.resPage.trigger_magnifier&&(this.o.redirectOnClick=0,this.o.trigger.click=
"ajax_search"),this.o.resPage.trigger_return&&(this.o.redirectOnEnter=0,this.o.trigger.click="ajax_search");this.o.trigger.redirect_url=a.decodeHTMLEntities(this.o.trigger.redirect_url);this.o.trigger.elementor_url=a.decodeHTMLEntities(this.o.trigger.elementor_url);this.n.textAutocomplete.val("");1==this.o.compact.overlay&&0==c("#asp_absolute_overlay").length&&c("body").append("<div id='asp_absolute_overlay'></div>");1==ASP.js_retain_popstate&&this.initPrevState();"undefined"!==typeof this.initCompact&&
this.initCompact();this.detectAndFixFixedPositioning();this.monitorTouchMove();this.initSettingsAnimations();this.initResultsAnimations();this.initEvents();this.initAutop();this.initEtc();this.initInfiniteScroll();this.fixAccessibility();this.hooks();d.firstIteration=!1;"undefined"===typeof this.originalFormData&&(this.originalFormData=a.formData(c("form",this.n.searchsettings)));this.n.s.trigger("asp_init_search_bar",[this.o.id,this.o.iid],!0,!0);return this},initNodeVariables:function(){this.n.s=
this.n.search;this.n.container=this.n.search.closest(".asp_w_container");this.o.id=this.n.search.data("id");this.o.iid=this.n.search.data("instance");this.o.rid=this.o.id+"_"+this.o.iid;this.o.name=this.n.search.data("name");this.n.searchsettings=c(".asp_ss",this.n.container);this.n.resultsDiv=c(".asp_r",this.n.container);this.n.probox=c(".probox",this.n.search);this.n.proinput=c(".proinput",this.n.search);this.n.text=c(".proinput input.orig",this.n.search);this.n.textAutocomplete=c(".proinput input.autocomplete",
this.n.search);this.n.loading=c(".proinput .loading",this.n.search);this.n.proloading=c(".proloading",this.n.search);this.n.proclose=c(".proclose",this.n.search);this.n.promagnifier=c(".promagnifier",this.n.search);this.n.prosettings=c(".prosettings",this.n.search);this.fixClonedSelf();this.n.settingsAppend=c("#wpdreams_asp_settings_"+this.o.id);this.o.blocking=this.n.searchsettings.hasClass("asp_sb");"undefined"!==typeof this.initSettingsBox&&this.initSettingsBox();this.n.trythis=c("#asp-try-"+this.o.rid);
this.n.resultsAppend=c("#wpdreams_asp_results_"+this.o.id);this.initResultsBox();this.n.hiddenContainer=c(".asp_hidden_data",this.n.container);this.n.aspItemOverlay=c(".asp_item_overlay",this.n.hiddenContainer);this.n.showmore=c(".showmore",this.n.resultsDiv);this.n.items=0<c(".item",this.n.resultsDiv).length?c(".item",this.n.resultsDiv):c(".photostack-flip",this.n.resultsDiv);this.n.results=c(".results",this.n.resultsDiv);"polaroid"==this.o.resultstype&&this.n.results.addClass("photostack");this.n.resdrg=
c(".resdrg",this.n.resultsDiv)},initEvents:function(){"undefined"!==typeof this.initSettingsEvents&&this.initSettingsEvents();this.initResultsEvents();this.initOtherEvents();this.initTryThisEvents();this.initButtonEvents();this.initMagnifierEvents();this.initInputEvents();1==this.o.compact.enabled&&this.initCompactEvents();"undefined"!==typeof this.initAutocompleteEvent&&this.initAutocompleteEvent();"undefined"!==typeof this.initNavigationEvents&&(this.initNavigationEvents(),this.initIsotopicPagination());
"undefined"!==typeof this.initNoUIEvents&&(this.initNoUIEvents(),this.initDatePicker(),this.initSelect2(),this.initFacetEvents())}})})(WPD.dom);
(function(c){let d=window.WPD.ajaxsearchpro.helpers;c.fn.extend(window.WPD.ajaxsearchpro.plugin,{initResultsBox:function(){d.isMobile()&&1==this.o.mobile.force_res_hover?(this.o.resultsposition="hover",this.n.resultsDiv=this.n.resultsDiv.clone(),c("body").append(this.n.resultsDiv),this.n.resultsDiv.css({position:"absolute"}),this.detectAndFixFixedPositioning()):"hover"==this.o.resultsposition&&0>=this.n.resultsAppend.length?(this.n.resultsDiv=this.n.resultsDiv.clone(),c("body").append(this.n.resultsDiv)):
(this.o.resultsposition="block",this.n.resultsDiv.css({position:"static"}),0<this.n.resultsAppend.length&&(0<this.n.resultsAppend.find(".asp_r_"+this.o.id).length?(this.n.resultsDiv=this.n.resultsAppend.find(".asp_r_"+this.o.id),"undefined"!==typeof this.n.resultsDiv.get(0).referenced?++this.n.resultsDiv.get(0).referenced:this.n.resultsDiv.get(0).referenced=1,this.n.showmore=c(".showmore",this.n.resultsDiv),this.n.items=0<c(".item",this.n.resultsDiv).length?c(".item",this.n.resultsDiv):c(".photostack-flip",
this.n.resultsDiv),this.n.results=c(".results",this.n.resultsDiv),this.n.resdrg=c(".resdrg",this.n.resultsDiv)):(this.n.resultsDiv=this.n.resultsDiv.clone(),this.n.resultsAppend.append(this.n.resultsDiv))));this.n.resultsDiv.get(0).id=this.n.resultsDiv.get(0).id.replace("__original__","")},initResultsAnimations:function(){let a=this.n.resultsDiv.css("position");this.resAnim={showClass:"",showCSS:{visibility:"visible",display:"block",opacity:1,"animation-duration":this.animOptions.results.dur+"ms"},
hideClass:"",hideCSS:{visibility:"hidden",opacity:0,display:"none"},duration:this.animOptions.results.dur+"ms"};"fade"==this.animOptions.results.anim&&(this.resAnim.showClass="asp_an_fadeIn",this.resAnim.hideClass="asp_an_fadeOut");"fadedrop"!=this.animOptions.results.anim||"fixed"!=a&&"absolute"!=a?"fadedrop"==this.animOptions.results.anim&&(this.resAnim.showClass="asp_an_fadeIn",this.resAnim.hideClass="asp_an_fadeOut"):(this.resAnim.showClass="asp_an_fadeInDrop",this.resAnim.hideClass="asp_an_fadeOutDrop");
this.n.resultsDiv.css({"-webkit-animation-duration":this.settAnim.duration+"ms","animation-duration":this.settAnim.duration+"ms"})}})})(WPD.dom);
(function(c){c(".ajaxsearchprotop").each(function(){let d=JSON.parse(c(this).data("aspdata")),a=d.id;if(0==d.action)c("a",c(this)).on("click",function(b){b.preventDefault()});else if(2==d.action)c("a",c(this)).on("click",function(b){b.preventDefault();ASP.api(a,"searchFor",c(this).html());c("html").animate({scrollTop:c("div[id*=ajaxsearchpro"+a+"_]").first().offset().top-40},500)});else if(1==d.action)c("a",c(this)).on("click",function(b){if(ASP.api(a,"exists"))return b.preventDefault(),ASP.api(a,
"searchRedirect",c(this).html())})})})(WPD.dom);window.ASP="undefined"!==typeof window.ASP?window.ASP:{};
window.ASP.api=function(){let c=function(b,f,g,h){b=ASP.instances.get(b,f);return!1!==b&&b[g].apply(b,[h])},d=function(b,f,g){if(!isNaN(parseFloat(f))&&isFinite(f))return b=ASP.instances.get(b,f),!1!==b&&b[g].apply(b);b=ASP.instances.get(b);return!1!==b&&b.forEach(function(h){h[f].apply(h,[g])})},a=function(b,f){if("exists"==f)return ASP.instances.exist(b);b=ASP.instances.get(b);return!1!==b&&b.forEach(function(g){g[f].apply(g)})};if(4==arguments.length)return c.apply(this,arguments);if(3==arguments.length)return d.apply(this,
arguments);if(2==arguments.length)return a.apply(this,arguments);0==arguments.length&&(console.log("Usage: ASP.api(id, [optional]instance, function, [optional]args);"),console.log("For more info: https://knowledgebase.ajaxsearchpro.com/other/javascript-api"))};
