<div class="ttd-typography ttd-main-wrapper large">
	<div class="ttd-page-title">
		<?php echo __( "Your Theme's Basic Typography", 'thrive-theme' ); ?>
	</div>

	<button class="ttd-new-set click" data-fn="create">+ <?php echo __( 'Create New Set', 'thrive-theme' ); ?></button>

	<div class="ttd-default-typography"></div>

	<hr/>

	<h3 class="ttd-subtitle"><?php echo __( 'Other Available Typography Sets', 'thrive-theme' ); ?></h3>

	<div class="ttd-other-typography"></div>
</div>
