<# var style = item.get('video_style'); #>
<# var options = item.get('options'); #>
<div class="tge-video-form tge-video-style-<#= style.selected #>">
	<div class="tqb-video-container-responsive">
		<video height="313" width="551"
		<#= 1 === options.autoplay.value ? ' autoplay="true"' : '' #>
		<#= 1 === options.hide_controls.value ? '' : ' controls="true"' #>
		<#= 1 === options.loop.value ? ' loop="true"' : '' #>
		allowtransparency="true"
		frameborder="0">
		<source src="<#= item.get( 'url' ) #>" type="<#= mime #>">
		<?php echo __( 'Not supported video tag', Thrive_Quiz_Builder::T ); ?>
		</video>
	</div>
</div>
