<div class="tvd-modal-content yt-video">
	<iframe width="800px" height="450px" allowfullscreen mozallowfullscreen webkitallowfullscreen oallowfullscreen msallowfullscreen allow="autoplay; encrypted-media"></iframe>
</div>
<a class="tvd-modal-action tvd-modal-close tvd-modal-close-x tvd-modal-close-x-yt" href="javascript:void(0)">
	<span class="tvd-icon-close-modal">
 <svg id="icon-close2" viewBox="0 0 30 32">
            <path d="M0.655 2.801l1.257-1.257 27.655 27.655-1.257 1.257-27.655-27.655z"/>
            <path d="M28.31 1.543l1.257 1.257-27.655 27.655-1.257-1.257 27.655-27.655z"/>
        </svg></span>
</a>


