<?
/** @var td_Connection $this */
?>
<div class="td-connect-screen">

	<h1><?php echo __( 'There seems to be a problem' ) ?></h1>
	<p>
		<?php echo __( "We can't seem to connect to your ThriveThemes.com account. Usually this is because of some kind of restrictions with your hosting company.", 'thrive-dash' ) ?>
	</p>
	<p>
        <?php echo sprintf( __( "Not to worry, %s to let us know about the issue and we'll quickly solve this problem for you", 'thrive-dash' ), '<a target="_blank" href="https://thrivethemes.com/support/">' . __( "click here", 'thrive-dash' ) . '</a>' ); ?>
    </p>

	<a class="td-retry" href="<?php echo TD_TTW_Update_Manager::get_instance()->get_admin_url(); ?>">
		<?php echo __( 'Try again', 'thrive-dash' ) ?>
	</a>

</div>

<div id="td-notification-box" class="td-error td-show">
	<h3><?php echo __( 'Ooops!', 'thrive-dash' ) ?></h3>
	<p><?php echo __( 'Something went wrong, can’t connect to account.', 'thrive-dash' ) ?></p>
</div>
