<div class="modal-content">
	<h3><?php echo __( 'Convert this site to Client Mode', Thrive_Product_Manager::T ) ?></h3>
	<p>
		<?php echo __( 'If you convert this website to "Client Mode", then the user of this website will no longer be able to access products from your ThriveThemes.com account.', Thrive_Product_Manager::T ) ?>
	</p>
	<p>
		<?php echo __( "This can be useful if you're handing over websites to clients and you want to prevent them from accessing products that you've purchased.", Thrive_Product_Manager::T ) ?>
	</p>
	<p>
		<?php echo __( 'You can add new products at any point in the future by reconnecting your ThriveThemes.com account in the Product Manager.', Thrive_Product_Manager::T ) ?>
	</p>
	<div class="modal-footer">
		<button class="tpm-button-gray tpm-modal-cancel">
			<?php echo __( 'Cancel', Thrive_Product_Manager::T ) ?>
		</button>
		<button class="tpm-button-green tpm-modal-submit">
			<?php echo __( 'Convert to Client Mode', Thrive_Product_Manager::T ) ?>
		</button>
	</div>
	<span class="close"></span>
</div>
