<div class="fr-jump-box fr-link-box" style="display:none">
	<div class="fr-checkbox-line fr-link-atts">
		<span class="fr-checkbox"><input name="jump-animation" class="fr-jump-attr" data-checked="smooth-anim" type="checkbox" id="fr-jump-smooth-<#= editor_id#>" tabIndex="' + ( ++ tab_idx ) + ' checked"><span><svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="10" height="10" viewBox="0 0 32 32"><path d="M27 4l-15 15-7-7-5 5 12 12 20-20z" fill="#FFF"></path></svg></span></span><label for="fr-jump-smooth-<#= editor_id#>"><?php echo __( 'Smooth Animation', 'thrive-cb' ) ?></label>
	</div>
	<div class="fr-jump-target"><span class="fr-jump-target-label"><?php echo __( 'Target', 'thrive-cb' ) ?> </span> <a id="fr-jump-target-<#= editor_id#>" class="fr-jump-target-elem click" data-cmd="scrollTo"></a></div>
	<div class="tcb-no-target mb-10 mt-5">
		<span class="info-text"><?php echo __( 'The target element was removed from the page. Please modify the target.', 'thrive-cb' ) ?></span>

	</div>
	<div class="fr-action-buttons row between-xs reverse">
		<button class="fr-command fr-submit" role="button" data-cmd="jumpInsert" href="#" tabIndex="' + ( ++ tab_idx ) + '" type="button"><?php echo __( 'Select Target', 'thrive-cb' ) ?></button>
		<button class="fr-command fr-danger fr-remove fr-hidden" role="button" data-cmd="jumpRemove" href="#" tabIndex="' + ( ++ tab_idx ) + '" type="button"><?php echo __( 'Delete Target', 'thrive-cb' ) ?></button>
	</div>
</div>
