<div class="tvd-row">
	<div class="tvd-col tvd-s12 tvd-m12 tvd-l12">
		<h3 class="tvd-title tvd-left">
			<?php echo __( 'Notifications', 'thrive-dash' ) ?>
			<a data-source="qCY1Gq9PZv4" class="tvd-open-video">
				<span class="tvd-icon-play"></span>
			</a>
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		</h3>
		<a href="javascript:void(0)" id="" class="tvd-left tvd-btn tvd-btn-blue tvd-waves-effect tvd-waves-light tvd-nm-create-notification">
			<?php echo __( 'Add New', 'thrive-dash' ) ?>
		</a>
	</div>
</div>

<div id="tvd-nm-notifications-list"></div>
