<div class="tvd-modal-content">
	<h3 class="tvd-modal-title"></h3>
	<p><?php echo __( 'Exporting process has started... please wait...', Thrive_Quiz_Builder::T ) ?></p>
	<div id="tqb-export-console"></div>
</div>
<div class="tvd-modal-footer">
	<div class="tvd-row">
		<div class="tvd-col tvd-s6">
			<a href="javascript:void(0)" class="tvd-btn-flat tvd-btn-flat-secondary tvd-btn-flat-dark tvd-waves-effect tqb-cancel-export">
				<?php echo __( 'Cancel export process', Thrive_Quiz_Builder::T ) ?>
			</a>
		</div>
		<div class="tvd-col tvd-s6">
			<a style="display: none" href="javascript:void(0)" id="tqb-download-export" class="tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-purple tvd-right">
				<?php echo __( 'Download export', Thrive_Quiz_Builder::T ) ?>
			</a>
		</div>
	</div>
</div>
