<div class="tvd-modal-content">
	<h3 class="tvd-modal-title">
		<?php echo __( 'Import Quiz', Thrive_Quiz_Builder::T ) ?>
	</h3>
	<p><?php echo __( 'Import a previously exported quiz below', Thrive_Quiz_Builder::T ) ?></p>
	<div id="tqb-drop-area">
		<div class="tqb-state tqb-initial-state">
			<span class="tqb-drop-blue"><?php tqb_get_svg_icon( 'paperclip_light' ); ?><?php echo __( 'Add file', Thrive_Quiz_Builder::T ) ?></span>
			<span class="tqb-drop-gray"><?php echo __( 'or drop files here', Thrive_Quiz_Builder::T ) ?></span>
			<div> Quiz_id.zip</div>
			<input id="tqb-file-input" type="file" name="name" style="display: none;"/>
		</div>
		<div class="tqb-state tqb-ready-state"></div>
	</div>
</div>
<div class="tvd-modal-footer">
	<div class="tvd-row">
		<div class="tvd-col tvd-s6">
			<a href="javascript:void(0)" class="tvd-btn-flat tvd-btn-flat-secondary tvd-btn-flat-dark tvd-waves-effect tvd-modal-close">
				<?php echo __( 'Close', Thrive_Quiz_Builder::T ) ?>
			</a>
		</div>
		<div class="tvd-col tvd-s12 tvd-m6">
			<a href="javascript:void(0)"
			   class="tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-purple tvd-right tqb-modal-submit">
				<?php echo __( 'Import Quiz', Thrive_Quiz_Builder::T ) ?>
			</a>
		</div>
	</div>
</div>
