<div class="tvd-modal-content tqb-modal-variation">
	<h3 class="tvd-modal-title">
		<?php echo __( 'Quiz settings', Thrive_Quiz_Builder::T ); ?>
	</h3>

	<div class="tqb-quiz-settings-right-wrong">
		<div class="tqb-highlight-settings"></div>
		<div class="tqb-feedback-settings"></div>
		<div class="tqb-preview-settings"></div>
	</div>
	<div class="tqb-quiz-settings">
		<div class="tqb-feedback-settings"></div>
		<div class="tqb-preview-settings"></div>
	</div>

	<div class="tqb-quiz-settings-personality">
		<div class="add-category-holder"></div>
		<div id="tqb-multiple-input-wrapper"></div>
		<div class="tqb-feedback-settings"></div>
		<div class="tqb-preview-settings"></div>
	</div>
</div>
<div class="tvd-modal-footer">
	<div class="tvd-row">
		<div class="tvd-col tvd-s12 tvd-m6">
			<a href="javascript:void(0)"
			   class="tvd-btn-flat tvd-btn-flat-secondary tvd-btn-flat-dark tvd-waves-effect tvd-modal-close">
				<?php echo __( 'Cancel', Thrive_Quiz_Builder::T ) ?>
			</a>
		</div>
		<div class="tvd-col tvd-s12 tvd-m6">
			<a href="javascript:void(0)"
			   class="tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-purple tvd-right tqb-modal-submit">
				<?php echo __( 'Save', Thrive_Quiz_Builder::T ) ?>
			</a>
		</div>
	</div>
</div>
