<div class="state-section">
	<a href="javascript:void(0)" class="click state-switch trigger" data-fn="toggle_dropdown">
		<span class="label"><?php echo __( 'State:', 'thrive-cb' ); ?></span>
		<strong class="state-action">
			<span class="current-state"><?php echo __( 'Normal', 'thrive-cb' ); ?></span>
			<span class="chevron"><?php tcb_icon( 'chevron-down-regular' ); ?></span>
		</strong>
	</a>
	<button class="click reset-state-button tcb-hidden" data-fn="toggleResetState" data-tooltip="Reset State">
		<span><?php tcb_icon( 'reset' ); ?></span>
	</button>
	<ul class="drop-content tcb-hidden">
		<li class="selected" data-state="default">
			<a href="javascript:void(0)" class="click" data-state="default" data-fn="done"><?php echo __( 'Normal', 'thrive-cb' ) ?></a>
		</li>
		<li data-state="hover">
			<a href="javascript:void(0)" class="click" data-state="hover" data-fn="state_select"><?php echo __( 'Hover', 'thrive-cb' ) ?></a>
		</li>
		<li data-state="active" class="tcb-hidden">
			<a href="javascript:void(0)" class="click" data-state="active" data-fn="state_select"><?php echo __( 'Active', 'thrive-cb' ) ?></a>
		</li>
		<li data-state="expanded" class="tcb-hidden">
			<a href="javascript:void(0)" class="click" data-state="expanded" data-fn="state_select"><?php echo __( 'Expanded', 'thrive-cb' ) ?></a>
		</li>
	</ul>
</div>