<?php
$unavailable_tooltip_text = __( 'This feature is only available for Thrive Leads, Thrive Ovation, Thrive Headline Optimizer, Thrive Quiz Builder', 'thrive-dash' );
?>
<div class="tvd-row">
	<div class="tvd-col tvd-s12 tvd-m12 tvd-l12">
		<h3 class="tvd-title tvd-left">
			<?php echo __( 'Notifications', 'thrive-dash' ) ?>
			<a class="tvd-open-video" data-source="qCY1Gq9PZv4">
				<span class="tvd-icon-play"></span>
			</a>
		</h3>
		<a style="margin-left: 30px;" href="javascript:void(0)" data-position="top" data-tooltip="<?php echo $unavailable_tooltip_text; ?>" class="tvd-disabled tvd-left tvd-btn tvd-btn-blue tvd-waves-effect tvd-waves-light tvd-tooltipped">
			<?php echo __( 'Add New', 'thrive-dash' ) ?>
		</a>
	</div>
</div>
<div class="tvd-card tvd-card-new tvd-valign-wrapper tvd-tooltipped" data-position="top" data-tooltip="<?php echo $unavailable_tooltip_text; ?>">
	<div class="tvd-card-content tvd-valign tvd-center-align">
		<i class="tvd-icon-plus tvd-icon-rounded tvd-icon-medium"></i>
		<h4><?php echo __( 'Add New Notification', 'thrive-dash' ) ?></h4>
	</div>
</div>
