<div class="row">
	<div class="col-xs-12">
		<div class="tve-control tve-shape-svg-height"></div>
	</div>
	<div class="col-xs-12 grey-text mt-10">
		<div class="tve-control tve-shape-svg-change-dir"></div>
	</div>
	<div class="col-xs-12 grey-text mt-10">
		<div class="tve-control tve-shape-svg-invert"></div>
	</div>
	<div class="col-xs-12 grey-text mt-10">
		<div class="tve-control tve-shape-svg-bring-front"></div>
	</div>
	<div class="col-xs-12 mt-10">
		<div class="tve-control tve-shape-svg-color"></div>
	</div>
</div>