<div id="tqb-completed-tests" style="display: none;">
	<h4 title="<?php echo __( 'Click to expand', 'thrive-quiz-builder' ) ?>" class="tvd-pointer tqb-toggle-display collapsed"
	    data-target="#tqb-completed-test-list">
		<?php echo __( 'Completed Tests', 'thrive-quiz-builder' ) ?> <span id="tqb-completed-tests-count">(0)</span>
	</h4>

	<ul class="tvd-collection tvd-with-header" id="tqb-completed-test-list" style="display: none;">
		<li class="tvd-collection-header">
			<div class="tvd-row">
				<div class="tvd-col tvd-s2">
					<div class="tvd-truncate-on-small">
						<h5 class="tvd-truncate-on-small-el">
							<?php echo __( 'Test Name', 'thrive-quiz-builder' ) ?>
						</h5>
					</div>
				</div>
				<div class="tvd-col tvd-s2">
					<h5>
						&nbsp;
					</h5>
				</div>
				<div class="tvd-col tvd-s2">
					<div class="tvd-truncate-on-small">
						<h5 class="tvd-truncate-on-small-el">
							<?php echo __( 'Test Description', 'thrive-quiz-builder' ) ?>
						</h5>
					</div>
				</div>
				<div class="tvd-col tvd-s2">
					<div class="tvd-truncate-on-small">
						<h5 class="tvd-truncate-on-small-el">
							<?php echo __( 'Start Date', 'thrive-quiz-builder' ) ?>
						</h5>
					</div>
				</div>
				<div class="tvd-col tvd-s2">
					<div class="tvd-truncate-on-small">
						<h5 class="tvd-truncate-on-small-el">
							<?php echo __( 'End Date', 'thrive-quiz-builder' ) ?>
						</h5>
					</div>
				</div>
				<div class="tvd-col tvd-s2">&nbsp;</div>
			</div>
		</li>
	</ul>
</div>
