<div class="">
	<#if(!this.selection||!this.selection.title){#>
	<button class="click tve-button white mt-5 mb-5 border w-100" data-fn="open_media">
		<#=this.labels.choose#>
	</button>
	<#}#>
	<#if(this.selection&&this.selection.title){#>
	<div class="video-picker control-grid mb-5">
		<span class="tcb-truncate t-80"><#=this.selection.title#></span>
		<a href="javascript:void(0)" class="image-edit click" data-fn="open_media" data-tooltip="<?php echo __( 'Change Element', 'thrive-cb' ) ?>">
			<?php tcb_icon( 'exchange-regular' ) ?>
		</a>
	</div>
	<#}#>
</div>