<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-apprentice
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden!
}
?>
<div class="tvd-modal-content">
	<h3 class="tvd-modal-title"><?php echo __( 'Hi there, Professor', 'thrive-apprentice' ); ?></h3>
	<p><?php echo __( 'Since this is your first time using Thrive Apprentice, we will provide you with demo content in order to see which elements of the template are affected by the changes you make.', 'thrive-apprentice' ); ?></p>
	<p><?php echo __( 'Don\'t worry! You\'ll still be able to change the preview to see your content by switching between DEMO and LIVE tabs.', 'thrive-apprentice' ); ?></p>
	<div class="tvd-center mt-30">
		<button type="button" class="tva-modal-btn tva-modal-btn-green tvd-modal-close"><?php echo __( 'Ok', 'thrive-apprentice' ); ?></button>
	</div>
</div>
