<div class="tva-context-title"><#=this.contextTitle#></div>
<div class="tva-context-option">
	<select class="change select2" data-fn="labelDisplayChanged">
		<option value="show"
		<#= this.model.get('opt') === 'show' ? ' selected' : ''#>><?php esc_html_e( 'Switch label to', 'thrive-apprentice' ); ?></option>
		<option value="hide"
		<#= this.model.get('opt') === 'hide' ? ' selected' : ''#>><?php esc_html_e( 'Hide label', 'thrive-apprentice' ); ?></option>
		<option value="nochange"
			<#= this.model.get('opt') === 'nochange' ? ' selected' : ''#>><?php esc_html_e( 'No change', 'thrive-apprentice' ); ?></option>
	</select>
</div>
<# if ( this.model.get('opt') === 'show' ) { #>
<div class="tva-label-edit tva-flex-mid">
	<div class="tva-label-color">
		<span class="tva-label-thumb click" data-fn="spectrum" data-field="color" style="--thumb-color: <#=this.model.get('color') #>"></span>
		<input type="text" value="<#= this.model.get('color') #>" class="tva-colorpicker" data-field="color"/>
	</div>
	<div class="tva-label-name tva-flex tva-align-center click ml-35" data-fn="editing">
		<# if ( ! this.model.get('editing') ) { #>
		<span title="<#= this.model.get('title') #>" class="tva-topic-title tvd-truncate"><#- this.model.get('title') #></span>
		<# } else { #>
		<input id="tva-edit-<#=this.model.cid#>" type="text" value="<#- this.model.get('title') #>" class="tva-title-events">
		<# } #>
	</div>
</div>
<# } #>
