<div class="settings">
	<div class="label"><?php echo __( 'Message', 'thrive-cb' ); ?></div>

	<div class="tve-email-modal-settings mt-10 click" data-fn="openSettings">
		<div class="input">
			<a href="javascript:void(0)" class="click center style-input">
				<span class="mr-5">
							<?php tcb_icon( 'pen-nib-light' ); ?>
						</span>
				<span class="tcb-truncate t-80"><?php echo __( 'Compose Email', 'thrive-cb' ); ?></span>
			</a>
		</div>
	</div>
</div>
