<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-dashboard
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden!
}
?>
<div class="tvd-rule-delete">
	<div><?php echo esc_html__( 'Are you sure you want  to delete this rule? This cannot be undone.', TVE_DASH_TRANSLATE_DOMAIN ); ?></div>
	<div>
		<a href="javascript:void(0);" class="click" data-fn="cancel"><?php echo esc_html__( 'No, cancel', TVE_DASH_TRANSLATE_DOMAIN ); ?></a>
		<a href="javascript:void(0);" class="click" data-fn="confirm"><?php echo esc_html__( 'Yes, delete', TVE_DASH_TRANSLATE_DOMAIN ); ?></a>
	</div>
</div>
