<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-dashboard
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}
?>

<?php include_once TVE_DASH_PATH . '/css/font/dashboard-icons.svg' ?>
<div id="tvd-tss-wrap-all">
	<div id="tvd-tss-header"></div>
	<div class="tvd-tss-breadcrumbs-wrapper" id="tvd-tss-breadcrumbs-wrapper"></div>
	<div id="tvd-tss-wrapper">
		<div class="tvd-tss-menu"></div>
		<div class="tvd-tss-content"></div>
	</div>
</div>
