<div class="ult-link-actions">
	<div class="fr-input-line"><strong><?php echo __( 'Thrive Ultimatum Action', 'thrive-ult' ) ?></strong></div>
	<# _.each( actions, function( data, key ) {#>
	<div class="fr-checkbox-line">
		<span class="fr-checkbox">
			<input name="evt_action[]" data-key="<#=key#>" class="fr-extra-action" type="checkbox" id="ult-action-<#=key#>-<#=current_id#>" dir="auto">
			<span>
				<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="10" height="10" viewBox="0 0 32 32"><path d="M27 4l-15 15-7-7-5 5 12 12 20-20z"
																													   fill="#FFF"></path></svg>
			</span>
		</span>
		<label for="ult-action-<#=key#>-<#=current_id#>">
			<#= data.labels #>
		</label>
		<# if ( data.options ) { #>
		<div class="ult-action-opts-<#=key#> ult-action-config fr-input-line" style="display: none">
			<label class="fr-label"><?php echo __( 'State', 'thrive-ult' ) ?></label>
			<select class="fr-select" name="s">
				<# _.each( data.options, function ( state ) { #>
				<option value="<#=state.id#>">
					<#=state.title#>
				</option>
				<#} ); #>
			</select>
			<# if ( data.animations ) { #>
			<label class="fr-label"><?php echo __( 'Animation', 'thrive-ult' ) ?></label>
			<select class="fr-select" name="a">
				<# _.each( data.animations, function ( name, key ) { #>
				<option value="<#=key#>">
					<#=name#>
				</option>
				<#} ); #>
			</select>
			<# } #>
		</div>
		<# } #>
	</div>
	<#}); #>
</div>
