<div class="row">
	<div class="col-xs-6">
		<label class="tcb-radio">
			<input type="radio" name="dynamic-link-type" class="change link-type" value="static" data-fn="linkType" checked>
			<span><?php echo __( 'Static', 'thrive-theme' ); ?></span>
		</label>
	</div>
	<div class="col-xs-6">
		<label class="tcb-radio">
			<input type="radio" name="dynamic-link-type" class="change link-type" value="dynamic" data-fn="linkType">
			<span><?php echo __( 'Dynamic', 'thrive-theme' ); ?></span>
		</label>
	</div>

	<div class="col-xs-12 margin-top-5">
		<select class="dynamic-link-select change" data-fn="dynamicLink" style="display: none;">
			<option value="#" selected><?php echo __( 'none', 'thrive-theme' ); ?></option>
			<option value="thrive_the_permalink"><?php echo __( 'Post link', 'thrive-theme' ); ?></option>
			<option value="thrive_archive_link"><?php echo __( 'Post Archive', 'thrive-theme' ); ?></option>
			<option value="thrive_author_link"><?php echo __( 'Author Archive', 'thrive-theme' ); ?></option>
			<option value="thrive_date_link"><?php echo __( 'Date link', 'thrive-theme' ); ?></option>
			<option value="thrive_comments_link"><?php echo __( 'Comments link', 'thrive-theme' ); ?></option>
		</select>
	</div>
</div>
