<div class="ttb-dynamic-toc mb-10">
	<div class="info-text orange tcb-text-center pt-5 pb-5 m-0">
		<p class="m-0"><strong><?php echo esc_html__( 'This element is dynamic', 'thrive-theme' ); ?></strong></p>
		<p class="mb-0 mt-5">
			<?php echo esc_html__( 'You’ve added the table of contents element inside a template.  This means the list of items will change depending on the content.', 'thrive-theme' ); ?>
			<a style="display: inline" href="https://thrivethemes.com/tkb_item/using-table-contents-element-theme-template/"
			   target="_blank"><?php echo esc_html__( 'Learn more', 'thrive-theme' ); ?></a>
		</p>
	</div>
</div>
