<div class="control-grid full-width pb-0">
	<span>
	<?php echo __( 'You can optionally choose to integrate with an email delivery service such as PostMark or SendGrid for increased deliverability. Otherwise emails will be sent directly from your server.', 'thrive-cb' ); ?>
	</span>
	<a class="blue-text" href="//thrivethemes.com/tkb_item/integrating-with-an-email-delivery-service-when-setting-up-an-email-connection/" target="_blank"><?php echo __( 'Learn more about this.', 'thrive-cb' ) ?></a>
</div>