<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-apprentice
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden!
}
?>
<div class="tva-modal-step" data-step="0">
	<div class="tvd-modal-content">
		<div class="tva-content-sets-container"></div>
	</div>
</div>
<div class="tva-modal-step" data-step="1">
	<div class="tvd-modal-content">
		<div class="tva-content-sets-form-container"></div>
	</div>
</div>
