<div class="control-grid full-width pb-0">
	<p class="mb-10 mt-0" style="font-weight: 500">
		<?php echo __( 'Custom fields unavailable', 'thrive-cb' ) ?>
	</p>
	<p class="m-0">
		<?php echo __( 'Custom fields are unavailable either because there is no autoresponder connected or the current one does not support it.', 'thrive-cb' ); ?>
	</p>
	<a class="blue-text mt-10" href="//thrivethemes.com/tkb_item/how-to-solve-the-custom-fields-unavailable-error/" target="_blank">
		<?php echo __( 'Help me solve this issue', 'thrive-cb' ) ?>
	</a>
</div>