<div class="control-grid">
	<div class="label flex-mid pr-15">
		<div class="corner-boxes">
			<div class="tve-corner tve-border-side click top-left" data-fn="corner" data-value="top-left"></div>
			<div class="tve-corner tve-border-side click top-right" data-fn="corner" data-value="top-right"></div>
			<div class="tve-corner tve-border-side click bottom-right" data-fn="corner" data-value="bottom-right"></div>
			<div class="tve-corner tve-border-side click bottom-left" data-fn="corner" data-value="bottom-left"></div>
			<div class="tve-corner tve-border-side click default center" data-fn="corner" data-value=""></div>
		</div>
	</div>
	<div class="corner-radius input">
		<div class="tve-corner-value no-space input-small"></div>
	</div>
</div>
