<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-visual-editor
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden!
}
?>
<div class="palettes-inherit-color-control"></div>
<div class="control-grid palettes-colorpicker-control">
	<div class="label">
		<?php echo __( 'Colors', 'thrive-cb' ); ?>
	</div>
	<div class="input">
		<div class="tcb-palettes-variables control-grid flex-end p-0"></div>
	</div>
</div>
