<div class="control-grid switch mb-5<#=this.getExtraClass()#>">
	<div class="fill">
		<span class="switch-label"><#= TVE.icon(this.model.config.icon ? this.model.config.icon : '' ) #> <#= this.model.config.label #></span>
		<# if ( this.model.config.info ) { #>
		<span class="click tve-switch-info" data-fn="openTooltip" <#= this.model.config.icontooltip ? 'data-tooltip="' + this.model.config.icontooltip + '"' : ''#> <#= this.model.config.iconside ? 'data-side="' + this.model.config.iconside + '"' : ''#>><?php tcb_icon( 'info-circle-solid' ); ?></span>
		<# } #>
		<# if ( this.model.config.instructions ) { #>
		<span class="click" data-type="<#=this.model.config.instructions.type#>" data-url="<#=this.model.config.instructions.url#>" data-link="<#=this.model.config.instructions.link#>" data-fn="openInstructionsLightbox"><#= TVE.icon( this.model.config.instructions.type + "-instructions" ) #></span>
		<# } #>
	</div>
	<div class="tcb-switch tcb-text-right">
		<label>
			<input class="tve-checkbox change" data-fn="check" <#= this.model.config.name? 'data-name="' + this.model.config.name + '"':'' #> type="checkbox"<#=this.model.config.checked ? ' checked' : '' #>>
			<span class="tcb-lever"></span>
		</label>
	</div>
</div>
