<div class="tth-dropdown-container q-s-relation"></div>

<span><?php echo __( 'results that belong to ', 'thrive-cb' ); ?></span>

<div class="tth-dropdown-container q-s-operator"></div>

<span><?php echo __( ' of these ', 'thrive-cb' ); ?></span>

<span class="taxonomy-label"><#= this.model.getTaxonomyLabel() #></span>

<div class="tth-dropdown-container q-s-terms"></div>

<button class="tth-delete-block click" data-fn="ruleRemove"></button>
