<div class="tvd-modal-content">
	<h3 class="tvd-modal-title"><?php echo __( "Copy campaign - ", 'thrive-ult' ) ?>
		<#= model.get('post_title') #>
	</h3>
	<div class="tvd-v-spacer"></div>
	<div class="tvu-new-campaign-templates control-grid"></div>
	<div id="tvu-campaign-type-options"></div>
</div>
<div class="tvd-modal-footer control-grid">
	<div>
		<a href="javascript:void(0)"
		   class="tvd-btn-flat tvd-btn-flat-secondary tvd-btn-flat-dark tvd-waves-effect tvd-modal-close">
			<?php echo __( "Cancel", 'thrive-ult' ) ?>
		</a>
	</div>
	<div>
		<a href="javascript:void(0)"
		   class="tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-green tvd-right tvd-modal-submit">
			<?php echo __( "Copy", 'thrive-ult' ) ?>
		</a>
	</div>
</div>

