<div class="tvu-modal-step">
	<div class="tvd-modal-content">
		<h3 class="tvd-modal-title"><?php echo __( 'Create campaign from scratch or customize a template', 'thrive-ult' ) ?></h3>

		<p><?php echo __( 'Choose a template', 'thrive-ult' ) ?></p>

		<div class="tvu-new-campaign-templates control-grid"></div>
		<div class="tvu-new-campaign-description"></div>
	</div>
	<div class="tvd-modal-footer control-grid">
		<div>
			<a href="javascript:void(0)"
			   class="tvd-btn-flat tvd-btn-flat-secondary tvd-btn-flat-dark tvd-waves-effect tvd-modal-close">
				<?php echo __( 'Cancel', 'thrive-ult' ) ?>
			</a>
		</div>
		<div>
			<a href="javascript:void(0)"
			   class="tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-green tvd-right tvu-modal-next-step">
				<?php echo __( 'Continue', 'thrive-ult' ) ?>
			</a>
		</div>
	</div>
</div>

<div class="tvu-modal-step">
	<div class="tvd-modal-content">
		<h3 class="tvd-modal-title"><?php echo __( 'Name your campaign', 'thrive-ult' ) ?></h3>

		<p><?php echo __( 'Enter a name for your campaign. This is for internal use only - your website visitors will not see this name.', 'thrive-ult' ) ?></p>

		<div class="tvd-input-field">
			<input id="tvu-new-campaign-name" type="text" name="new-campaign-name" data-bind="post_title">
			<label for="tvu-new-campaign-name"
				   data-error="<?php echo __( 'Campaign name is required', 'thrive-ult' ) ?>"><?php echo __( 'Campaign name', 'thrive-ult' ) ?></label>
		</div>
	</div>
	<div class="tvd-modal-footer control-grid">
		<a href="javascript:void(0)"
		   class="tvd-btn-flat tvd-btn-flat-secondary tvd-btn-flat-dark tvd-waves-effect tvu-modal-prev-step">
			<?php echo __( 'Back', 'thrive-ult' ) ?>
		</a>
		<a href="javascript:void(0)"
		   class="tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-green tvd-right tvd-modal-submit">
			<?php echo __( 'Continue', 'thrive-ult' ) ?>
		</a>
	</div>
</div>
