<div class="tvd-modal-content top-ribbon-modal">
	<h3 class="tvd-modal-title"><?php echo __( 'Top Ribbon settings', 'thrive-ult' ) ?></h3>

	<div class="control-grid mt-25" id="tu-top-ribbon-position">
		<div><?php echo __( 'Choose how the top ribbon is displayed', 'thrive-ult' ); ?></div>
		<div class="tu-display-switch mt-15">
			<div data-value="over_content" class="tu-display-option"><?php echo __( 'Over content', 'thrive-ult' ); ?></div>
			<div data-value="push_content" class="tu-display-option active"><?php echo __( 'Push content', 'thrive-ult' ); ?></div>
		</div>
	</div>

</div>
<div class="tvd-modal-footer control-grid">
	<div>
		<a href="javascript:void(0)"
		   class="tvd-btn-flat tvd-btn-flat-secondary tvd-btn-flat-dark tvd-waves-effect tvd-modal-close">
			<?php echo __( 'Cancel', 'thrive-ult' ) ?>
		</a>
	</div>
	<div>
		<a href="javascript:void(0)"
		   class="tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-green tvd-right tvd-modal-submit">
			<?php echo __( 'Save', 'thrive-ult' ) ?>
		</a>
	</div>
</div>
