<svg class="tcb-icon tcb-icon-central-style-panel tooltip-image-align">
	<use xlink:href="#icon-central-style-panel"></use>
</svg>
<p class="tooltip-header tcb-tooltip text-green tooltip-text-align"><?php echo __( 'Quickly Style the General Look of this page.', 'thrive-cb' ); ?></p>
<p class="tooltip-text-typography"><?php echo __( 'With this style editor you can reuse elements and styles, control colors and typography 
												 or inherit them from your active theme.', 'thrive-cb' ); ?></p>