<div class="thrv_wrapper tcb-group-editing-item tcb-filter-option tcb-filter-button"
	 data-id="<#= id #>"
	 data-name="<#= name #>"
	 data-selector="">
	<div class="thrive-colors-palette-config" style="display: none !important">__CONFIG_colors_palette__{"active_palette":0,"config":{"colors":{"62516":{"name":"Main Accent","parent":-1}},"gradients":[]},"palettes":[{"name":"Default Palette","value":{"colors":{"62516":{"val":"var(--tcb-skin-color-0)"}},"gradients":[]}}]}__CONFIG_colors_palette__</div>
	<a class="tcb-button-link tcb-plain-text">
		<span class="tcb-button-texts">
			<span class="tcb-button-text tcb_filter_name"> <#= name #> </span>
		</span>
	</a>
</div>