<div class="tge-modal-step">
	<div class="tvd-modal-content tge-select-question-type">
		<h3 class="tvd-modal-title tvd-white-text"><?php echo __( 'Select question type', 'thrive-graph-editor' ) ?></h3>
		<p class="tqb-modal-subtitle"><?php echo __( 'Select question type:', 'thrive-graph-editor' ) ?></p>
		<div id="tge-question-types" class="tvd-row tvd-collapse"></div>
	</div>
	<div class="tvd-modal-footer">
		<div class="tvd-row">
			<div class="tvd-col tvd-s12 tvd-m6">
				<a href="javascript:void(0)"
				   class="tvd-btn-flat tvd-btn-flat-secondary tvd-btn-flat-dark tvd-waves-effect tvd-modal-close">
					<?php echo __( 'Cancel', 'thrive-graph-editor' ) ?>
				</a>
			</div>
			<div class="tvd-col tvd-s12 tvd-m6">
				<a href="javascript:void(0)"
				   class="tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-purple tvd-right tge-modal-next-step">
					<?php echo __( 'Continue', 'thrive-graph-editor' ) ?>
				</a>
			</div>
		</div>
	</div>
</div>

<div class="tge-modal-step">
	<div class="tvd-modal-content">
		<h3 class="tvd-modal-title tvd-white-text"><?php echo __( 'Add Question', 'thrive-graph-editor' ) ?></h3>
		<div id="tge-question-form"></div>
	</div>
	<div class="tvd-modal-footer">
		<div class="tvd-row">
			<div class="tvd-col tvd-s12 tvd-m6">
				<a href="javascript:void(0)"
				   class="tvd-btn-flat tvd-btn-flat-secondary tvd-btn-flat-dark tvd-waves-effect tge-modal-prev-step">
					<?php echo __( 'Back', 'thrive-graph-editor' ) ?>
				</a>
			</div>
			<div class="tvd-col tvd-s12 tvd-m6">
				<a href="javascript:void(0)"
				   class="tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-purple tvd-right tvd-modal-submit">
					<?php echo __( 'Save', 'thrive-graph-editor' ) ?>
				</a>
			</div>
		</div>
	</div>
</div>
