<div class="tvd-modal-content">
	<h3 class="tvd-modal-title tvd-white-text"><?php echo __( 'Progress Bar Settings', Thrive_Graph_Editor::T ) ?></h3>

	<div class="tqb-progress-big-container">
		<div class="tqb-settings-container">
			<div id="tge-progress-switcher"></div>
			<p><?php echo __( 'Displaying a progress highlights how many more questions are remaining and can often increase the engagement of your quiz.', Thrive_Graph_Editor::T ) ?></p>
		</div>
		<div class="tqb-progress-options">

			<div class="tqb-progress-bar-options"></div>

			<div class="tqb-progress-bar"></div>

		</div>
	</div>
</div>
<div class="tvd-modal-footer">
	<a href="javascript:void(0)" class="tqb-progress-close tvd-modal-close">
		<?php echo __( 'Cancel', Thrive_Quiz_Builder::T ) ?>
	</a>
	<a href="javascript:void(0)"
	   class="tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-purple tvd-right tvd-modal-submit">
		<?php echo __( 'Save', Thrive_Graph_Editor::T ) ?>
	</a>
</div>
