<div class="ttd-performance-main">
	<a class="ttd-performance-card" href="admin.php?page=tve_lightspeed" target="_blank">
		<span class="ttd-p-card-icon">
			<#= TTD.utils.icon( 'performance-lightspeed' ) #>
		</span>
		<span class="ttd-p-card-title">
			<?php echo __( 'Project Lightspeed', 'thrive-theme' ); ?>
		</span>
		<span class="ttd-p-card-content">
			<?php echo __( 'Optimize assets like CSS and Javascript for a blazing fast website', 'thrive-theme' ); ?>
		</span>
	</a>

	<a class="ttd-performance-card" href="#performance/image">
		<span class="ttd-p-card-icon">
			<#= TTD.utils.icon( 'performance-image' ) #>
		</span>
		<span class="ttd-p-card-title">
			<?php echo __( 'Image Optimization and Delivery', 'thrive-theme' ); ?>
		</span>
		<span class="ttd-p-card-content">
			<?php echo __( 'Serve your images at the right dimensions, compression and from a CDN (servers that work together to ensure fast delivery). Your images should be fully optimized for fast performance.', 'thrive-theme' ); ?>
		</span>
	</a>

	<a class="ttd-performance-card" href="#performance/cache">
		<span class="ttd-p-card-icon">
			<#= TTD.utils.icon( 'performance-cache' ) #>
		</span>
		<span class="ttd-p-card-title">
			<?php echo __( 'Minification and Caching', 'thrive-theme' ); ?>
		</span>
		<span class="ttd-p-card-content">
			<?php echo __( 'Reduce the size of your site by compressing scripts and styles. Create static copies of your pages to bypass loading WordPress for every hit to your site resulting in notably faster load speed.', 'thrive-theme' ); ?>
		</span>
	</a>

	<a class="ttd-performance-card" href="#performance/amp">
		<span class="ttd-p-card-icon">
			<#= TTD.utils.icon( 'performance-amp' ) #>
		</span>
		<span class="ttd-p-card-title">
			<?php echo __( 'Accelerated Mobile Pages', 'thrive-theme' ); ?>
		</span>
		<span class="ttd-p-card-content">
			<?php echo __( 'Activate Accelerated Mobile Pages (AMP) to create better, faster experiences for your visitors on the mobile web.', 'thrive-theme' ); ?>
		</span>
	</a>
</div>
