<div class="control-grid full-width pb-0">
	<h4>
		<?php echo __( 'Reserved name variable', 'thrive-cb' ) ?>
	</h4>
	<br>
	<span>
		<?php echo __( 'The variable name is reserved by WordPress and may cause unexpected 404 errors.', 'thrive-cb' ) ?>
	</span>
	<br><span>
		<?php echo __( 'You should consider renaming the fields to something more unique.', 'thrive-cb' ) ?>
	</span>
	<br>
	<a class="blue-text" href="//codex.wordpress.org/Function_Reference/register_taxonomy#Reserved_Terms" target="_blank">
		<?php echo __( 'See full list of reserved names here', 'thrive-cb' ) ?>
	</a>
</div>