<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-dashboard
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}
?>

<div class="tvd-tss-field-data">
	<label for="tvd-tss-field-name"><?php echo __( 'Field Name', 'thrive-dash' ) ?> *</label>
	<div class="tvd-input-field">
		<input id="tvd-tss-field-name" autocomplete="phone" class="input-change <#= model.get( 'default_field' )? 'tvd-disabled tvd-no-focus' : '' #>" type="text" value="<#= model.get('name') #>"
			   data-field="name"
			   placeholder="<?php echo __( 'Company Phone', 'thrive-dash' ) ?>">
		<label></label>
	</div>
</div>

<div class="tvd-tss-field-data">
	<label for="tvd-tss-field-phone"><?php echo __( 'Phone Number', 'thrive-dash' ) ?> *</label>
	<div class="tvd-input-field">
		<input id="tvd-tss-field-phone" autocomplete="phone-input" class="input-change" type="text" value="<#= model.get('data').phone ? model.get('data').phone : '' #>" data-field="data_phone" placeholder="<?php echo __( '555-555-555', 'thrive-dash' ) ?>">
		<label></label>
	</div>
</div>