<div class="tvd-input-field mr-20">
	<input id="tvu-email-link<#= key || key == 0 ? key : 0 #>" readonly="readonly" class="tvd-no-focus tvu-email-link tvu-lockdown-input mb-0 p-5" type="text"
		   value="<#= model.get('link') ? model.get('link') : '' #>">
</div>
<a class="tve-copy-to-clipboard tvu-url-to-copy tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-blue" href="javascript:void(0)">
	<span class="tvd-copy-text"><?php echo __( 'Copy', 'thrive-ult' ) ?></span>
</a>
