<div class="elem-link-redirect-logout-wrapper w-100">
	<div class="elem-link-redirect-logout-checkbox" style="display: none"></div>
	<div class="tve-static-link control-grid no-space elem-link-redirect-logout-link" style="display: none">
		<div id="tcb-redirect-link-search-control" class="fill pt-0"></div>
		<a href="javascript:void(0)" class="click tve-static-link-settings ml-5" data-fn="open_link_search_settings"><?php tcb_icon( 'settings' ); ?></a>
	</div>
</div>