<div class="control-grid">
    <h3 class="mr-30">
        <?php echo __( 'Conversion Events', TVE_Ult_Const::T ) ?>
        <?php tve_ult_video( 's3vd37mygx' ) ?>
    </h3 class>
	<div class="tvd-right">
		<a href="javascript:void(0)" id="tvu-add-conversion-event" class="tvu-add-conversion-event tvd-tooltipped tvd-btn tvd-btn-blue tvd-waves-effect tvd-waves-light tvd-right tvd-margin-right" data-tooltip="<?php echo __( 'Add new conversion event', TVE_Ult_Const::T ) ?>" data-position="left"><?php echo __( 'Add New', TVE_Ult_Const::T ) ?></a>
	</div>
</div>
<div id="tvu-conversion-events" class="tvu-conversion-events"></div>
