<div class="control-grid">
	<h3 class="mr-30">
		<?php echo __( 'Conversion Events', 'thrive-ult' ) ?>
		<?php tve_ult_video( 'z2Rki4nTFDg' ) ?>
	</h3 class>
	<div class="tvd-right">
		<a href="javascript:void(0)" id="tvu-add-conversion-event" class="tvu-add-conversion-event tvd-tooltipped tvd-btn tvd-btn-blue tvd-waves-effect tvd-waves-light tvd-right tvd-margin-right" data-tooltip="<?php echo __( 'Add new conversion event', 'thrive-ult' ) ?>" data-position="left"><?php echo __( 'Add New', 'thrive-ult' ) ?></a>
	</div>
</div>
<div id="tvu-conversion-events" class="tvu-conversion-events"></div>
