<div class="control-grid full-width pb-0">
	<p class="m-0">
		<?php echo __( 'Insert the full URL of the folder that you wish to upload the files to.', 'thrive-cb' ); ?>
	</p>
	<a class="blue-text mt-10" href="https://thrivethemes.com/tkb_item/how-to-find-the-url-of-a-folder-when-uploading-a-file-in-the-lead-generation-element/" target="_blank">
		<?php echo __( 'How to find the folder URL', 'thrive-cb' ) ?>
	</a>
</div>
