<div class="tvd-input-field mb-20">
	<div class="tge-source-col-elem">
		<div id="tge-display-url-source" class="tge-display-url-source"></div>

		<div class="tvd-input-field tqb-video-color-container">
			<div class="tqb-video-color-code-holder">
				<label for="tqb-video-overlay-color"><?php echo __( 'Player color', Thrive_Graph_Editor::T ) ?></label>
				<div class="tge-col-label">
					<input type="text" readonly class="tqb-video-color" id="tqb-video-overlay-color" value="<#= item.get( 'color' ) #>">
					<div class="tqb-video-color-code-holder">
						<input type="text" readonly class="tqb-color-code" id="tqb-video-color-overlay-code" value="<#= item.get( 'color' ) #>">
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="tvd-input-field mb-20 tge-display-settings-url8">
	<div class="tvd-input-field">
		<input type="text" id="tge-display-settings-url" class="tge-display-settings-url"  data-bind="url" value="<#= item.get('url')#>">
		<label for="tge-display-settings-url" data-error="<?php echo __( 'Invalid URL', Thrive_Graph_Editor::T ) ?>" class="tge-media-url-name"><#= item.getUrlPlaceholder() #></label>
	</div>
	<div class="tge-select-media-video <#= 'custom' === item.get('source') ? '' : 'tvd-hiddendiv' #>">
		<span><?php echo __( 'Select file', Thrive_Graph_Editor::T ) ?></span>
	</div>
	<div class="tge-select-media-video-err"> </div>
</div>

<div class="tvd-input-field mb-20 tge-display-style-container"></div>

<div class="tge-display-options-container">
	<div id="tge-display-video-options" class="tge-display-options">
		<span><?php echo __( 'Advanced', Thrive_Graph_Editor::T ) ?></span>
		<div class="tge-vopts-selected-elem <#= '' === this.model.get( 'url' ) ? 'tge-options-disabled' : '' #>"><?php echo __( 'Display Options', Thrive_Graph_Editor::T ) ?></div>
	</div>
	<div class="tge-display-options-data tvd-hiddendiv"></div>
</div>
