<div class="custom-fields-options mt-5 full-width">
	<label><?php echo __( 'Custom Source', 'thrive-cb' ); ?></label>
	<select data-fn="selectCustomField" class="change"></select>
</div>
<div class="tve-advanced-controls custom-fields-more-options full-width extend-grey">
	<div class="dropdown-header" data-prop="advanced">
			<span>
				<?php echo __( 'More Options', 'thrive-cb' ); ?>
			</span>
	</div>
	<div class="dropdown-content pt-0">
		<label><?php echo __( 'If not available', 'thrive-cb' ); ?></label>
		<select class="custom-fields-placeholder-options change mb-5" data-fn="selectPlaceholder">
			<option value="hide"><?php echo __( 'Hide element', 'thrive-cb' ); ?></option>
			<option value="replace"><?php echo __( 'Show Default', 'thrive-cb' ); ?></option>
		</select>
		<div class="custom-fields-placeholder-input">
			<label><?php echo __( 'Default', 'thrive-cb' ); ?></label>
			<div class="image-picker-input"></div>
		</div>
	</div>
</div>
