<span class="subtitle control-grid center m-20 p-0">
	<?php echo __( 'Choose an existing display template below or create a new list of testimonials', TVO_TRANSLATE_DOMAIN ); ?>
</span>
<div id="tvo-testimonial-shortcode-list">
	<a class="tvo-shortcode-box tvo-create-testimonial-list w-100" href="#pre-select">
		<div class="tvo-card tvo-card-xsmall">
			<div class="tvo-card-content">
				<span class="tvo-f-icon-add tvo-add-testimonial"></span>
				<?php echo __( 'Create New Display Template', TVO_TRANSLATE_DOMAIN ); ?>
			</div>
		</div>
	</a>
</div>
