<div class="tvo-row">
	<div class="tvo-col tvo-s8">
		<h4>
			<?php echo __( 'Drag and drop testimonials into the desired order below', 'thrive-ovation' ); ?>
		</h4>
	</div>
	<div class="tvo-col tvo-s4">
		<button class="tve-button blue tvd-right tvo-randomize-testimonials">
			<?php echo __( 'Randomize', 'thrive-ovation' ); ?>
		</button>
	</div>
</div>
<div class="tvo-testimonials-list-order ui-sortable"></div>
