<div class="tvo-small-container">
	<span class="subtitle control-grid center m-20 p-0">
		<?php echo __( 'Choose your selection mode', TVO_TRANSLATE_DOMAIN ); ?>
	</span>

	<div class="tvo-row tvo-collapse">
		<div class="tvo-col tvo-s6">
			<div class="tvo-select-testimonials">
				<div class="tvo-card tvo-card-medium tvo-full tvo-pointer">
					<div class="tvo-card-content tvo-center-text tvo-large-icon tvo-blue-text">
						<div class="tvo-f-icon-chat"></div>
						<p>
							<strong>
								<?php echo __( 'Testimonials', TVO_TRANSLATE_DOMAIN ); ?>
							</strong><br>
							<span>
								<?php echo __( 'build static content', TVO_TRANSLATE_DOMAIN ); ?>
							</span>
						</p>
					</div>
				</div>
			</div>
		</div>
		<div class="tvo-col tvo-s6">
			<div class="tvo-select-tags">
				<div class="tvo-card tvo-card-medium tvo-full tvo-pointer">
					<div class="tvo-card-content tvo-center-text tvo-large-icon tvo-blue-text">
						<div class="tvo-f-icon-tags"></div>
						<p>
							<strong>
								<?php echo __( 'Tags', TVO_TRANSLATE_DOMAIN ); ?>
							</strong><br>
							<span>
								<?php echo __( 'build dynamic content', TVO_TRANSLATE_DOMAIN ); ?>
							</span>
						</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
