<div class="tvo-small-container">
	<span class="subtitle control-grid center m-20 p-0">
		<?php echo __( 'You have ', 'thrive-ovation' ); ?>
		<span class="pl-5 pr-5"><#= count #></span>&nbsp;
		<span><#= selection #></span>&nbsp;
		<?php echo __( ' on your list', 'thrive-ovation' ); ?>
	</span>

	<div class="tvo-row tvo-collapse">
		<div class="tvo-col tvo-s6">
			<div class="tvo-save-template">
				<div class="tvo-card tvo-card-medium tvo-full tvo-pointer">
					<div class="tvo-card-content tvo-center-text tvo-large-icon tvo-blue-text">
						<div class="tvo-f-icon-save"></div>
						<p>
							<strong>
								<?php echo __( 'Save for future use', 'thrive-ovation' ); ?>
							</strong>
						</p>
					</div>
				</div>
			</div>
		</div>
		<div class="tvo-col tvo-s6">
			<div class="tvo-display-shortcode" id="tvo-display-testimonials-shortcode-wrapper">
				<div class="tvo-card tvo-card-medium tvo-full tvo-pointer">
					<div class="tvo-card-content tvo-center-text tvo-large-icon tvo-text-green">
						<div class="tvo-f-icon-check"></div>
						<p>
							<strong>
								<?php echo __( 'Finish without saving', 'thrive-ovation' ); ?>
							</strong>
						</p>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="tvo-template-name" style="display: none;">
		<div class="tvo-spacer"></div>
		<h6>
			<?php echo __( 'Give your template a name', 'thrive-ovation' ); ?>
		</h6>
		<div class="tvo-row tvo-collapse">
			<div class="tvo-col tvo-s8">
				<input type="text" class="tve_lightbox_input tvo-display-testimonial-shortcode-name" placeholder="<?php echo __( 'template name', 'thrive-ovation' ); ?>">
			</div>
			<div class="tvo-col tvo-s4">
				<button class="tvo-save-testimonial-shortcode tve-button blue">
					<?php echo __( 'SAVE AND CLOSE', 'thrive-ovation' ); ?>
				</button>
			</div>
		</div>
	</div>
</div>
