<span class="subtitle control-grid center w-100">
	<?php echo __( 'You have <b class="p-5">0</b> tags on your list', 'thrive-ovation' ); ?>
</span>

<div class="tve_scTC tve_scTC1" style="display: block;">
	<div id="tvo-tags-list" class="tvo-row"></div>
	<div class="tvo-row tvo-collapse">
		<div class="tvo-col tvo-s4">
			<p>
				<span class="tvo-margin-right-small"></span>
				<?php echo __( 'Max number of testimonials', 'thrive-ovation' ) ?>
			</p>
		</div>
		<div class="tvo-col tvo-s6">
			<input class="tvo_config_field tve_lightbox_input tvo_max_testimonials" type="text" value="<#= max_testimonials #>">
		</div>
	</div>
</div>
<div class="tve_clear" style="height: 15px;"></div>

