<div class="drop-panel panel-light tve-delete-confirmation">
	<div class="popup-content">

	</div>
	<div class="action-buttons control-grid">
		<div data-fn="onCancel" class="click tve-button drop-panel-action btn-cancel"><?php echo __( 'No', 'thrive-cb' ) ?></div>
		<div data-fn="onApply" class="click tve-button drop-panel-action btn-apply"><?php echo __( 'Yes', 'thrive-cb' ) ?></div>
	</div>
	<div class="tcb-panel-arrow tve-top-drop-panel"></div>
</div>
