<div class="ttd-wizard-menu-box fw ttd-wizard-clip clip-menu placeholder">
	<div class="ttd-wizard-menu-icon"><?php tva_get_svg_icon( 'wizard-menu-icon' ); ?></div>
	<p class="ttd-wizard-desc desc-secondary mt-10 mb-30"><?php echo __( 'Which menus do you want to use in headers and footers?', TVA_Const::T ); ?></p>

	<# if ( this.menus.length ) { #>
	<div class="tva-flex menu-fixed-width">
		<div class="ttd-menus-selector ttd-wizard-selector click" data-fn="toggleDropdown">
			<p class="ttd-wizard-desc wizard-drop-label">
				<?php echo __( 'Header menu', TVA_Const::T ); ?>
			</p>
			<span class="selector-drop">
					<span class="selected-menu" data-target="header"><#= this.activeMenus.header.name #></span>
					<?php Thrive_Views::svg_icon( 'chevron-down' ); ?>
					<div class="menu-dropdown">
						<#_.each( this.menus, function( item ) { #>
							<span class="click<#= item.extra_class || '' #>" data-fn="selectItem" data-target="header"
									data-id="<#= item.id #>"><#= item.name #></span>
						<#}, this)#>
					</div>
				</span>
		</div>

		<div class="ml-30 ttd-menus-selector ttd-wizard-selector click" data-fn="toggleDropdown">
			<p class="ttd-wizard-desc wizard-drop-label">
				<?php echo __( 'Footer menu', TVA_Const::T ); ?>
			</p>
			<span class="selector-drop">
					<span class="selected-menu" data-id="<#= this.activeMenus.footer #>" data-target="footer"><#= this.activeMenus.footer.name #></span>
					<?php Thrive_Views::svg_icon( 'chevron-down' ); ?>
					<div class="menu-dropdown">
						<#_.each( this.menus, function( item ) { #>
							<span class="click<#= item.extra_class || '' #>" data-fn="selectItem" data-target="footer"
									data-id="<#= item.id #>"><#= item.name #></span>
						<#}, this)#>
					</div>
				</span>
		</div>
	</div>
	<button class="ttd-choose-menu ttd-btn click fill blue loader-absolute small mt-30 menu-fixed-width"
		data-fn="finishMenu"><?php echo __( 'Use selected menus', TVA_Const::T ) ?></button>

	<# } else { #>
	<div class="no-menu-notice">
		<?php echo sprintf( __( 'No WordPress menu %s Go and ' ), '<br>', TVA_Const::T ); ?>
		<a href="<?php echo admin_url( 'nav-menus.php' ) ?>" target="_blank"><?php echo __( 'create your first menu', TVA_Const::T ); ?></a>
	</div>
	<# } #>

	<div class="ttd-menu-or"><span><?php echo __( 'or', TVA_Const::T ); ?></span></div>

	<button class="ttd-finish-button ttd-btn click blue mt-15 loader-absolute small" data-templates='1'
			data-fn="finishMenu"><?php echo __( 'Continue without choosing a menu', TVA_Const::T ); ?></button>
</div>
