<div class="ttd-wizard-welcome ttd-wizard-finished">
	<img class="ttd-wizard-splash" src="<?php echo TVA_Const::plugin_url( 'admin/includes/assets/img/wizard/splash@2x.png' ); ?>" height="135">
	<h2 class="ttd-wizard-title"><?php echo esc_html__( 'School wizard complete', TVA_Const::T ); ?></h2>
	<p class="ttd-wizard-desc f-20 mt-0 mb-0"><?php echo esc_html__( "Your school has now been built using the designs you've chosen.", TVA_Const::T ); ?></p>
	<p class="ttd-wizard-desc f-20 mt-20 mb-0"><?php echo sprintf( esc_html__( 'You can revisit the wizard at any time by clicking on the %s design icon in the left panel.', TVA_Const::T ), '<br>' ); ?></p>

	<# if(!skin.get('is_active')) { #>
	<div class="tva-flex mt-30">
		<button data-fn="publishSkin" class="click ttd-next-option bg-white ttd-btn fill green">
			<?php echo esc_html__( 'Publish school design', TVA_Const::T ); ?>
		</button>

		<a target="_blank" href="<#= TVA.indexPageModel.previewUrl({tva_skin_id: wizard.SKIN_ID}) #>" class="tva-skin-preview-link light ml-20">
			<span><?php tva_get_svg_icon( 'eye-empty' ); ?></span>
			<span><?php echo esc_html__( 'Preview school design', TVA_Const::T ); ?></span>
		</a>
	</div>
	<# } #>

	<a href="#design/<#=wizard.SKIN_ID#>" class="ttd-next-option ttd-back-to-dash mt-30">
		<?php echo esc_html__( 'Go to dashboard', TVA_Const::T ); ?>
	</a>
</div>
