<div class="ttd-wizard-welcome">
	<img class="ttd-wizard-splash" src="<?php echo TVA_Const::plugin_url( 'admin/includes/assets/img/wizard/splash@2x.png' ); ?>" height="135">
	<h2 class="ttd-wizard-title"><?php echo esc_html__( 'Welcome to the school wizard', 'thrive-apprentice' ); ?></h2>
	<div class="wizard-splash">
		<p class="ttd-wizard-desc f-20 mt-0 mb-0"><?php echo esc_html__( 'Design a unique and branded learning experience for your customers in a few clicks', 'thrive-apprentice' ); ?></p>
		<button type="button" data-fn="start" class="ttd-btn click fill blue ttd-wizard-start mt-30"><?php echo esc_html__( 'Get Started!', 'thrive-apprentice' ); ?></button>
		<img class="ttd-wizard-stars mt-30" src="<?php echo TVA_Const::plugin_url( 'admin/includes/assets/img/wizard/stars@2x.png' ); ?>" width="50">
		<p class="ttd-wizard-desc mt-30 mb-0"><strong><?php echo esc_html__( 'Please note', 'thrive-apprentice' ); ?></strong></p>
		<p class="ttd-wizard-desc mt-5 mb-0"><?php echo esc_html__( 'Anything you select in this wizard will only be applied to your school and not your entire site', 'thrive-apprentice' ); ?></p>

	</div>
</div>
