<# if ( this.model.hasActiveStep() ) { #>
<div class="ttd-wizard-summary<# if ( this.model.hasPreviousStepLink() ) { #> with-link<# } #>">
	<h2><#=this.model.getStepTitle() #></h2>
	<# if ( this.model.hasPreviousStepLink() ) { #>
	<a class="wizard-link-prev click" data-fn="previousClick" href="javascript:void(0)">
		<?php Thrive_Views::svg_icon( 'chevron-left' ); ?>
		<span class="link-text"><?php echo esc_html__( 'Previous Step', 'thrive-apprentice' ); ?></a></span>
	<# } #>
</div>
<# } #>
<# if ( this.model.hasTemplateSelector() ) { #>
<div id="template-selector" class="ttd-wizard-part">
	<?php include __DIR__ . '/top/template-selector.phtml'; ?>
</div>
<# } #>
