<div class="column-options">
	<div class="tve-columns-options" data-cols="2">
		<div class="panel-title"><?php echo sprintf( __( '%d Columns', 'thrive-cb' ), 2 ) ?></div>
	</div>
	<div class="tve-columns-options" data-cols="3">
		<div class="panel-title"><?php echo sprintf( __( '%d Columns', 'thrive-cb' ), 3 ) ?></div>
	</div>
</div>
<div class="tcb-col-preview tcb-text-center">
	<div class="tve-columns-options" data-cols="2">
		<div class="flex-row click" data-fn="onApply" data-index="0">
			<div class="flex-col c-50">
				<div class="desc">1/2</div>
			</div>
			<div class="flex-col c-50">
				<div class="desc">1/2</div>
			</div>
		</div>
		<div class="flex-row click" data-fn="onApply" data-index="1">
			<div class="flex-col c-33">
				<div class="desc">1/3</div>
			</div>
			<div class="flex-col c-66">
				<div class="desc">2/3</div>
			</div>
		</div>
		<div class="flex-row click" data-fn="onApply" data-index="2">
			<div class="flex-col c-66">
				<div class="desc">2/3</div>
			</div>
			<div class="c-33 flex-col">
				<div class="desc">1/3</div>
			</div>
		</div>
	</div>
	<div class="tve-columns-options" data-cols="3">
		<div class="flex-row click" data-fn="onApply" data-index="0">
			<div class="flex-col c-33">
				<div class="desc">1/3</div>
			</div>
			<div class="flex-col c-33">
				<div class="desc">1/3</div>
			</div>
			<div class="flex-col c-33">
				<div class="desc">1/3</div>
			</div>
		</div>
		<div class="flex-row click" data-fn="onApply" data-index="1">
			<div class="flex-col c-25 ">
				<div class="desc">1/4</div>
			</div>
			<div class="flex-col c-50">
				<div class="desc">2/4</div>
			</div>
			<div class="flex-col c-25">
				<div class="desc">1/4</div>
			</div>
		</div>
		<div class="flex-row click" data-fn="onApply" data-index="2">
			<div class="flex-col c-25">
				<div class="desc">1/4</div>
			</div>
			<div class="flex-col c-25">
				<div class="desc">1/4</div>
			</div>
			<div class="flex-col c-50">
				<div class="desc">2/4</div>
			</div>
		</div>
		<div class="flex-row click" data-fn="onApply" data-index="3">
			<div class="flex-col c-50">
				<div class="desc">2/4</div>
			</div>
			<div class="flex-col c-25 ">
				<div class="desc">1/4</div>
			</div>
			<div class="flex-col c-25">
				<div class="desc">1/4</div>
			</div>
		</div>
	</div>
</div>
