<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-dashboard
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}
?>

<ul class="tvd-ss-breadcrumbs">
	<# links.each( function( item, index ) { item.has_link = index < links.size() - 1 #>
	<li class="tvd-breadcrumb <#= ( item.has_link ? '' : ' tva-no-link' ) #>">
		<# if ( item.has_link ) { #><a href="<#= item.get_url() #>"><# } #>
			<#= _.escape ( item.get ( 'label' ) ) #>
		<# if ( item.has_link ) { #></a><# } #>
	</li>
	<# } ) #>
</ul>
