<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-apprentice
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden!
}
?>
<button class="tve-c-modal-radio-item click<#= item.default ? ' active':''#>" data-fn="onRadioFilterClick" data-id="<#= item.id #>">
	<span class="radio-filter-label"><#= item.label #></span>
	<span class="radio-filter-count"><#= item.count #></span>
</button>
