<?php
/**
 * Created by PhpStorm.
 * User: Ovidiu
 * Date: 12/13/2018
 * Time: 4:23 PM
 */

/**
 * Used in:
 * editor/js/main/views/controls/global/style-picker.js
 * editor/js/main/views/controls/global/style-panel.js
 */
?>

<div class="thrv_wrapper thrv_contentbox_shortcode thrv-content-box <#= cls #>">
	<div class="tve-content-box-background <#= cls #>-bg"></div>
	<div class="tve-cb <#= cls #>-cb"></div>
</div>
<# if(text.length > 0){ #>
<p><#= text #></p>
<# } #>
