<div class="tva-generate">
	<form class="tva-generate-courses">
		<div class="mb-10">
			<p><?php echo __( 'The courses will be generated with a random number of modules/chapters/lessons from the intervals given', 'thrive-apprentice' ) ?></p>
			<b><?php echo __( 'Select Number of courses', 'thrive-apprentice' ) ?> </b>
			<br/>
			<input type="number" id="course-count" name="courseCount" value="1">
		</div>
		<div class="mb-10">
			<b><?php echo __( 'Select Number of modules', 'thrive-apprentice' ) ?></b>
			<br/>
			<label for="min-modules"><b><?php echo __( 'From', 'thrive-apprentice' ) ?></b></label>
			<input type="number" id="min-modules" name="minModules" value="0">
			<label for="max-modules"><b><?php echo __( 'To', 'thrive-apprentice' ) ?></b></label>
			<input type="number" id="max-modules" name="maxModules" value="0">
		</div>
		<div class="mb-10">
			<b><?php echo __( 'Select Number of Chapters', 'thrive-apprentice' ) ?></b>
			<br/>
			<label for="min-chapters"><b><?php echo __( 'From', 'thrive-apprentice' ) ?></b></label>
			<input type="number" id="min-chapters" name="minChapters" value="0">
			<label for="max-chapters"><b><?php echo __( 'To', 'thrive-apprentice' ) ?></b></label>
			<input type="number" id="max-chapters" name="maxChapters" value="0">
		</div>
		<div class="mb-10">
			<b><?php echo __( 'Select Number of Lessons', 'thrive-apprentice' ) ?></b>
			<br/>
			<label for="min-lessons"><b><?php echo __( 'From', 'thrive-apprentice' ) ?></b></label>
			<input type="number" id="min-lessons" name="minLessons" value="1">
			<label for="max-lessons"><b><?php echo __( 'To', 'thrive-apprentice' ) ?></b></label>
			<input type="number" id="max-lessons" name="maxLessons" value="1">
		</div>
		<button class="tva-btn tva-btn-blue" type="button" data-fn="tva-generate-courses"><?php echo __( 'Generate Courses', 'thrive-apprentice' ) ?></button>
		<button class="tva-btn tva-btn-red" type="button" data-fn="tva-delete-generated-courses"><?php echo __( 'Delete Generated Courses', 'thrive-apprentice' ) ?></button>
	</form>
</div>

<div class="tva-generate">
	<form class="tva-generate-products">
		<div class="mb-10">
			<label for="products-count"><b><?php echo __( 'Select Number of Products', 'thrive-apprentice' ) ?></b></label>
			<br/>
			<input type="number" id="products-count" name="productsCount" value="1">
			<br/>
			<b><?php echo __( 'Select Course Percentage per Product', 'thrive-apprentice' ) ?></b>
			<br/>
			<label for="course-percentage-min"><b><?php echo __( 'From', 'thrive-apprentice' ) ?></b></label>
			<input type="number" min="0" max="100" id="course-percentage-min" name="coursePercentageMin" value="30">
			<label for="course-percentage-max"><b><?php echo __( 'To', 'thrive-apprentice' ) ?></b></label>
			<input type="number" min="0" max="100" id="course-percentage-max" name="coursePercentageMax" value="50">
			<br/>
			<button class="tva-btn tva-btn-blue" data-fn="tva-generate-products" type="button"><?php echo __( 'Generate Products', 'thrive-apprentice' ) ?></button>
			<button class="tva-btn tva-btn-red" data-fn="tva-delete-generated-products" type="button"><?php echo __( 'Delete Generated Products', 'thrive-apprentice' ) ?></button>
		</div>
	</form>
</div>

<div class="tva-generate">
	<form class="tva-generate-members">
		<div class="mb-10">
			<label for="members-count"><b><?php echo __( 'Select Number of Members', 'thrive-apprentice' ) ?></b></label>
			<br/>
			<input type="number" id="members-count" name="membersCount" value="1">
			<br/>
			<b><?php echo __( 'Select Products Percentage per Member', 'thrive-apprentice' ) ?></b>
			<br/>
			<label for="product-percentage-min"><b><?php echo __( 'From', 'thrive-apprentice' ) ?></b></label>
			<input type="number" min="0" max="100" id="product-percentage-min" name="productPercentageMin" value="10">
			<label for="product-percentage-max"><b><?php echo __( 'To', 'thrive-apprentice' ) ?></b></label>
			<input type="number" min="0" max="100" id="product-percentage-max" name="productPercentageMax" value="20">
			<br/>
			<button class="tva-btn tva-btn-blue" type="button" data-fn="tva-generate-members"><?php echo __( 'Generate Members', 'thrive-apprentice' ) ?></button>
			<button class="tva-btn tva-btn-red" type="button" data-fn="tva-delete-generated-members"><?php echo __( 'Delete Generated Members', 'thrive-apprentice' ) ?></button>
		</div>
	</form>
</div>


<div class="tva-generate">
	<form class="tva-generate-completion">
		<div class="mb-10">
			<b><?php echo __( 'Select Completion Rate', 'thrive-apprentice' ) ?></b>
			<br/>
			<label for="completion-percentage-min"><b><?php echo __( 'From', 'thrive-apprentice' ) ?></b></label>
			<input type="number" min="0" max="100" id="completion-percentage-min" name="completionPercentageMin" value="30">
			<label for="completion-percentage-max"><b><?php echo __( 'To', 'thrive-apprentice' ) ?></b></label>
			<input type="number" min="0" max="100" id="completion-percentage-max" name="completionPercentageMax" value="60">
			<br/>
			<button class="tva-btn tva-btn-blue" type="button" data-fn="tva-generate-completion"><?php echo __( 'Generate Completion', 'thrive-apprentice' ) ?></button>
			<button class="tva-btn tva-btn-red" type="button" data-fn="tva-delete-generated-completion"><?php echo __( 'Delete Generated Completion', 'thrive-apprentice' ) ?></button>
		</div>
	</form>
</div>
