<p class="tva-text"><?php echo esc_html__( 'Click to upload an image', 'thrive-apprentice' ); ?></p>
<p class="tva-text lighter"><?php echo esc_html__( 'Recommended size:', 'thrive-apprentice' ) ?> 1170px x 400px</p>

<button class="tva-details-btn removeImage">
	<?php tva_get_svg_icon( 'trash-1' ); ?>
	<?php echo esc_html__( 'Remove', 'thrive-apprentice' ); ?>
</button>

<button class="tva-details-btn uploadImage">
	<?php tva_get_svg_icon( 'upload_light' ); ?>
	<?php echo esc_html__( 'Upload', 'thrive-apprentice' ); ?>
</button>
