<?php

/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-apprentice
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden!
}
?>

<div class="tva-flex tva-space-center tva-align-center" style="width: 100%; gap: 10px;">
	<img alt="Spinner" src="<?php echo TVA_Const::plugin_url( 'admin/img/loading-spinner.gif' ); ?>"/>
	<div class="tva-pagination-loading-text"><#= text #></div>
</div>
