<div class="tve-video-resize">
	<div class="tve-video-control-wrapper">
		<div class="tve-video-resize-control tve-corner-resize tve-drag-top-left" data-cursor="nwse-resize" data-reverse="1"></div>
		<div class="tve-video-resize-control tve-corner-resize tve-drag-top-right" data-cursor="nesw-resize"></div>
		<div class="tve-video-resize-control tve-corner-resize tve-drag-bottom-right" data-cursor="nwse-resize"></div>
		<div class="tve-video-resize-control tve-corner-resize tve-drag-bottom-left" data-cursor="nesw-resize" data-reverse="1"></div>
		<div class="tve-drag-helper tve-video-drag-middle-horiz tcb-permanently-hidden"></div>
		<div class="tve-drag-helper tve-video-drag-middle-vert tcb-permanently-hidden"></div>
		<div class="tve-drag-video tve-draggable" draggable="true"></div>
	</div>
</div>