<div class="fr-checkbox-line tve-top-tabs">
	<label id="static-link" class="tcb-radio">
		<input type="radio" name="static-link-type" class="fr-link-type" value="static" checked><span><?php echo __( 'Static', 'thrive-cb' ); ?></span></label>
	<label id="jump-link" class="tcb-radio">
		<input type="radio" name="jump-link-type" class="fr-link-type" value="jump"><span><?php echo __( 'JumpLink', 'thrive-cb' ); ?></span></label>
	<label id="dynamic-link" class="tcb-radio">
		<input type="radio" name="dynamic-link-type" class="fr-link-type" value="dynamic"><span><?php echo __( 'Dynamic', 'thrive-cb' ); ?></span></label>
</div>
