<div class="control-grid full-width pb-0">
	<span>
		<?php echo esc_html__( 'Selected options will apply a unique tag to the subscriber in your mailing list.', 'thrive-cb' ); ?>
	</span>
	<br>
	<a href="https://thrivethemes.com/tkb_item/how-to-send-answers-from-a-lead-generation-element-as-tags-to-your-autoresponder/" target="_blank">
		<?php echo __( 'Learn more here', 'thrive-cb' ) ?>
	</a>
	<br>
	<span>
		<?php echo esc_html__( 'Apostrophes, quotation marks and slashes will be removed from your tags.', 'thrive-cb' ); ?>
	</span>
</div>