<div class="tve-parallax-controls">
	<div class="tve-control tve-parallax-effect-type drop-panel-control" data-key="ParallaxEffects" data-name="<?php esc_attr_e( 'Effect', 'thrive-cb' ); ?>"></div>
	<div class="tve-control tve-parallax-effect-direction drop-panel-control" data-key="ParallaxDirection" data-name="<?php esc_attr_e( 'Type', 'thrive-cb' ); ?>"></div>
	<div class="if-perspective">
		<div class="tve-control tve-parallax-effect-perspective-angle drop-panel-control" data-name="<?php esc_attr_e( 'Degrees', 'thrive-cb' ); ?>"></div>
		<div class="tve-control tve-parallax-effect-perspective drop-panel-control" data-name="<?php esc_attr_e( 'Perspective', 'thrive-cb' ); ?>"></div>
	</div>
	<div class="tve-control tve-parallax-effect-speed drop-panel-control"></div>
	<div class="tve-control tve-parallax-effect-viewport-start drop-panel-control" data-name="<?php esc_attr_e( 'Viewport Start', 'thrive-cb' ); ?>"></div>
	<div class="tve-control tve-parallax-effect-viewport-end drop-panel-control" data-name="<?php esc_attr_e( 'Viewport End', 'thrive-cb' ); ?>"></div>
</div>