<div class="tve-image-resize">
	<div class="tve-image-control-wrapper">
		<div class="tve-image-resize-control tve-corner-resize tve-drag-top-left" data-cursor="nwse-resize" data-reverse="1"></div>
		<div class="tve-image-resize-control tve-central-resize tve-drag-top-center" data-cursor="ns-resize" data-reverse="1"></div>
		<div class="tve-image-resize-control tve-corner-resize tve-drag-top-right" data-cursor="nesw-resize"></div>
		<div class="tve-image-resize-control tve-corner-resize tve-drag-bottom-right" data-cursor="nwse-resize"></div>
		<div class="tve-image-resize-control tve-central-resize tve-drag-bottom-center" data-cursor="ns-resize"></div>
		<div class="tve-image-resize-control tve-corner-resize tve-drag-bottom-left" data-cursor="nesw-resize" data-reverse="1"></div>
		<div class="tve-drag-helper tve-image-drag-middle-horiz tcb-permanently-hidden"></div>
		<div class="tve-drag-helper tve-image-drag-middle-vert tcb-permanently-hidden"></div>
		<div class="tve-drag-image tve-draggable" draggable="true"></div>
	</div>
</div>