<div class="tve-login-form-item tcb-no-clone tcb-no-delete tcb-no-save">
	<div class="thrv-form-input-wrapper tcb-no-clone tcb-no-delete tcb-no-save" data-type="<#= config.type || config.strippedName #>">
		<div class="thrv_wrapper tcb-label tcb-removable-label thrv_text_element tcb-no-delete tcb-no-save tcb-no-clone tve_no_drag"<#= config.showLabel ? '' : ' style="display: none"'#>>
			<div class="tcb-plain-text"><#-label #></div>
		</div>
		<div class="tcb-no-clone tcb-no-delete tcb-no-save tcb-input-generic"></div>
	</div>
</div>
