<div class="tqb-gray-box">

	<p class="tqb-mt3b9"><?php echo __( 'Preview', Thrive_Quiz_Builder::T ) ?></p>

	<div class="tqb-tooltip-demo"><?php echo __( 'Lorem ipsum dolor', Thrive_Quiz_Builder::T ) ?></div>

	<div class="tqb-prev-demo">
		<span class="feedback-green"><?php echo __( 'A message is displayed if the quiz participant chooses the right answer.', Thrive_Quiz_Builder::T ) ?></span>
		<span class="feedback-blue"><?php echo __( 'This is how feedback is displayed after the participant answers a question.', Thrive_Quiz_Builder::T ) ?></span>
	</div>

	<div class="tqb-button-holder">
		<div class="tqb-empty"></div>

		<div class="tqb-next-button">
			<svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" viewBox="0 0 40 40">
				<path fill="#0F7DBE" fill-rule="nonzero"
				      d="M20 0c11.048 0 20 8.952 20 20s-8.952 20-20 20S0 31.048 0 20 8.952 0 20 0zm-2.33 11.58l6.088 5.84H9.032a1.93 1.93 0 0 0-1.935 1.935v1.29a1.93 1.93 0 0 0 1.935 1.936h14.726l-6.089 5.838c-.782.75-.798 2-.032 2.766l.887.88a1.927 1.927 0 0 0 2.734 0L31.96 21.37a1.927 1.927 0 0 0 0-2.734L21.258 7.927a1.927 1.927 0 0 0-2.734 0l-.887.88a1.947 1.947 0 0 0 .032 2.774z"/>
			</svg>
		</div>
	</div>

</div>
