<div class="tqb-feedback-settings">

	<p class="tqb-mpbt">
		<?php echo __( 'How long should the feedback be displayed for?', 'thrive-quiz-builder' ) ?>
	</p>

	<div class="tqb-options tqb-mb0">
		<input class="tqb-display-feedback tqb-radio-option" id="tqb-no-feedback" type="radio" data-attr="dont_display_feedback"
		<#= model.get( 'display_feedback' ) !== 1 && model.get( 'press_next' ) !== 1 ? 'checked' : '' #> />
		<label for="tqb-no-feedback" class="tqb-mr30">
			<?php echo __( 'Don\'t display feedback', 'thrive-quiz-builder' ) ?>
		</label>

		<input class="tqb-display-feedback tqb-radio-option" id="tqb-checkbox-seconds" type="radio" data-attr="display_feedback"
		<#= model.get( 'display_feedback' ) === 1 ? 'checked' : '' #> />
		<label for="tqb-checkbox-seconds"></label>

		<input type="text" id="tqb-feedback-time" value="<#= model.get( 'display_feedback_time' ) #>" data-bind="display_feedback_time">
		<label for="tqb-checkbox-seconds" class="tqb-mr30 tqb-feedback-seconds">
			<?php echo __( ' seconds', 'thrive-quiz-builder' ) ?>
		</label>

		<input class="tqb-press-next tqb-radio-option" id="tqb-checkbox-press-next" type="radio" data-attr="press_next"
		<#= model.get( 'press_next' ) === 1 ? 'checked' : '' #> />
		<label for="tqb-checkbox-press-next">
			<?php echo __( 'Until the user presses the Next button', 'thrive-quiz-builder' ) ?>
		</label>
	</div>

	<p class="tqb-mpbt tqb-mt0">
		<?php echo __( 'Allow users to go back and revisit previous questions?', 'thrive-quiz-builder' ) ?>
	</p>

	<div class="tqb-options">
		<div class="tvd-switch">
			<label>
				<input id="tqb-nav-buttons" type="checkbox" data-bind="nav_buttons" <#= model.get( 'nav_buttons' ) === true ? 'checked' : '' #>>
				<span class="tqb-ml3 tvd-lever"></span>
			</label>
			<label for="tqb-nav-buttons" class="tqb-mr30">
				<?php echo __( 'Display navigation buttons', 'thrive-quiz-builder' ) ?>
			</label>
		</div>
	</div>

</div>
