<div id="c-f-placeholder-wrapper" class="control-grid">
	<div class="label">
		<?php echo __( 'Placeholder', 'thrive-theme' ); ?>
	</div>
	<div class="input">
		<input type="text" class="change input c-f-placeholder" data-fn="changeSetting" data-fn-input="changeSetting" data-setting="placeholder"/>
	</div>
</div>
<div id="c-f-label-wrapper" class="control-grid">
	<div class="label">
		<?php echo __( 'Label', 'thrive-theme' ); ?>
	</div>
	<div class="input">
		<input type="text" class="change input c-f-label" data-fn="changeSetting" data-fn-input="changeSetting" data-setting="label"/>
	</div>
</div>
