<div class="tcb-tooltip progress-bar-tooltip">
	<div class="tcb-tooltip-text">
		<div class="bar-position">
			<p class="mb-5">
				<?php echo __( 'Top of viewport', 'thrive-theme' ); ?>
			</p>
			<div class="image-container">
				<img src="<?php echo THEME_URL . '/inc/assets/images/progress-bar-top.png'; ?>" alt="">
			</div>
		</div>
		<div class="ml-20 bar-position">
			<p class="mb-5">
				<?php echo __( 'Underneath the header', 'thrive-theme' ); ?>
			</p>
			<div class="image-container">
				<img src="<?php echo THEME_URL . '/inc/assets/images/progress-bar-underneath.png'; ?>" alt="">
			</div>
		</div>
	</div>
</div>
