<div>
	<div class="tcb-page-map click mouseenter mouseleave mouseover" data-fn="boxHover" data-fn-click="selectSection" data-section="#wrapper">
		<div class="tsp-header tsp-box click mouseenter mouseleave mouseover has-visibility-icon" data-fn-click="selectSection" data-fn="boxHover" data-section="header" data-selector=".thrv_header">
			<span><?php echo __( 'Header', 'thrive-theme' ); ?></span>
		</div>

		<div class="tsp-content tsp-wrapper mouseenter mouseleave mouseover click" data-fn="boxHover" data-fn-click="selectSection" data-section="#content .main-content-background" data-selector=".main-content-background">

			<div class="tsp-top tsp-box click mouseenter mouseleave mouseover has-visibility-icon" data-fn-click="selectSection" data-fn="boxHover" data-section="top" data-selector=".top-section .section-content">
				<span><?php echo __( 'Top', 'thrive-theme' ); ?></span>
			</div>

			<div class="tsp-columns">
				<div class="tsp-content tsp-box click mouseenter mouseleave" data-fn-click="selectSection" data-fn="boxHover" data-section="content" data-selector=".content-section .section-content">
					<span><?php echo __( 'Content', 'thrive-theme' ); ?></span>
				</div>
				<div class="tsp-sidebar tsp-box click mouseenter mouseleave mouseover has-visibility-icon" data-fn-click="selectSection" data-fn="boxHover" data-section="sidebar" data-selector=".sidebar-section .section-content">
					<?php tcb_icon( 'sticky-sidebar', false, 'sidebar', '', [
						'data-tooltip'  => __( 'Sticky on Scroll', 'thrive-theme' ),
						'data-position' => 'top',
					] ); ?>
					<span class="one-word"><?php echo __( 'Sidebar', 'thrive-theme' ); ?></span>
					<span class="two-words"><?php echo __( 'Side bar', 'thrive-theme' ); ?></span>
				</div>
			</div>

			<div class="tsp-bottom tsp-box click mouseenter mouseleave mouseover has-visibility-icon" data-fn-click="selectSection" data-fn="boxHover" data-section="bottom" data-selector=".bottom-section .section-content">
				<span><?php echo __( 'Bottom', 'thrive-theme' ); ?></span>
			</div>
		</div>

		<div class="tsp-footer tsp-box click mouseenter mouseleave mouseover has-visibility-icon" data-fn-click="selectSection" data-fn="boxHover" data-section="footer" data-selector=".thrv_footer">
			<span><?php echo __( 'Footer', 'thrive-theme' ); ?></span>
		</div>
	</div>
</div>
