<div class="tva-list-item">
	<div class="tva-flex tva-align-center tva-space-center">
		<?php tva_get_svg_icon( 'book_light' ); ?>
	</div>
	<div><#= course.get('name') #></div>
	<# if ( course.get('drip_campaigns').length ) { #>
	<select class="change" data-fn="setCampaign" data-course-id="<#= course.get('id') #>">
		<option value="0"><?php echo esc_html__( 'None', TVA_Const::T ); ?></option>
	</select>
	<# } else { #>
	<div class="tva-flex tva-align-center">
		<div class="tva-drip-gray tva-flex tva-align-center">
			<?php tva_get_svg_icon( 'ban_light', 'mr-5' ); ?>
			<?php esc_html_e( 'No drip schedule found.', TVA_Const::T ); ?>
		</div>
		&nbsp;&nbsp;
		<a href="#courses/<#= course.get('id') #>/drip"><?php esc_html_e( 'Create new', TVA_Const::T ); ?></a>
	</div>
	<# } #>
</div>
