<div class="tvd-modal-content">
	<h3 class="tvd-modal-title tqb-translate"><?php echo __( 'Add A/B Test Variation for %s', 'thrive-quiz-builder' ) ?></h3>
	<p class="tqb-translate"><?php echo __( 'Give your variation a name. This can be used to describe the design of the specific %s Variation that you are going to build, for example "Orange Variation"', 'thrive-quiz-builder' ) ?></p>
	<div class="tvd-input-field">
		<input type="text" name="post_title" data-bind="post_title" class="post_title" tabindex="1">
		<label for="add-new-form-name" class="tqb-translate"><?php echo __( 'Variation Name', 'thrive-quiz-builder' ) ?></label>
	</div>
</div>
<div class="tvd-modal-footer">
	<div class="tvd-row">
		<div class="tvd-col tvd-s12 tvd-m6">
			<a href="javascript:void(0)" class="tvd-btn-flat tvd-btn-flat-secondary tvd-btn-flat-dark tvd-modal-close tvd-waves-effect" tabindex="3">
				<?php echo __( 'Cancel', 'thrive-quiz-builder' ) ?>
			</a>
		</div>
		<div class="tvd-col tvd-s12 tvd-m6">
			<a href="javascript:void(0)" class="tvd-right tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-green tve-add-form tvd-modal-submit" tabindex="2">
				<?php echo __( 'Continue', 'thrive-quiz-builder' ) ?>
			</a>
		</div>
	</div>
</div>
