<div class="tvd-modal-content">
	<h4><?php echo __( 'Are you sure you want to archive this variation?', 'thrive-quiz-builder' ) ?></h4>

	<p><?php echo __( 'This will move the form to the archive.','thrive-quiz-builder' ) ?></p>
</div>
<div class="tvd-modal-footer">
	<div class="tvd-row">
		<div class="tvd-col tvd-s12 tvd-m6">
			<a href="javascript:void(0)" class="tvd-btn-flat tvd-btn-flat-secondary tvd-btn-flat-dark tvd-modal-close tvd-waves-effect"><?php echo __( 'Cancel', 'thrive-quiz-builder' ) ?></a>
		</div>
		<div class="tvd-col tvd-s12 tvd-m6">
			<a href="javascript:void(0)" class="tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-red tvd-right tvd-modal-submit tve-confirm-delete-action"><?php echo __( 'Move to Archive', 'thrive-quiz-builder' ) ?></a>
		</div>
	</div>
</div>
