<div class="tvd-modal-content">
	<div class="tvd-modal-title">
		<h3>
			<?php echo __( 'Social Share Badge Template you would like to use', 'thrive-quiz-builder' ) ?>
		</h3>
	</div>
	<p><?php echo __( 'Choose a Social Share Badge template or start creating one from scratch' ) ?>:</p>
	<div id="tqb-badge-templates-list"></div>
</div>
<div class="tvd-modal-footer">
	<div class="tvd-row">
		<div class="tvd-col tvd-s6">
			<a href="javascript:void(0)" class="tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-gray tvd-modal-close">
				<?php echo __( 'Cancel', 'thrive-quiz-builder' ) ?>
			</a>
		</div>
		<div class="tvd-col tvd-s6">
			<a href="javascript:void(0)"
			   class="tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-green tvd-right tvd-modal-submit">
				<?php echo __( 'Choose Template', 'thrive-quiz-builder' ) ?>
			</a>
		</div>
	</div>
</div>
