<div class="tqb-modal-step tqb-quiz-eval-type">
	<div class="tvd-modal-content">
		<h3 class="tvd-modal-title"><?php echo __( 'Quiz Evaluation Type', Thrive_Quiz_Builder::T ) ?></h3>
		<p><?php echo __( 'Choose what the result would look like', Thrive_Quiz_Builder::T ) ?></p>
		<div class="tvd-row tvd-qet-cont tvd-collapse">
			<?php foreach ( tqb()->get_quiz_types() as $prop_type ) : ?>
				<div class="tvd-col tvd-s12 tvd-m3 tqb-quiz-selector" data-type="<?php echo $prop_type['key']; ?>"
					 data-description="<?php echo $prop_type['tooltip']; ?>"
					 data-learn-more="<?php echo $prop_type['learn_more']; ?>">
					<div class="tvd-card tvd-white tvd-pointer tvd-center-align <#= (model.get('type') === '<?php echo $prop_type['key']; ?>')? 'tvd-selected-card':'' #>">
						<div class="tvd-card-content">
							<img src="<?php echo $prop_type['image']; ?>"/>
						</div>
					</div>
					<p><strong><?php echo $prop_type['label'] ?></strong></p>
				</div>
			<?php endforeach; ?>
		</div>
		<div id="tqb-quiz-type-description"></div>
	</div>
	<div class="tvd-modal-footer">
		<div class="tvd-row">
			<div class="tvd-col tvd-s12 tvd-m6">
				<a href="javascript:void(0)"
				   class="tvd-btn-flat tvd-btn-flat-secondary tvd-btn-flat-dark tvd-waves-effect tvd-modal-close">
					<?php echo __( 'Cancel', Thrive_Quiz_Builder::T ) ?>
				</a>
			</div>
			<div class="tvd-col tvd-s12 tvd-m6 tqb-continue">
				<a href="javascript:void(0)"
				   class="tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-green tvd-right tqb-modal-next-step tqb-modal-type-action">
					<?php echo __( 'Continue', Thrive_Quiz_Builder::T ) ?>
				</a>
			</div>
			<div class="tvd-col tvd-s12 tvd-m6 tqb-save tqb-hide">
				<a href="javascript:void(0)" class="tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-purple tvd-right tqb-modal-submit">
					<?php echo __( 'Save', Thrive_Quiz_Builder::T ) ?>
				</a>
			</div>
		</div>
	</div>
</div>

<!-- CATEGORY QUIZ STEP -->
<div class="tqb-modal-step">
	<div class="tvd-modal-content">
		<h3 class="tvd-modal-title"><?php echo __( 'Quiz settings', Thrive_Quiz_Builder::T ) ?></h3>

		<div class="tqb-quiz-extra-settings">
			<div class="add-category-holder"></div>
			<div class="tqb-categories-holder"></div>
			<div id="tqb-multiple-input-wrapper"></div>
			<div class="tqb-feedback-settings"></div>
			<div class="tqb-preview-settings"></div>
		</div>

	</div>
	<div class="tvd-modal-footer">
		<div class="tvd-row">
			<div class="tvd-col tvd-s12 tvd-m6">
				<a href="javascript:void(0)"
				   class="tvd-btn-flat tvd-btn-flat-secondary tvd-btn-flat-dark tvd-waves-effect tqb-modal-prev-step">
					<?php echo __( 'Back', Thrive_Quiz_Builder::T ) ?>
				</a>
			</div>
			<div class="tvd-col tvd-s12 tvd-m6">
				<a href="javascript:void(0)"
				   class="tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-purple tvd-right tqb-modal-submit">
					<?php echo __( 'Save', Thrive_Quiz_Builder::T ) ?>
				</a>
			</div>
		</div>
	</div>
</div>

<!-- RIGHT/WRONG QUIZ STEP -->
<div class="tqb-modal-step">
	<div class="tvd-modal-content">
		<h3 class="tvd-modal-title"><?php echo __( 'Quiz settings', Thrive_Quiz_Builder::T ) ?></h3>
		<div class="tqb-quiz-extra-settings">
			<div class="tqb-highlight-settings"></div>
			<div class="tqb-feedback-settings"></div>
			<div class="tqb-preview-settings"></div>
		</div>
	</div>
	<div class="tvd-modal-footer">
		<div class="tvd-row">
			<div class="tvd-col tvd-s12 tvd-m6">
				<a href="javascript:void(0)"
				   class="tvd-btn-flat tvd-btn-flat-secondary tvd-btn-flat-dark tvd-waves-effect tqb-modal-prev-step">
					<?php echo __( 'Back', Thrive_Quiz_Builder::T ) ?>
				</a>
			</div>
			<div class="tvd-col tvd-s12 tvd-m6">
				<a href="javascript:void(0)"
				   class="tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-purple tvd-right tqb-modal-submit">
					<?php echo __( 'Save', Thrive_Quiz_Builder::T ) ?>
				</a>
			</div>
		</div>
	</div>
</div>

<!-- NUMBER AND PERCENTAGE QUIZ STEP -->
<div class="tqb-modal-step tqb-feedback-special">
	<div class="tvd-modal-content">
		<h3 class="tvd-modal-title"><?php echo __( 'Quiz settings', Thrive_Quiz_Builder::T ) ?></h3>
		<div class="tqb-quiz-extra-settings">
			<div class="tqb-feedback-settings"></div>
			<div class="tqb-preview-settings"></div>
		</div>
	</div>
	<div class="tvd-modal-footer">
		<div class="tvd-row">
			<div class="tvd-col tvd-s12 tvd-m6">
				<a href="javascript:void(0)"
				   class="tvd-btn-flat tvd-btn-flat-secondary tvd-btn-flat-dark tvd-waves-effect tqb-modal-prev-step">
					<?php echo __( 'Back', Thrive_Quiz_Builder::T ) ?>
				</a>
			</div>
			<div class="tvd-col tvd-s12 tvd-m6">
				<a href="javascript:void(0)"
				   class="tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-purple tvd-right tqb-modal-submit">
					<?php echo __( 'Save', Thrive_Quiz_Builder::T ) ?>
				</a>
			</div>
		</div>
	</div>
</div>
