<div class="tvd-ni-inbox-detail">
	<div class="tvd-ni-single-header">
		<span class="ni-go-back"><?php echo __( 'Notification', 'thrive-dash' ) ?></span>
		<span class="tvd-ni-close"></span>
	</div>
	<div class="tvd-ni-detail-title">
		<#= model.get('title') #>
	</div>
	<div class="tvd-ni-detail-data">
		<#= model.get('info') #>
	</div>
	<span class="ni-go-back">&lt;&nbsp;<?php echo __( 'Back to the Notifications Lists', 'thrive-dash' ) ?></span>
</div>
