<div class="tvd-header">
	<nav id="tvd-nav">
		<div class="nav-wrapper">
			<div class="tve-logo tvd-left">
				<a href="<?php menu_page_url( 'tve_dash_section' ); ?>"
				   class="tvd-users-dashboard-logo"
				   title="<?php echo __( 'Thrive Dashboard', TVE_DASH_TRANSLATE_DOMAIN ) ?>">
                            <span class="tvd-logo-container">
                                <img class="thrive_admin_logo"
                                     src="<?php echo TVE_DASH_URL ?>/css/images/thrive-logo.png"
                                     alt="">
                            </span>
				</a>
			</div>
			<ul id="tvd-dash-submenu" class="tvd-right">
				<li>
					<a id="tvd-support-token" href="javascript:void(0)" class=" tvd-btn tvd-btn-green tvd-full-btn dashtoken">
						<?php _e( 'Support login', TVE_DASH_TRANSLATE_DOMAIN ); ?>
					</a>
				</li>
				<?php do_action( 'tvd_notification_inbox' ); ?>
				<li>
					<a id="tvd-share-modal" class="tvd-modal-trigger" href="#tvd-modal1"
					   data-overlay_class="tvd-white-bg" data-opacity=".95">
						<span class="tvd-icon-heart"></span>
					</a>
				</li>
			</ul>
			<div class="tvd-inbox-holder" style="display: none;">
				<div class="tvd-notification-header"></div>
				<div class="tvd-notification-wrapper"></div>
			</div>
		</div>
	</nav>
</div>
<?php include TVE_DASH_PATH . '/templates/share.phtml'; ?>

