<div class="control-grid">
	<div class="decoration-boxes">
		<div class="tve-decoration-side click top" data-fn="decorationSide" data-value="top"></div>
		<div class="tve-decoration-side click left" data-fn="decorationSide" data-value="left"></div>
		<div class="tve-decoration-side click right" data-fn="decorationSide" data-value="right"></div>
		<div class="tve-decoration-side click default bottom" data-fn="decorationSide" data-value="bottom"></div>
		<div class="tve-decoration-side disabled center" data-value=""></div>
	</div>
	<div class="decoration-type input">
		<select class="tve-select change tcb-base-divider-control mt-10" data-fn="chooseType">
			<option value="none"><?php echo __( 'None', 'thrive-cb' ) ?></option>
			<option value="slanted"><?php echo __( 'Slanted edge', 'thrive-cb' ) ?></option>
			<option value="pointer"><?php echo __( 'Pointer', 'thrive-cb' ) ?></option>
			<option value="divider"><?php echo __( 'Divider', 'thrive-cb' ) ?></option>
			<option value="fancy_divider"><?php echo __( 'Fancy divider', 'thrive-cb' ) ?></option>
		</select>
	</div>
</div>

<div class="tve-control tve-sub-control tcb-template-control" style="display:none"></div>
<div class="tve-control tve-sub-control tve-slanted-control" style="display:none"></div>
<div class="tve-control tve-sub-control tve-pointer-control" style="display:none"></div>
<div class="tve-control tve-sub-control tve-divider-control" style="display:none"></div>
<div class="tve-control tve-sub-control tve-fancydivider-control" style="display:none"></div>
