<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-apprentice
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden!
}
?>
<div class="tva-flex tva-flex-row tva-logs-top">
	<span><strong><?php echo __( 'Product:', 'thrive-apprentice' ) ?></strong><#- model.get('product') #></span>
	<span><strong><?php echo __( 'Type:', 'thrive-apprentice' ) ?></strong><#- model.get('type') #></span>
	<span><strong><?php echo __( 'Added:', 'thrive-apprentice' ) ?></strong><#- model.get('date') #></span>
</div>

<div class="tve-debug-table tva-logs-table"></div>
