<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-apprentice
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden!
}
?>
<div class="tva-flex tva-flex-row mb-30">
	<h1 class="tva-main-heading"><?php echo __( 'Logs', 'thrive-apprentice' ); ?></h1>
</div>

<div class="tva-flex tva-align-center mb-40">
	<div class="tva-logs-search mr-20"></div>
	<div id="tva-logs-filters" class="tva-logs-filters"></div>
</div>

<div id="tva-logs-content"></div>
<div class="tva-pagination tva-flex"></div>
