<div class="tvd-modal-content">
	<h3 class="tvd-modal-title"><?php esc_html_e( 'Warning: You are about to delete the selected topic', TVA_Const::T ); ?></h3>
	<p class="mb-0"><?php esc_html_e( 'You are about to permanently delete a topic. Are you sure you want to delete it? ', TVA_Const::T ); ?></p>
</div>

<div class="tva-modal-footer-outer">
	<button class="tva-modal-btn tvd-modal-close">
		<?php esc_html_e( 'Cancel', TVA_Const::T ); ?>
	</button>

	<button class="tva-modal-btn tva-modal-btn-red click" data-fn="performDelete">
		<?php esc_html_e( 'Delete Topic', TVA_Const::T ); ?>
	</button>
</div>
