<div class="tvd-modal-content">
	<h3 class="tvd-modal-title"><?php esc_html_e( 'Warning: You are about to delete the selected topic', 'thrive-apprentice' ); ?></h3>
	<p class="mb-0"><?php esc_html_e( 'You are about to permanently delete a topic. Are you sure you want to delete it? ', 'thrive-apprentice' ); ?></p>
</div>

<div class="tva-modal-footer-outer">
	<button class="tva-modal-btn tvd-modal-close">
		<?php esc_html_e( 'Cancel', 'thrive-apprentice' ); ?>
	</button>

	<button class="tva-modal-btn tva-modal-btn-red click" data-fn="performDelete">
		<?php esc_html_e( 'Delete Topic', 'thrive-apprentice' ); ?>
	</button>
</div>
