<div class="tcb-relative tcb-flex">
	<span class="sp-transparent click variable-square-control tcb-relative" data-fn="domEditCssVariable" data-var="<#= css_variable #>" data-type="<#=type #>" data-index="<#=index #>" data-tooltip="<#= name #>" data-side="bottom">
		<span class="tcb-icon-inline variable-square-control <#= extra_class #>" style="background-size:auto;background-image:<#= bg #>"></span>
	</span>
</div>
