<div class="control-grid full-width pb-0">
    <p class="mb-10 mt-0">
        <?php echo __( 'You can optionally add a field name to help you identify what the field is for.  This can be useful if you have multiple fields and you\'re sending the collected data via email.  The field name that you\'ve set would show in the email as opposed to something generic like "Text 1".', 'thrive-cb' ) ?>
    </p>
    <p class="m-0">
        <?php echo __( 'Field names are optional, don\'t affect the submission of data to autoresponders and are entirely for your benefit as a user.', 'thrive-cb' ); ?>
    </p>
</div>
