<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-visual-editor
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden!
}
?>
<div class="tve-avatar-picker-element thrv_wrapper tve_lg_input_container"
	 data-button-type="icon"
	 data-button-position="bottom"
	 data-icon-position="top-right"
	 data-gravatar="1"
	 data-google="1"
	 data-facebook="1"
	 data-default-avatar="<?php echo tve_editor_url( 'editor/css/images/avatar.svg' ) ?>">
	<div class="tve-avatar-picker-image" style="background-image:url(<?php echo tve_editor_url( 'editor/css/images/avatar.svg' ) ?>)">
		<input type="hidden" name="avatar-picker">
	</div>
	<button class="tve-avatar-edit-button" data-action="open-modal" data-modal-type="avatar-picker" type="button">
		<span class="tve-avatar-edit-icon">
			<svg viewBox="0 0 14 14" xmlns="http://www.w3.org/2000/svg">
				<path d="M12.01 1.813c.296.296.445.652.445 1.066 0 .414-.149.77-.446 1.066l-8.25 8.25-2.742.305a.535.535 0 0 1-.422-.188.57.57 0 0 1-.14-.445l.304-2.672L9.01.945A1.455 1.455 0 0 1 10.076.5c.414 0 .77.148 1.066.445l.867.868zm-8.766 9.304 6.14-6.14L7.978 3.57l-6.14 6.14-.188 1.595 1.594-.188zm7.968-7.969a.37.37 0 0 0 0-.539l-.867-.867a.37.37 0 0 0-.539 0L8.775 2.773 10.18 4.18l1.031-1.032z" fill-rule="nonzero"/>
			</svg>
		</span>
		<span class="tve-avatar-edit-text thrv-inline-text">
			<?php echo __( 'Manage image', 'thrive-cb' ); ?>
		</span>
	</button>
</div>
