<div class="ttd-sidebar-tab ttd-sidebar-branding scrollbar-inner">
	<h2><?php echo __( 'Branding', 'thrive-theme' ); ?></h2>
	<p class="info"><?php echo __( 'Customize the theme to match your brand', 'thrive-theme' ); ?>.</p>
	<hr/>
	<?php if ( ! empty( thrive_skin()->get_palettes() ) ): ?>
		<div id="ttd-skin-palettes-wrapper"></div>
		<hr/>
	<?php endif; ?>
	<div id="ttd-logo-wrapper"></div>
	<hr/>
	<div id="ttd-favicon-wrapper"></div>
	<hr/>
</div>
