<div class="drop-panel panel-light">
	<div class="tve-tooltip-close"><span class="click" data-fn="onCancel"><?php tcb_icon( 'exit' ) ?></span></div>
	<div class="popup-content"></div>
	<div class="action-buttons control-grid">
		<div data-fn="onCancel" class="click tve-button drop-panel-action btn-cancel"><?php echo __( 'Cancel', 'thrive-cb' ) ?></div>
		<div data-fn="onApply" class="click tve-button drop-panel-action btn-apply tve-disabled"><?php echo __( 'Apply', 'thrive-cb' ) ?></div>
	</div>
	<div class="tcb-panel-arrow"></div>
</div>
