<div class="control-grid full-width pb-0">
	<p class="mb-10 mt-0" style="font-weight: 500">
		<?php echo __( 'Custom fields unavailable', 'thrive-cb' ) ?>
	</p>
	<p class="m-0">
		<?php echo __( 'Our integration doesn\'t currently support custom fields for this autoresponder.', 'thrive-cb' ); ?>
	</p>
	<a class="blue-text mt-10" href="//thrivethemes.com/tkb_item/what-autoresponders-does-the-custom-field-integration-with-the-lead-generation-element-support/#list" target="_blank">
		<?php echo __( 'See list of autoresponders with custom field support', 'thrive-cb' ) ?>
	</a>
</div>