<?php

/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-apprentice
 */

use TVA\Reporting\Main;

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden!
}
?>
<div class="apprentice-dashboard-container">
	<div class="apprentice-top-section">
		<div>
			<h2 class="mt-0">
				<?php echo esc_html__( 'Course completions', 'thrive-apprentice' ); ?>
			</h2>

			<div class="apprentice-dashboard-wrapper no-focus">
				<?php Main::render_report( 'tve_reporting_filter', 'courses_filter' ); ?>
				<?php Main::render_report( 'tve_reporting_filter', 'users_filter' ); ?>
				<?php Main::render_report( 'tve_reporting_filter', 'date_filter' ); ?>
			</div>
		</div>
	</div>

	<div class="apprentice-info mb-20">
		<span class="tva-info-icon text-blue">
			<?php tva_get_svg_icon( 'info-circle_light' ); ?>
		</span>
		<span class="apprentice-info-text can-truncate">
			<?php echo esc_html__( 'A course is considered completed when all lessons in that course have been marked as complete. Many members may be engaged but could leave some lessons incomplete, and therefore won’t count towards completions. For more meaningful information about their progress, open the Progress and Drop-Off rate report.', 'thrive-apprentice' ); ?>
		</span>
		<span class="apprentice-info-button text-blue click" data-fn="toggleShowMore">
			<span><?php echo esc_html__( 'View more', 'thrive-apprentice' ); ?></span>
			<span><?php echo esc_html__( 'View less', 'thrive-apprentice' ); ?></span>
		</span>
	</div>

	<div class="apprentice-dashboard-wrapper">
		<div class="col-3-8">
			<?php Main::render_report( 'tve_reporting_card', 'course_completion', 'abacus', [
				'has-chart'             => 0,
				'report-size'           => 'lg',
				'report-title'          => __( 'Count', 'thrive-apprentice' ),
				'has-date-comparison'   => 1,
				'report-global-filters' => 'date',
				'report-expanded-view'  => '',
			] ); ?>
		</div>

		<div class="col-5-8">
			<?php Main::render_report( 'tve_reporting_chart', 'course_completion', 'arrow-clock', [
				'report-title'          => __( 'Over time', 'thrive-apprentice' ),
				'report-global-filters' => 'date',
				'report-expanded-view'  => '',
				'chart-config'          => [
					'cumulative-toggle' => 1,
				],
			] ); ?>

		</div>
	</div>

	<div class="apprentice-dashboard-wrapper">
		<div class="col-8-8">
			<?php Main::render_report( 'tve_reporting_table', 'course_completion', 'info', [
				'report-title'              => __( 'Details', 'thrive-apprentice' ),
				'report-group-by'           => 'date,user_id,course_id',
				'report-table-columns'      => 'date,user_id,course_id',
				'report-global-filters'     => 'date',
				'report-expanded-view'      => '',
				'has-pagination'            => 1,
				'report-items-per-page'     => 10,
				'report-order-by'           => 'date',
				'report-order-by-direction' => 'desc',
				'report-has-export'         => 1,
				'export-title'              => esc_html__( 'Course completions', 'thrive-apprentice' ),
			] ); ?>
		</div>
	</div>
</div>
