<div class="tva-opt">
	<div class="tva-label"><?php esc_html_e( 'Unlock content', 'thrive-apprentice' ); ?></div>
	<div class="tva-field">
		<#= this.renderDropdown( 'interval', <?php echo json_encode( \TVA\Drip\Schedule\Repeating::get_interval_options() ); ?> ) #>
	</div>
</div>
<# if ( this.model.get('interval') === 'days' ) { #>
<div class="tva-opt">
	<div class="tva-label"><?php esc_html_e( 'Every', 'thrive-apprentice' ); ?></div>
	<div class="tva-field tva-field-border">
		<#= this.renderDropdown( 'interval_number', <?php echo json_encode( \TVA\Drip\Schedule\Repeating::get_daily_options() ); ?>, 'data-fit-parent="1" class="tva-select-compact"' ) #>
		<div class="tva-field-suffix"><?php esc_html_e( 'day(s)', 'thrive-apprentice' ); ?></div>
	</div>
</div>
<# } else if ( this.model.get('interval') === 'weeks' ) { #>
<div class="tva-opt">
	<div class="tva-label"><?php esc_html_e( 'Every', 'thrive-apprentice' ); ?></div>
	<div class="tva-field tva-field-border tva-opt">
		<input type="number" data-field="interval_number" oninput="validity.valid||(value='');" value="<#=this.model.get('interval_number')#>" min="1" max="100">
		<div class="tva-field-suffix">
			<?php esc_html_e( 'week(s)', 'thrive-apprentice' ); ?>
		</div>
	</div>
</div>
<div class="tva-opt">
	<div class="tva-label"><?php esc_html_e( 'On which day?', 'thrive-apprentice' ); ?></div>
	<div class="tva-field">
		<#= this.renderDropdown( 'weekday', <?php echo json_encode( \TVA\Drip\Schedule\Repeating::get_weekdays( true ) ); ?> ) #>
	</div>
</div>
<# } else if ( this.model.get('interval') === 'months' ) { #>
<div class="tva-opt">
	<div class="tva-label"><?php esc_html_e( 'Every', 'thrive-apprentice' ); ?></div>
	<div class="tva-field tva-field-border tva-opt">
		<input type="number" data-field="interval_number" oninput="validity.valid||(value='');" value="<#=this.model.get('interval_number')#>" min="1" max="100">
		<div class="tva-field-suffix">
			<?php esc_html_e( 'month(s)', 'thrive-apprentice' ); ?>
		</div>
	</div>
</div>
<?php include plugin_dir_path( __FILE__ ) . '_monthly-fields.phtml'; ?>
<# } #>

