<div class="tvd-row">
    <div class="tvd-col tvd-s3">
        <# if(url) { #>
            <a href="<#- url #>" class="tvd-break-word"><#- name #></a>
        <# } else { #>
            <span  class="tvd-break-word">
                <#- name #>
            </span>
        <# } #>
    </div>
    <div class="tvd-col tvd-s3">
        <#- type #>
    </div>
    <div class="tvd-col tvd-s3">
        <#- conversions #>
    </div>
    <div class="tvd-col tvd-s3">
        <#- leads #>
    </div>
</div>
