<ul class="tvd-collection tvd-with-header" id="tve-table-items">
    <li class="tvd-collection-header">
        <div class="tvd-row">
            <div class="tvd-col tvd-s3">
                <div class="tvd-truncate-on-small" data-popup="<?php echo __('Source', 'thrive-leads'); ?>">
                    <h5 class="tvd-truncate-on-small-el"><?php echo __('Source', 'thrive-leads'); ?></h5>
                </div>
            </div>
            <div class="tvd-col tvd-s3">
                <div class="tvd-truncate-on-small" data-popup="<?php echo __('Type', 'thrive-leads'); ?>">
                    <h5 class="tvd-truncate-on-small-el"><?php echo __('Type', 'thrive-leads'); ?></h5>
                </div>
            </div>
            <div class="tvd-col tvd-s3">
                <div class="tvd-truncate-on-small" data-popup="<?php echo __('Conversions', 'thrive-leads'); ?>">
                    <h5 class="tvd-truncate-on-small-el tve-table-sortable" data-order-by="conversions"><?php echo __('Conversions', 'thrive-leads'); ?><span class="<#=  this.pagination.order_by && this.pagination.order_by == 'conversions' && this.pagination.order_dir == 'ASC' ? 'tvd-icon-collapsed' : 'tvd-icon-expanded' #>"></span></h5>
                </div>
            </div>
            <div class="tvd-col tvd-s3">
                <div class="tvd-truncate-on-small" data-popup="<?php echo __('New Leads', 'thrive-leads'); ?>">
                    <h5 class="tvd-truncate-on-small-el tve-table-sortable" data-order-by="leads"><?php echo __('New Leads', 'thrive-leads'); ?><span class="<#=  this.pagination.order_by && this.pagination.order_by == 'leads' && this.pagination.order_dir == 'ASC' ? 'tvd-icon-collapsed' : 'tvd-icon-expanded' #>"></span></h5>
                </div>
            </div>
        </div>
    </li>
</ul>
