<div class="api-field">
	<div class="field-description">
		<?php echo __( 'Choose your mailing list', 'thrive-cb' ); ?>
	</div>

	<div class="control-grid">
		<select class="api-list change" data-fn="setupChange" data-name="list">
			<# _.each(api.get('lists'), function(item) { #>
			<#= TVE.tpl( 'util/option', {value:item.id, selected: (api.getConfig('list')==item.id), text: item.name}) #>
			<# } ) #>
		</select>

		<span class="click tve-refresh-api-list" data-fn="forceGet" data-tooltip="<?php echo __( 'Refresh', 'thrive-cb' ); ?>" data-side="top"> <?php tcb_icon( 'redo-regular' ) ?></span>
	</div>
</div>
<div class="api-field">
	<div class="field-description">
		<?php echo __( 'Cycle day:', 'thrive-cb' ); ?>
	</div>
	<div class="tvd-input-field">
		<input id="get-response-cycleday" type="number" max="103" min="0" class="tve-api-extra"
			   name="cycleday" value="<#= api.getConfig('cycleday') ? api.getConfig('cycleday') : '0' #>"/>
	</div>
	<div class="field-description"><?php echo __( 'Number of the cycle day(between 0 and 103)', 'thrive-cb' ) ?></div>
</div>
