<div class="tve-drag-image-wrapper">
	<div class="tve-drag-image tve-drag-image-overlay"></div>
	<div class="tve-drag-image tve-drag-image-handle" data-key="default">
		<?php tcb_icon( 'arrows-alt-regular' ) ?>
		<span><?php echo __( 'Drag to Reposition', 'thrive-cb' ) ?></span>
	</div>

	<div class="tve-drag-image tve-drag-image-handle" data-key="height">
		<?php tcb_icon( 'arrows-alt-v-regular' ) ?>
		<span><?php echo __( 'Move Up or Down to Reposition', 'thrive-cb' ) ?></span>
	</div>
	<div class="tve-drag-image tve-drag-image-handle" data-key="width">
		<?php tcb_icon( 'arrows-alt-h-regular' ) ?>
		<span><?php echo __( 'Move Left or Right to Reposition', 'thrive-cb' ) ?></span>
	</div>
</div>