<div class="tve-login-form-item tcb-no-clone tcb-no-delete tcb-no-save tve_lg_input_container">
	<div class="thrv-form-input-wrapper tcb-no-clone tcb-no-delete tcb-no-save" data-type="<#= config.type #>">
		<div class="thrv_wrapper tcb-label tcb-removable-label thrv_text_element tcb-no-delete tcb-no-save tcb-no-clone tve_no_drag"
		<#= config.showLabel ? '' : ' style="display: none"'#>>
		<div class="tcb-plain-text"><#-label #></div>
	</div>
	<div class="tve_lg_textarea tve_lg_regular_input tcb-plain-text tve-login-form-input">
		<textarea class="tcb-plain-text" rows="3" data-min="10" maxlength="350" data-required="1"></textarea>
		<div class="thrv_wrapper thrv_text_element tve-lg-textarea-counter">
			<div class="tcb-plain-text"><span class="tve-fill-text-dynamic" contenteditable="false">0 of 350</span></div>
		</div>
	</div>
</div>
</div>
