<div class="tcb-dynamic-color-container">
	<span>
		<?php echo __( 'If not available, use this default color:', 'thrive-cb' ); ?>
	</span>
	<span class="tcb-default-dynamic-color">
		<span class="sp-transparent click" style="margin-right: 6px;float: right;background-size: 0px;" data-fn="edit_default_color" data-default-dynamic="<#=dynamicVar#>">
			<span class="tcb-icon-inline" style="background-color: <#= color #>;background-size:4px"></span>
		</span>
	</span>
</div>
