<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-apprentice
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden!
}
?>

<select class="change" data-fn="selectChange">
	<option value=""><?php echo __( 'Select an option', TVA_Const::T ); ?></option>
</select>

<button class="tva-btn tva-btn-blue click" data-fn="refreshData"><?php echo __( 'Button', TVA_Const::T ); ?></button>
