<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-apprentice
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden!
}
$breadcrumbs_config = array(
	array(
		'title' => __( 'Quick Start Guide', 'thrive-apprentice' ),
		'route' => 'sendowl/quick-start',
	),
	array(
		'title' => __( 'Purchase Links', 'thrive-apprentice' ),
	),
);

$options = array(
	'products' => array(
		'title'                 => __( 'Product', 'thrive-apprentice' ),
		'icon'                  => 'so-products',
		'option_button_label'   => __( 'Refresh Products List', 'thrive-apprentice' ),
		'discount_button_label' => __( 'Refresh Discount List', 'thrive-apprentice' ),
		'query_string'          => 'pid',
	),
	'bundles'  => array(
		'title'                 => __( 'Bundle', 'thrive-apprentice' ),
		'icon'                  => 'so-bundle',
		'option_button_label'   => __( 'Refresh Bundles List', 'thrive-apprentice' ),
		'discount_button_label' => __( 'Refresh Discount List', 'thrive-apprentice' ),
		'query_string'          => 'bid',
	),
);

?>
<div class="tva-flex tva-flex-row mb-30">
	<h1 class="tva-main-heading"><?php echo __( 'Purchase Links', 'thrive-apprentice' ); ?></h1>
</div>
<?php include 'breadcrumbs.phtml'; ?>
<div class="tva-flex tva-flex-column mt-30">
	<# if ( !! TVA.settings.checkout_page.value === false ) { #>
	<p>
		<?php echo __( 'You haven\'t set up your checkout page yet! In order to get your correct Purchase Links you need to set up your Checkout Page', 'thrive-apprentice' ); ?>
		<a href="#settings/sendowl/checkout"><?php echo __( 'Here', 'thrive-apprentice' ) ?></a>.
	</p>
	<# } #>
	<p class="sendowl-p"><?php echo __( 'Use the link generator below to get purchase links for any of your SendOwl products or bundles. ', 'thrive-apprentice' ) ?>
		<a data-source="ZIMIJybwMrU" class="tvd-open-video">
			<?php echo __( 'Click here to see video instructions on how to use these links.', 'thrive-apprentice' ); ?>
		</a>
	</p>
</div>
<div class="tva-flex tva-purchase-top mb-20">
	<div>
		<div class="tva-card tva-purchase-card">
			<p><?php echo __( 'Would you like to generate a purchase link for a product or a bundle?', 'thrive-apprentice' ); ?></p>

			<?php foreach ( $options as $key => $option ) : ?>
				<div class="click tva-colored-card tva-so-options" data-fn="selectOption"
					 data-option="<?php echo $key; ?>"
					 data-query-string="<?php echo $option['query_string']; ?>"
					 data-option-button-label="<?php echo esc_html( $option['option_button_label'] ); ?>"
					 data-option-discount-label="<?php echo esc_html( $option['discount_button_label'] ); ?>">
					<?php tva_get_svg_icon( $option['icon'] ); ?>
					<p><?php echo $option['title']; ?></p>
				</div>
			<?php endforeach; ?>
		</div>
	</div>
	<div class="tva-option-content"></div>
	<div class="tva-discount-content"></div>
</div>
<div class="tva-links-content mt-20"></div>
