<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-university
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}
?>

<div class="tva-purchase-empty tva-flex tva-flex-column tva-align-center">
	<h3><?php echo __( 'No Bundles Found', 'thrive-apprentice' ) ?></h3>

	<p class="mb-0">
		<?php echo __( 'We managed to connect to your SendOwl account but didn\'t find any bundles.', 'thrive-apprentice' ) ?>
		<br>
		<a href="https://thrivethemes.com/tkb_item/no-sendowl-products-bundles-found-what-to-do/" target="_blank">
			<?php echo __( 'Click here to troubleshoot', 'thrive-apprentice' ) ?>
		</a>
	</p>
</div>
