<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-university
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}
?>

<p><?php echo __( 'This is the page where your customer will register for your product by creating their user account', 'thrive-apprentice' ); ?></p>

<p>
	<?php
	$url_txt = __( ' Learn more about the registration page', 'thrive-apprentice' );
	$url     = 'PjnAFb-uhIk';
	$href    = '<a data-source="' . $url . '" class="tvd-open-video"> %s </a>';

	echo sprintf( $href, $url_txt );
	?>
</p>

<div class="tva-so-checkout-reg"></div>
