<?php
/**
 * Created by PhpStorm.
 * User: Ovidiu
 * Date: 12/11/2018
 * Time: 2:02 PM
 */

/**
 * Used in:
 * editor/js/main/views/controls/global/style-picker.js
 * editor/js/main/views/controls/global/style-panel.js
 */
?>

<div class="thrv_wrapper thrv-page-section <#= cls #>">
	<div class="tve-page-section-out <#= cls #>-out"></div>
	<div class="tve-page-section-in <#= cls #>-in tve_empty_dropzone"></div>
</div>
<# if(text.length > 0){ #>
<p><#= text #></p>
<# } #>

