<?php
/**
 * Created by PhpStorm.
 * User: ovidiu
 * Date: 9/30/2018
 * Time: 4:26 PM
 */
?>
<div class="row middle-xs">
	<div class="col-xs-12">
		<span id="global-style-desc"></span>&nbsp;<a href="https://thrivethemes.com/tkb_item/how-to-use-the-shared-styles-feature/" target="_blank"><?php tcb_icon( 'info' ); ?></a>
	</div>
	<style id="global-style-preview-css"></style>
	<div id="global-style-preview-html" class="global-style-preview col-xs-12"></div>
	<div class="col-xs-12">
		<input type="text" id="global-style-name"/>
	</div>
</div>
