<div class="tvd-card tvd-medium-xxsmall tvd-card-new tvd-valign-wrapper tvd-relative tqb-new-button tvd-tooltipped"
	 data-tooltip="<?php echo __( 'Optional: Create a customizable image that will lead to more shares', 'thrive-quiz-builder' ); ?>"
	 data-position="top">
	<a href="<#= item && item.get('editor_url') ? item.get('editor_url') : 'javascript:void(0)' #>" id="tqb-add-badge" class="tvd-card-content tvd-valign tvd-center-align">
		<i class="tqb-new-social-badge"></i>
		<h4 class="tqb-new-button-header-text">
			<?php echo __( 'Create a Social Share Badge', 'thrive-quiz-builder' ); ?>
		</h4>
	</a>
</div>
