<div class="tvd-card tvd-red" tabindex="-1">
	<div class="tvd-card-content">
		<h4 class="tvd-margin-top tqb-center-text-in-card">
			<?php echo __( 'Are you sure you want to delete the badge?', 'thrive-quiz-builder' ) ?>
		</h4>
	</div>
	<div class="tvd-card-action">
		<div class="tvd-row">
			<div class="tvd-col tvd-s12 tvd-m6">
				<a class="tvd-btn-flat tvd-btn-flat-secondary tvd-btn-flat-light tvd-left tqb-delete-yes">
					<?php echo __( 'Yes, delete', 'thrive-quiz-builder' ) ?>
				</a>
			</div>
			<div class="tvd-col tvd-s12 tvd-m6">
				<a class="tvd-btn-flat tvd-btn-flat-primary tvd-btn-flat-light tvd-right tqb-delete-no">
					<?php echo __( 'No, keep it', 'thrive-quiz-builder' ) ?>
				</a>
			</div>
		</div>
	</div>
</div>
