<div class="no-search-results" style="display: none;">
	<?php echo __( "Oups! We couldn't find anything called " ) ?><span class="search-word"><#= message #></span><?php echo __( '. Maybe search for something else ?' ); ?>
</div>
<div class="no-sections-on-site">
	<?php echo __( "You don't have any " ) ?><span class="section-type"><#= type #></span><?php echo __( ' created on the site' ) ?>
</div>
<div class="no-sections-on-cloud">
	<?php echo __( "For the moment we don't have any " ) ?><span class="section-type"><#= type #></span><?php echo __( ' created' ) ?>
</div>
