<div class="conditional-display-wrapper">
	<div class="current-display"><#= name #></div>
	<div class="conditional-display-list" style="display:none"></div>

	<div class="tcb-i-wrapper">
		<div class="click tcb-i" data-fn="toggleDisplayDropdown"><#= dropdownIcon #></div>
		<div class="click tcb-i" data-key="" data-fn="resetDisplay"><#= resetIcon #></div>
		<div class="click tcb-i" data-key="" data-fn="toggleVisibility"><#= visibilityIcon #><#= hiddenIcon #></div>
		<div class="click tcb-i" data-key="" data-fn="duplicateDisplay"><#= duplicateIcon #></div>
		<div class="click tcb-i" data-key="" data-fn="openConditionsModal"><#= openModalIcon #></div>
	</div>
</div>

<div class="click tcb-i conditional-display-small" data-fn="toggleSmallOptions"><#= smallOptionsIcon #></div>

