<# if ( this.model.isDefault() ) { #>
<div class="template-top-label"><#= this.model.getDefaultLabel() #></div>
<# } #>
<div class="template-upper" style="<#= this.model.hasThumbnail() ? this.model.getThumbnailCss() : ''  #>">

	<# if ( ! this.model.hasThumbnail() ) { #>
	<div class="template-icon">
		<#= this.model.icon() #>
	</div>
	<# } #>

	<button class="template-edit-button">
		<a target="_blank" href="<#= this.model.get('edit_url') #>">
			<?php Thrive_Views::svg_icon( 'pen-light' ); ?>
			<span><?php echo __( 'Edit', 'thrive-theme' ); ?></span>
		</a>
	</button>
</div>

<div class="template-lower">
	<div class="template-name-container">
		<#= this.model.icon() #>
		<span class="template-name"><#= this.model.name() #></span>
	</div>
	<span class="ttd-dropdown-dots click" data-fn="showOptionsTooltip">
		<?php Thrive_Views::svg_icon( 'icon-three-dots' ); ?>
	</span>
	<div class="template-meta">
		<ul>
			<li>
				<span class="template-label"><?php echo __( 'Layout', 'thrive-theme' ); ?></span>
				<span class="template-meta-val"><#= this.model.getLayoutName() #></span>
			</li>
			<li>
				<span class="template-label"><?php echo __( 'Content Type', 'thrive-theme' ); ?></span>
				<span class="template-meta-val"><#= this.model.getContentType() #></span>
			</li>
			<li>
				<span class="template-label"><?php echo __( 'Single or List', 'thrive-theme' ); ?></span>
				<span class="template-meta-val"><#= this.model.getType() #></span>
			</li>
		</ul>
	</div>
</div>
