<div class="ttd-a-fresh-start ttd-main-wrapper">

	<div class="ttd-page-title">
		<?php echo __( 'Your Theme Templates', 'thrive-theme' ); ?>
	</div>

	<div class="ttd-settings-container">

		<div class="ttd-sep"></div>

		<button class="ttd-normal-button click" data-fn="addPageTemplate">
			<?php Thrive_Views::svg_icon( 'plus-solid' ); ?>
			<span><?php echo __( 'Add New', 'thrive-theme' ); ?></span>
		</button>
	</div>

	<div class="ttd-templates-area single-container">
		<div class="ttd-templates-header">
			<h2><?php echo __( 'Single Content Templates', 'thrive-theme' ); ?></h2>
			<p><?php echo __( 'Used to display individual posts, pages etc.', 'thrive-theme' ); ?></p>
		</div>

		<div class="ttd-templates-inner single"></div>
	</div>

	<div class="ttd-templates-area list-container">
		<div class="ttd-templates-header">
			<h2><?php echo __( 'List Templates', 'thrive-theme' ); ?></h2>
			<p><?php echo __( 'Used to display list pages like search results, your blog feed, etc.', 'thrive-theme' ); ?></p>
		</div>

		<div class="ttd-templates-inner list"></div>
	</div>
</div>
