<span class="input-um click" tabindex="2">px</span>
<input type="text" class="tve-input input change width-input has-um" data-fn="change_value" data-fn-input="on_input">
<div class="um-wrapper">
	<span class="tve-input-um mousedown active" data-fn="change_uom" data-value="px">px</span>
	<span class="tve-input-um mousedown" data-fn="change_uom" data-value="%">%</span>
	<span class="tve-input-um mousedown" data-fn="change_uom" data-value="vw">vw</span>
	<span class="tve-input-um mousedown" data-fn="change_uom" data-value="vh">vh</span>
</div>
<a href="javascript:void(0)" class="input-clear click" data-fn="clear_value" data-width="fluid"
		data-tooltip="<?php echo __( 'Change Size to Auto', 'thrive-cb' ); ?>"><?php tcb_icon( 'times-light' ); ?></a>