<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-apprentice
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden!
}
?>
<span><?php echo esc_html__( 'Are you sure you want to delete this rule?', TVA_Const::T ); ?></span>
<a class="click" data-fn="cancel"><?php echo esc_html__( 'No, cancel', TVA_Const::T ); ?></a>
<a class="click" data-fn="confirm"><?php echo esc_html__( 'Yes, delete', TVA_Const::T ); ?></a>
