<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-apprentice
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden!
}
?>
<div>
	<h3><?php _e( 'Add new content set', 'thrive-apprentice' ); ?></h3>
</div>
<div class="tvd-content-set-inner">
	<div>
		<input class="mb-30" id="tvd-content-set-name" placeholder="<?php echo __( 'Content set name', 'thrive-apprentice' ) ?>" type="text"
			   value="<#= model.get('post_title') #>">
	</div>
	<div>
		<h4><?php _e( 'What content should be part of this set?', 'thrive-apprentice' ); ?></h4>
	</div>
	<div id="tvd-content-set-rules"></div>
	<div id="tvd-content-set-add-rule"></div>
</div>

<div class="tvd-content-sets-footer tva-flex tva-flex-row tva-space-between tva-align-center">
	<button class="click tva-empty-btn-back ml-30" data-fn="back">
		<?php echo __( 'Back', 'thrive-apprentice' ); ?>
	</button>
	<button class="click" data-fn="saveContentSet">
		<?php echo __( 'Save content set', 'thrive-apprentice' ); ?>
	</button>
</div>
