<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-apprentice
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden!
}
?>
<div>
	<h3><?php _e( 'Content sets', 'thrive-apprentice' ); ?></h3>
</div>

<div class="tva-flex tva-align-center tva-space-between mb-20">
	<input type="text" class="tva-filter-sets input" data-fn="filterSets" placeholder="<?php esc_html_e( 'Filter content sets', 'thrive-apprentice' ); ?>"/>
	<a href="javascript:void(0)" class="click tvd-tss-add-new-field tva-btn tva-btn-blue" data-fn="addSet">
		<?php tva_get_svg_icon( 'add-btn' ); ?>
		<span><?php _e( 'Create new', 'thrive-apprentice' ); ?></span>
	</a>
</div>
<p class="col-dark mt-30 mb-5"><?php _e( 'Select content sets that you want to add to your product', 'thrive-apprentice' ); ?></p>
<div class="tvd-content-sets-list"></div>
<div class="tvd-content-sets-list-pagination"></div>
<div class="tvd-content-sets-footer tva-flex tva-align-center tva-space-between">
	<button class="click" data-fn="saveAndClose">
		<?php echo __( 'Save and close', 'thrive-apprentice' ); ?>
	</button>
</div>
