<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-visual-editor
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}
?>
<div class="horizontal ctrl no-space input-small" data-style="left" data-label="<?php echo __( 'Horizontal', 'thrive-cb' ); ?>"></div>
<div class="vertical ctrl no-space input-small" data-style="top" data-label="<?php echo __( 'Vertical', 'thrive-cb' ); ?>"></div>