<div class="tva-drip-date">
	<div class="tva-opt">
		<div class="tva-label"><?php esc_html_e( 'Unlock if date/time', 'thrive-apprentice' ); ?></div>
		<select data-bind="occurrence">
			<option value="after"><?php esc_html_e( 'is after', 'thrive-apprentice' ); ?></option>
			<option value="before"><?php esc_html_e( 'is before', 'thrive-apprentice' ); ?></option>
		</select>
	</div>
	<div class="tva-trigger-schedule"></div>
</div>
