<div class="tve-landing-page-text-preview tve-remove-auxiliary-content canvas-mode">
	<div class="tve-border-radius">
		<div class="tve-landing-page-text-controls">
			<div class="tve_left tcb-element-title"><?php echo __( 'All Elements', 'thrive-cb' ) ?></div>
			<div id="tcb-close-lp-fonts-icon" class="tve_right tcb-close-lp-fonts"></div>
		</div>
		<div id="tcb-fonts-all-texts-wrapper">
			<?php tcb_template( 'typography.phtml', null, false, 'backbone' ); ?>
		</div>
	</div>
	<div class="tcb-panel-right">
		<button id="tcb-close-lp-fonts-btn" class="tcb-btn-green tcb-close-lp-fonts"><?php echo __( 'Close', 'thrive-cb' ) ?></button>
	</div>
</div>
