<div class="control-grid">
	<label class="label"><?php echo __( 'Source', 'thrive-cb' ) ?></label>
	<select class="v-source change input" data-fn="show_section">
		<option value=""><?php echo __( 'Select source', 'thrive-cb' ) ?></option>
		<option value="youtube">YouTube</option>
		<option value="vimeo">Vimeo</option>
		<option value="wistia">Wistia</option>
		<option value="external"><?php echo __( 'Externally Hosted Video', 'thrive-cb' ) ?></option>
		<option value="custom"><?php echo __( 'Uploaded Video', 'thrive-cb' ) ?></option>
		<option value="vooplayer">VooPlayer/SpotLightr</option>
	</select>
</div>
<div class="v-settings" style="display:none" id="v-settings-youtube" data-view="Youtube"><?php tcb_template( 'actions/video-popup/youtube' ) ?></div>
<div class="v-settings" style="display:none" id="v-settings-vimeo" data-view="Vimeo"><?php tcb_template( 'actions/video-popup/vimeo' ) ?></div>
<div class="v-settings" style="display:none" id="v-settings-wistia" data-view="Wistia"><?php tcb_template( 'actions/video-popup/wistia' ) ?></div>
<div class="v-settings" style="display:none" id="v-settings-external" data-view="External"><?php tcb_template( 'actions/video-popup/external' ) ?></div>
<div class="v-settings" style="display:none" id="v-settings-custom" data-view="Custom"><?php tcb_template( 'actions/video-popup/custom' ) ?></div>
<div class="v-settings" style="display:none" id="v-settings-vooplayer" data-view="VooPlayer"><?php tcb_template( 'actions/video-popup/vooplayer' ) ?></div>
