<div class="line-margin">
	<div class="m-handle top" data-side="top">
		<div class="m-value"><span class="value"></span><span class="uom"></span></div>
	</div>
	<div class="m-preview flex-mid"><?php echo esc_html__( 'Line Spacing', 'thrive-cb' ); ?></div>
	<div class="m-handle bottom" data-side="bottom">
		<div class="m-value"><span class="value"></span><span class="uom"></span></div>
	</div>
</div>