<div class="custom-html-extra" id="tl-custom-html-opts" style="display: none">
	<h6><?php echo __( 'When should we load this snippet?', 'thrive-leads' ); ?></h6>
	<div class="main-text">
		<?php echo __( "You’ve added this custom HTML element inside a Thrive Leads state. Please tell us when you want the code you've pasted below to be executed.", 'thrive-leads' ); ?>
		<a href="https://thrivethemes.com/tkb_item/when-to-load-an-html-code-to-track-conversions/" target="_blank"><?php echo __( 'What does this mean?', 'thrive-leads' ); ?></a>
	</div>

	<div>
		<small><?php echo __( 'Choose the moment', 'thrive-leads' ); ?></small>
		<br>
		<select id="custom-html-lazy-load">
			<option value=""><?php echo __( 'On page load', 'thrive-leads' ); ?></option>
			<option value="lazy"><?php echo __( 'When the visitor views the state', 'thrive-leads' ); ?></option>
		</select>
	</div>
</div>