<?php
/** @var $tva_links array */
?>
<div id="ta-nav-menu-links" class="ta-nav-menu-links-div">
	<div id="ta-nav-menu-links-list" class="tabs-panel tabs-panel-active">
		<ul id="ta-link-checklist" class="categorychecklist form-no-clear">
			<?php foreach ( $tva_links as $item ): ?>
				<li>
					<label class="menu-item-title">
						<input type="checkbox" class="menu-item-checkbox" data-link="<?php echo $item['link']; ?>" data-slug="<?php echo $item['slug']; ?>">
						<?php echo $item['label']; ?>
					</label>
				</li>
			<?php endforeach; ?>
		</ul>
	</div>
	<p class="button-controls wp-clearfix">
	<span class="add-to-menu">
		<input type="submit" class="button submit-add-to-menu right" value="Add to Menu" name="add-custom-menu-item" id="submit-ta-links"/>
		<span class="spinner"></span>
	</span>
	</p>
</div>
