<div class="mt-10 tcb-hidden global-edit-warning" id="global-gradient-edit-warning">
	<span id="global-gradient-edit-msg"><?php echo __( 'Careful, you are editing a global gradient.', 'thrive-cb' ); ?></span>
	<a href="https://thrivethemes.com/tkb_item/how-to-use-the-global-gradients-feature/#globalgradient_edit" target="_blank"><?php echo __( 'Learn more', 'thrive-cb' ); ?></a>
</div>
<div class="mt-6">
	<span class="click open color-menu-item tcb-favorites-toggle-control" data-dropdown-base-selector=".tcb-favorites-toggle-" data-fn="toggleGradientDropdown">
		<i></i> <?php echo __( 'My Gradients', 'thrive-cb' ); ?>
	</span>
</div>
<div class="tcb-favorites-toggle-content">
	<div id="gradient-details"></div>
	<div id="add-gradient"></div>
	<div class="saved-gradients-container mt-5"></div>
</div>
