<div class="tvd-modal-content">
	<h3 class="tvd-modal-title">
		<?php echo sprintf( __( '%s - display settings', 'thrive-ult' ), "<#= model.get( 'post_title' ) #>" ) ?>
		<?php tve_ult_video( 'YYOw8BGkm4g' ) ?>
	</h3>
	<div id="tvu-leads-options-container">
		<div class="control-grid flex-start">
			<div class="tvd-input-field w-200 mr-30">
				<select class="tvu_leads_saved_options tvd-select2" id="tvu_load_template" data-field="load_template" data-placeholder="<?php echo __( 'Current selection', 'thrive-ult' ) ?>">
					<option value=""></option>
				</select>
				<label for="tvu_load_template"></label>
			</div>
			<button class="tvu_leads_load_saved_options tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-green tvd-full-btn w-200"><?php echo __( 'Load Saved Options', 'thrive-ult' ) ?></button>
		</div>
		<div id="tve-message-container">
			<div class="error">
				<?php
				$cache_plugin = tve_dash_detect_cache_plugin();

				$message = $cache_plugin
					? sprintf( __( 'After saving these settings, the cache data from %s plugin will be automatically cleared (this is required each time you make a change to these settings)', 'thrive-ult' ), '<strong>' . $cache_plugin . '</strong>' )
					: sprintf( __( 'If you have a caching plugin installed (such as %1$sW3 Total Cache%2$s or %1$sWP Super Cache%2$s), please clear the cache after modifying these settings', 'thrive-ult' ), '<strong>', '</strong>' );
				?>
				<p><?php echo $message ?></p>
			</div>
		</div>
		<div class="tvd-v-spacer vs-2"></div>
		<h4>
			<?php echo __( 'Display Logic', 'thrive-ult' ); ?>
			<span class="inclusions-count">(0)</span>
		</h4>
		<p><?php echo __( 'Use these settings to configure where the campaign should be displayed:', 'thrive-ult' ) ?></p>
		<div id="show_options"></div>
		<div class="tvd-v-spacer vs-3"></div>
		<h4 data-target="#exclusions_wrapper" class="tl-clickable tl-toggle-tab-display collapsed tvd-pointer">
			<span><?php echo __( "Exclusions", 'thrive-ult' ); ?></span>
			<span class="exclusions-count">(0)</span>
		</h4>
		<div class="tvd-relative">
			<div id="exclusions_wrapper" class="tvd-not-visible">
				<p><?php echo __( 'Use these settings to configure where the campaign should be HIDDEN. Attention! This will override the display logic above', 'thrive-ult' ) ?></p>
				<div id="hide_options"></div>
			</div>
		</div>
		<div class="tvd-v-spacer vs-3"></div>
		<div class="tvu_leads_tabs_content tvu_leads_clearfix" style="display: block">
			<div class="tvd-row tvd-collapse">
				<div class="tvd-col tvd-s12">
					<h4><?php echo __( 'Save as Template', 'thrive-ult' ); ?></h4>
					<p><?php echo __( "You can save the display configuration that you've created if you'd like a template to re-use with other campaigns.", 'thrive-ult' ); ?></p>
				</div>
			</div>
			<div class="tvd-row tvd-collapse">
				<div class="tvd-col tvd-l3 tvd-s4">
					<div class="tvd-input-field">
						<input class="tvu_leads_left tvd-skip-modal-save" type="text" name="tvu_leads_new_template_name" id="tvu_leads_new_template_name"/>
						<label for="tvu_leads_new_template_name"
							   data-error="<?php echo __( 'Template name is required', 'thrive-ult' ) ?>"><?php echo __( 'Template name', 'thrive-ult' ); ?></label>
					</div>
				</div>
				<div class="tvd-col tvd-l3 tvd-s4">
					<button
							class="tvu_leads_add_new_template tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-green"><?php echo __( 'Save Display Template', 'thrive-ult' ); ?></button>
				</div>
			</div>
		</div>
		<div class="clearfix"></div>
	</div>
</div>
<div class="tvd-modal-footer control-grid">
	<button class="tvd-btn-flat tvd-btn-flat-secondary tvd-btn-flat-dark tvd-modal-close tvd-waves-effect"><?php echo __( 'Cancel', 'thrive-ult' ); ?></button>
	<button class="tvu_leads_save_widget_options tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-green tvd-right"><?php echo __( 'Save & close', 'thrive-ult' ); ?></button>
</div>
<a href="javascript:void(0)" class="tvd-modal-action tvd-modal-close tvd-modal-close-x"><i class="tvd-icon-close2"></i></a>
