
<div class="objectcache:widget objectcache:adaptive-widget objectcache:flushlog-widget">
    <p>
        Run a cache scan to see a list of keys and their read/write-ratio.
        This may take a while.
    </p>

    <div class="actions">
        <div>
            <button class="button button-primary" data-text="Scan keys" data-loading="Scanning...">
                Scan keys
            </button>
        </div>
    </div>
</div>
