<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-dashboard
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}
?>

<div class="tvd-tss-field-data">
	<label for="tvd-tss-field-name"><?php echo __( 'Field Name', 'thrive-dash' ) ?> *</label>
	<div class="tvd-input-field">
		<input id="tvd-tss-field-name" autocomplete="email" class="input-change <#= model.get( 'default_field' )? 'tvd-disabled tvd-no-focus' : '' #>" type="text" value="<#= model.get('name') #>"
			   data-field="name"
			   placeholder="<?php echo __( 'Email address', 'thrive-dash' ) ?>">
		<label></label>
	</div>
</div>

<div class="tvd-tss-field-data">
	<label for="tvd-tss-field-email"><?php echo __( 'Email Address', 'thrive-dash' ) ?> *</label>
	<div class="tvd-input-field">
		<input id="tvd-tss-field-email" autocomplete="email-input" class="input-change" type="text" value="<#= model.get('data').email ? model.get('data').email : '' #>" data-field="data_email" placeholder="<?php echo __( 'email@someexample.com', 'thrive-dash' ) ?>">
		<label></label>
	</div>
</div>
