<div class="control-grid full-width pb-0">
	<span>
		<?php echo esc_html__( 'Featured content sits above the main post list element and can be used to highlight important posts.', 'thrive-cb' ); ?>
	</span>
	<a href="https://thrivethemes.com/tkb_item/how-to-use-the-featured-content-option-of-the-post-list-element" class="blue-text mt-5" target="_blank">
		<?php echo esc_html__( 'Learn more about this feature', 'thrive-cb' ); ?>
	</a>
</div>