<div class="tvd-modal-content tvd-modal-add-edit-script">
	<h4 class="tvd-modal-title"><#= message #></h4>
	<a href="javascript:void(0)"
	   class="tvd-modal-action tvd-modal-close tvd-modal-close-x">
		<i class="tvd-icon-close2"></i>
	</a>
	<form class="">
		<div class="tvd-row">
			<div class="tvd-sm-form-element clearfix">
				<label for="tvd-sm-script-code">
					<?php echo __( 'Script', 'thrive-dash' ) ?>
				</label>
				<textarea id="tvd-sm-script-code"><#= typeof(this.model) !== 'undefined' ? this.model.get('code'):''#></textarea>
			</div>

			<div id="tvd-sm-code-empty" class="tvd-sm-input-error" hidden>
				<?php echo __( 'Required field!', 'thrive-dash' ); ?>
			</div>

			<div id="tvd-sm-code-invalid" class="tvd-sm-input-error" hidden>
				<?php echo __( 'Invalid code!', 'thrive-dash' ); ?>
			</div>

			<div class="tvd-sm-form-element">
				<label class="tvd-sm-script-name" for="tvd-sm-script-name"><?php echo __( 'Script Label', 'thrive-dash' ) ?></label>
				<input id="tvd-sm-script-name" type="text" value="<#= typeof(this.model) !== 'undefined' ? this.model.get('label') : '' #>">
			</div>

			<div id="tvd-sm-label-empty" class="tvd-sm-input-error no-space-top" hidden>
				<?php echo __( 'Required field!', 'thrive-dash' ); ?>
			</div>

			<div class="tvd-sm-form-element">
				<label class="tvd-sm-script-placement" for="tvd-sm-script-placement"><?php echo __( 'Placement', 'thrive-dash' ) ?></label>
				<select id="tvd-sm-script-placement">
					<option value="" disabled selected hidden><?php echo __( 'Choose placement', 'thrive-dash' ) ?></option>
					<# _.each(TVD_SM_CONST.script_placement_text, function(value,key){ #>
					<option value="<#= key #>"
					<#= (typeof(this.model) !== 'undefined') && (key === this.model.get('placement')) ? "selected" : "" #>
					>
					<#= value #>
					</option>
					<# }, this); #>

				</select>
			</div>

			<div id="tvd-sm-placement-empty" class="tvd-sm-input-error no-space-top" hidden>
				<?php echo __( 'Required field!', 'thrive-dash' ); ?>
			</div>

			<div class="tvd-sm-form-element tvd-sm-location" style="<#= TVD_SM_CONST.is_ttb_active && TVD_SM_CONST.is_tar_active ? '' : 'display:none' #>">
				<label class="tvd-sm-script-location"><?php echo __( 'Inserted in', 'thrive-dash' ) ?></label>
				<input id="tvd-sm-script-checkbox-ttb" type="checkbox" <#= typeof(this.model) !== 'undefined' ? (this.model.get('status').ttb ? 'checked' : '') : '' #>>
				<label for="tvd-sm-script-checkbox-ttb" class="tvd-sm-checkbox"> <?php echo __( 'Thrive Themes', 'thrive-dash' ); ?> </label>

				<input id="tvd-sm-script-checkbox-lp" type="checkbox" <#= typeof(this.model) !== 'undefined' ? (this.model.get('status').lp ? 'checked' : '') : '' #>>
				<label for="tvd-sm-script-checkbox-lp" class="tvd-sm-checkbox"> <?php echo __( 'Landing Pages', 'thrive-dash' ); ?> </label>
			</div>

			<div style="display:none">
				<input id="tvd-sm-script-icon" type="text" value="<#= typeof(this.model) !== 'undefined' ? this.model.get('icon') : '' #>">
			</div>
		</div>
		<div class="tvd-row tvd-row_wmb">
			<a href="javascript:void(0)" class="tvd-modal-close tvd-btn-flat tvd-btn-flat-secondary tvd-btn-flat-dark tvd-waves-effect"><?php echo __( 'BACK', 'thrive-dash' ) ?></a>
			<a href="javascript:void(0)" class="tvd-submit tvd-waves-effect tvd-waves-light tvd-btn tvd-right tvd-btn-green"><?php echo __( 'CONTINUE', 'thrive-dash' ) ?></a>
		</div>
	</form>
</div>