<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-visual-editor
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden!
}
?>
<div class="tve-blocks-info-wrapper">
	<p class="tve-blocks-tooltip-header"><?php echo __( 'Page Blocks Ready!', 'thrive-cb' ); ?></p>
	<p class="tve-blocks-tooltip-text"><?php echo __( 'This landing page set comes complete with page blocks to make building your page quicker.', 'thrive-cb' ); ?></p>
</div>
