<div class="tva-course-product-outer tva-boxed-container">
	<div class="tva-course-product">
		<div class="tva-course-product-title"><?php echo __( 'This course is currently available to everyone', 'thrive-apprentice' ) ?></div>
		<div class="tva-course-product-text tva-course-product-w"><?php echo __( 'You can sell your course, include it in a bundle or unlock it to only certain members of your website:', 'thrive-apprentice' ) ?></div>
		<button class="tva-btn tva-btn-blue tva-btn-big tva-btn-blue-empty click" data-screen="course" data-fn="addNewProduct">
			<?php tva_get_svg_icon( 'add-btn-extra' ); ?>
			<?php echo __( 'Create a Product based on this course', 'thrive-apprentice' ) ?>
		</button>
	</div>
</div>
