<div class="pt-40 pb-60 tva-products-info tva-no-products">
	<?php tva_get_svg_icon( 'drip-products-membership' ); ?>
	<div>
		<div class="tva-products-title"><?php echo __( 'Products & Membership', 'thrive-apprentice' ); ?></div>
		<div class="tva-products-text"><?php echo __( 'Quickly build products out of your courses and website content. Control how your members get access to them.', 'thrive-apprentice' ); ?></div>
		<div class="tva-products-subtitle"><?php echo __( 'Currently you don\'t have any products', 'thrive-apprentice' ); ?></div>
		<button class="tva-btn tva-btn-blue tva-btn-big click" data-screen="list" data-fn="addNewProduct">
			<?php tva_get_svg_icon( 'add-btn' ); ?>
			<?php echo __( 'Create your first product', 'thrive-apprentice' ) ?>
		</button>
	</div>
</div>
