<div class="tvd-modal-content">
	<a href="javascript:void(0)" class="tvd-modal-action tvd-modal-close tvd-modal-close-x">
		<i class="tvd-icon-close2"></i>
	</a>
	<h3 class="tvd-modal-title"><?php echo __( 'Give your new shortcode a name', 'thrive-ovation' ); ?></h3>
	<div class="tvd-v-spacer"></div>
	<div class="tvd-row tvd-collapse">
		<div class="tvd-col tvd-s12">
			<div class="tvd-input-field">
				<input id="tvo-shortcode-name" type="text" class="tvd-validate">
				<label for="tvo-shortcode-name" data-error="<?php echo __( 'Shortcode name is required', 'thrive-ovation' ); ?>"
				       class=""><?php echo __( 'Shortcode name', 'thrive-ovation' ); ?></label>
			</div>
		</div>
	</div>
</div>
<div class="tvd-modal-footer">
	<div class="tvd-row">
		<div class="tvd-col tvd-s12">
			<a class="tvo-save-new-shortcode tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-green tvd-right"
			   href="javascript:void(0);"><?php echo __( 'Save and continue', 'thrive-ovation' ); ?></a>
			</a>
		</div>
	</div>
</div>
