<div class="drop-panel tooltip-panel panel-light">
	<div class="popup-content"></div>
	<div class="control-grid center pb-0">
		<div data-fn="onApply" class="click tve-button drop-panel-action btn-apply"><?php echo __( 'Got it', 'thrive-cb' ); ?></div>

		<a class="ml-5 tcb-hidden learn_more_link tooltip-text" href="" target="_blank">
			<?php tcb_icon( 'info-regular' ); ?><?php echo __( 'Learn More', 'thrive-cb' ); ?>
		</a>
	</div>
	<div class="tooltip-promotion-image"></div>
	<div class="tcb-panel-arrow"></div>
</div>
