<div id="aff_modal" class="tvd-modal">

	<div class="tvd-col tvd-m3 tvd-input-field">
		<input placeholder="Affiliate ID" type="text" id="affiliate-id" value="">
        <span id="aff-invalid">Invalid affiliate ID</span>
	</div>

    <p>Please make sure that you add a valid ID number</p>

	<div class="">
        <a class='tvd-modal-close'>Cancel</a>
        <a class='tvd-waves-effect tvd-waves-light tvd-btn-small tvd-right tvd-btn-green tvd-save-aff-id'>Save</a>
	</div>
</div>