<?php
/**
 * Created by PhpStorm.
 * User: Ovidiu
 * Date: 7/26/2018
 * Time: 1:14 PM
 */
?>
<span data-var-type="<#= typeof var_type !== 'undefined' ? var_type : '' #>" class="p-thumb p-global-thumb click" data-fn="color_click" data-color="<#= color #>" data-custom-name="<#= custom_name #>" data-name="<#= name #>" data-tooltip="<#= name #>" data-position="top" data-var="<#= global_prefix #><#= id #>" data-synced-var="<#= synced_var #>" data-id="<#= id #>">
	<span class="p-thumb-inner" style="<#= css_prop #>:var(<#= global_prefix #><#= id #>,<#= color #>);box-shadow: 0 0 3px 1px var(<#= global_prefix #><#= id #>,<#= color #>)"></span>
</span>
