<div class="no-icons-container mr-40 ml-10" style="height: <#= height*0.95#>px;">
    <span><?php dashboard_icon( 'file-search-solid' ) ?></span>
    <span class="no-results mt-30 mb-5"><?php echo __( 'No results found', 'thrive-dash' ); ?></span>
    <span><?php echo __( 'Try adjusting your search to find what you are looking for', 'thrive-dash' ); ?></span>
</div>
<?php include TVE_DASH_PATH . '/css/font/icon-library.svg'; ?>
