<div class="api-field">
	<div class="tve-email-providers">
		<div class="label">
			<?php echo __( 'Email delivery service', 'thrive-cb' ); ?>
			<span data-paneltlt-hover class="tve-cb-img-info ml-5 tcb-email-tooltip"><?php tcb_icon( 'info-circle-solid' ); ?></span>
		</div>

		<div class="tcb-relative tve-providers-select">
			<select id="lg-email-service" class="tve-select change" data-fn="selectEmailProvider"></select>
			<span class="select2-arrow"><?php tcb_icon( 'a_down' ); ?></span>
		</div>
	</div>
	<div class="tve-email-settings"></div>
</div>
