<div class="control-grid tcb-relative palette-controls">
	<select class="tcb-select-palettes change" data-fn="domChangePalette"></select>
	<span class="palettes-arrow"><?php tcb_icon('a_down'); ?></span>
	<a href="javascript:void(0);" class="palettes-action-btn click" data-fn="domResetActivePalette" data-position="top" data-tooltip="<?php echo __( 'Reset Active Palette', 'thrive-cb' ); ?>"><?php tcb_icon('sync-regular'); ?></a>
</div>
<div class="control-grid">
	<div class="label">
		<?php echo __( 'Colors', 'thrive-cb' ); ?>
	</div>
	<div class="input">
		<div class="tcb-palettes-variables control-grid flex-end p-0"></div>
	</div>
</div>
