<div class="api-field">
	<div class="field-description">
		<?php echo __( 'Choose your mailing list', 'thrive-cb' ); ?>
	</div>
	<div class="control-grid">
		<select class="api-list change" data-fn="setupChange" data-name="list">
			<# _.each(api.get('lists'), function(item) { #>
			<#= TVE.tpl( 'util/option', {value:item.id, selected: (api.getConfig('list')==item.id), text: item.name}) #>
			<# } ) #>
		</select>

		<span class="click tve-refresh-api-list" data-fn="forceGet" data-tooltip="<?php echo __( 'Refresh', 'thrive-cb' ); ?>" data-side="top"> <?php tcb_icon( 'redo-regular' ) ?></span>
	</div>
</div>

<div class="api-field">
	<div class="field-description">
		<?php echo __( 'Choose tag:', 'thrive-cb' ) ?>
	</div>
	<div class="control-grid">
		<div class="tvd-input-field">
			<select class="tve-api-extra" name="tag">

				<#= TVE.tpl( 'util/option', {value:0, selected: (api.getConfig('tag') == 0), text: '<?php echo __( 'No tag', 'thrive-cb' ) ?>'}) #>

				<# _.each( api.get('extra_settings').tags, function( tag, id ) { #>
				<#= TVE.tpl( 'util/option', {value:id, selected: (api.getConfig('tag')== id), text: tag}) #>
				<# } ) #>
			</select>
		</div>
	</div>
</div>
