<span class="subtitle"><?php echo __( 'Thrive Lightbox Settings', 'thrive-cb' ) ?></span>
<# if ( this.get().length ) { #>
	<div class="control-grid full-width">
		<label for="evt-lightbox"><?php echo __( 'Select the Thrive Lightbox to be displayed', 'thrive-cb' ) ?></label>
		<select id="evt-lightbox" class="change" data-fn="lightbox_change">
			<# _.each( this.get(), function( lb ) { #>
			<option value="<#=lb.id#>"<#=this.model.config && this.model.config.l_id == lb.id ? ' selected="selected"' : '' #>><#=lb.title#></option>
			<# }, this ) #>
		</select>
	</div>

	<div class="tcb-text-right lightbox-add tve-add-tag clearfix">
		<a href="javascript:void(0)" class="click tcb-right" data-fn="create_lightbox_toggle"><span class="circle mr-5">+</span><?php echo __( 'Create new lightbox', 'thrive-cb' ) ?></a>
		<div class="form-create-lb tcb-right control-grid" style="display: none;">
			<input type="text" placeholder="<?php echo __( 'Lightbox title', 'thrive-cb' ) ?>" class="create-lb keyup-enter mr-10" data-fn="create_lightbox">
			<button type="button" class="tcb-right tve-button small click" data-fn="create_lightbox"><?php tcb_icon( 'check-regular' ); ?></button>
		</div>
	</div>
	<div class="control-grid full-width">
		<label for="evt-animation"><?php echo __( 'Lightbox animation', 'thrive-cb' ) ?></label>
		<select id="evt-animation" class="change" data-fn="animation_change">
			<?php foreach (TCB_Thrive_Lightbox::animations() as $key => $label ) : ?>
				<option value="<?php echo $key ?>"<#=this.model.config && this.model.config.l_anim == '<?php echo $key ?>' ? ' selected="selected"' : ''#>> <?php echo esc_html($label) ?></option>
			<?php endforeach ?>
		</select>
	</div>
<# } else { #>
	<p><?php echo __( "You don't have any lightboxes yet. Create one using the link below.", 'thrive-cb' ) ?></p>
	<div class="tcb-text-right lightbox-add tve-add-tag clearfix">
		<a href="javascript:void(0)" class="click tcb-right" data-fn="create_lightbox_toggle"><span class="circle mr-5">+</span><?php echo __( 'Create new lightbox', 'thrive-cb' ) ?></a>
		<div class="form-create-lb tcb-right control-grid" style="display: none;">
			<input type="text" placeholder="<?php echo __( 'Lightbox title', 'thrive-cb' ) ?>" class="create-lb keyup-enter mr-10" data-fn="create_lightbox">
			<button type="button" class="tcb-right tve-button small click" data-fn="create_lightbox"><?php tcb_icon( 'check-regular' ); ?></button>
		</div>
	</div>
<# } #>