<div class="tqb-answer-feedback tqb-hide">
	<div class="tqb-feedback-inner"></div>
</div>

<div class="tqb-answer-action">

	<div class="tqb-answer-text-type">
		<div class="tqb-answer-text">
			<span class="tqb-span-text"><#= item.get('text') #></span>
			<span class="tqb-fancy-icon">
				<?php tqb_get_svg_icon( 'check' ); ?>
				<?php tqb_get_svg_icon( 'times' ); ?>
			</span>
		</div>
	</div>

</div>

