<div class="tqb-answer-action tqb-open-ended-wrapper">
	<div class="tqb-answer-open-type">
		<textarea name="" id="tqb-open-type-answer" rows="<#= settings.get('form_size') #>" placeholder="<#= question.get('settings').get('placeholder')#>"></textarea>
		<p class="tqb-answer-status tqb-gray-text"><?php echo __( 'Characters', 'thrive-quiz-builder' ) ?>: <#= settings.get_max_value() #></p>
	</div>
</div>
