<div class="tqb-progress">
	<span class="tqb-progress-label"><#= model.getPercentToDisplay() #>% <#= model.get( 'label_text' ) #></span>
	<div class="tqb-progress-abs">
		<div class="tqb-progress-completed" style="width: calc( <#= completed #>% )"></div>
		<div class="tqb-next-item" style="width: calc( <#= estimatedProgress #>% )"></div>
		<div class="tqb-remaining-progress" style="width: calc( <#= remaining #>% )"></div>
	</div>
</div>
