<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-visual-editor
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden!
}
?>
<div class="thrv_wrapper tve-toc-title tve-prevent-content-edit">
	<div class="tve-content-box-background"></div>
	<div class="tve-cb">
		<div class="tve-toc-title-icon" data-icon-code="icon-ellipsis-h-regular">
			<svg class="tcb-icon" viewBox="0 0 512 512" data-id="icon-ellipsis-h-regular" data-name="">
				<path d="M304 256c0 26.5-21.5 48-48 48s-48-21.5-48-48 21.5-48 48-48 48 21.5 48 48zm120-48c-26.5 0-48 21.5-48 48s21.5 48 48 48 48-21.5 48-48-21.5-48-48-48zm-336 0c-26.5 0-48 21.5-48 48s21.5 48 48 48 48-21.5 48-48-21.5-48-48-48z"></path>
			</svg>
		</div>
		<div class="thrv_wrapper thrv_text_element tve_no_icons">
			<div class="tcb-plain-text">Outline of Post</div>
		</div>
	</div>
</div>
