<div class="fill pt-5" id="tcb-button-link-dynamic-control" data-view="DynamicLink" style="display:none">
	<select class="change dynamic-link-select" data-fn="select_dynamic_link">
		<option value="#"><?php echo __( 'None', 'thrive-theme' ); ?></option>
		<option value="thrive_the_permalink"><?php echo __( 'Post link', 'thrive-theme' ); ?></option>
		<option value="thrive_archive_link"><?php echo __( 'Post Archive', 'thrive-theme' ); ?></option>
		<option value="thrive_author_link"><?php echo __( 'Author Archive', 'thrive-theme' ); ?></option>
		<option value="thrive_date_link"><?php echo __( 'Date link', 'thrive-theme' ); ?></option>
		<option value="thrive_comments_link"><?php echo __( 'Comments link', 'thrive-theme' ); ?></option>
	</select>
</div>
