<div class="control-grid full-width pb-0">
	<p class="mt-0">
		<?php echo __( 'When enabled, an icon trigger will be added to your sidebar. This is a pre-designed trigger, that can be fully customized. However, you can remove it if you wish, by deactivating this option.', 'thrive-theme' ) ?>
	</p>
	<p class="mt-0 mb-0">
		<?php echo __( 'Moreover, you can create custom triggers that will expand the sidebar (buttons/icons/etc) and spread them all around your site. This can be achieved with the use of the "Animation&Action" element setting. Learn more about sidebar triggers ', 'thrive-theme' ); ?>
		<a target="_blank" class="blue-text" href="https://help.thrivethemes.com/en/articles/4786747-how-to-set-custom-triggers-for-your-sidebar-section"><?php echo __( 'here', 'thrive-theme' ); ?></a>.
	</p>
</div>
