<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-dashboard
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden!
}
?>
<div class="tvd-content-set-rule-step-widthin-the-last">
	<div>
		<input type="number" class="change input" data-fn="change" min="0"/>
	</div>
	<div>
		<select class="tvd-browser-default change" data-fn="change">
			<option value="days">Days</option>
			<option value="weeks">Weeks</option>
			<option value="month">Months</option>
			<option value="years">Years</option>
		</select>
	</div>
</div>
