<?php
/**
 * Created by PhpStorm.
 * User: Ovidiu
 * Date: 5/14/2018
 * Time: 11:36 AM
 */
?>
<div class="tvd-row">
	<div class="tvd-col tvd-s12">
		<input type="checkbox" class="tqb-checkbox-action" id="tqb_gdpr_user_permission" <# if(checked) { #> checked <# }  #> />
		<label for="tqb_gdpr_user_permission">
			<?php echo __( 'Creating user profiles in the Reporting Area by matching the answers and result to the email address entered by the user in this step.', 'thrive-quiz-builder' ); ?>
			<a href="https://help.thrivethemes.com/en/articles/4426073-profiling-in-thrive-quiz-builder-how-to-be-gdpr-compliant" target="_blank"><?php echo __( 'Find out more about profiling in this article.', 'thrive-quiz-builder' ); ?></a>
		</label>
	</div>
</div>
