<?php

/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-quiz-builder
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden!
}
?>
<div class="tvd-row">
	<div class="tvd-col tvd-s12">
		<input type="checkbox" class="tqb-checkbox-action" id="tqb_skip_optin" <# if(checked) { #> checked <# }  #> />
		<label for="tqb_skip_optin">
			<?php echo __( 'Skip this opt-in gate for logged in users', 'thrive-quiz-builder' ); ?>
		</label>
	</div>
</div>

