<div class="ls-optimization-wrapper">
	<div class="page-content grey">
		<div class="page-title"><?php echo __( "Your assets aren't fully optimized", 'thrive-cb' ); ?></div>
		<div class="page-text-wrapper">
			<span class="big-icon warning"></span>
			<div class="text-title red-color"><?php echo __( 'None of your assets are optimized. ', 'thrive-cb' ); ?></div>
			<div class="text-main">
				<div class="text-paragraph">
					<?php echo __( 'Click the button below to migrate to the latest version for additional performance benefits. Once complete, you can disable and enable site optimizations at any time with a single click', 'thrive-cb' ); ?>
				</div>
			</div>
		</div>
		<button class="lightspeed-button blue-color lightspeed-optimize">
			<?php echo __( 'Optimize my site', 'thrive-cb' ); ?>
		</button>
		<div class="page-footnote-wrapper">
			<div class="footnote-text">
				<?php echo __( 'Please note that optimization may take some time to complete depending on the size of your site. You’ll see a live update of migration occurring. You can leave it running in the background and come back at any point to see progress.', 'thrive-cb' ); ?>
			</div>
			<a class="link-text" target="_blank" href="https://help.thrivethemes.com/en/articles/5295426-what-is-the-asset-optimization-tool-how-does-it-work">
				<?php echo __( 'Learn more about the migration process', 'thrive-cb' ); ?>
			</a>
		</div>
	</div>
</div>
