<div class="ttd-theme-info click" data-fn="toggleSkinView">
	<div class="ttd-icon ttd-icon-blue ttd-change-bg-reverse">
		<?php Thrive_Views::svg_icon( 'builder-logo' ); ?>
	</div>
	<h1 class="ttd-spn">
        <span>
            <?php echo __( 'Currently Previewing', 'thrive-theme' ); ?>:
        </span>
		<span class="ttd-skin-preview-name">
            <#= name #>
        </span>
	</h1>
	<div class="dots">
		<span></span>
		<span></span>
		<span></span>
		<span></span>
		<span></span>
		<span class="span-w-text"><?php echo __( 'Manage', 'thrive-theme' ); ?></span>
	</div>
</div>
