<?php
/**
 * Created by PhpStorm.
 * User: ovidi
 * Date: 6/30/2018
 * Time: 12:17 PM
 */
?>
<div class="row">
	<div class="col-xs-12">
		<div class="tve-price-box-default-control"></div>
	</div>
</div>
<hr>
<div class="control-grid">
	<div class="label"><?php echo __( 'Price Boxes', 'thrive-cb' ); ?></div>
	<div class="fill">
		<button class="tcb-right tve-button blue click" id="tcb-add-price-box-item" data-fn="add_price_box">
			<?php echo __( 'ADD NEW', 'thrive-cb' ) ?>
		</button>
	</div>
</div>
<hr>
<div class="tve-price-box-preview-list-control"></div>

<div class="hide-mobile">
	<hr class="hide-mobile">
	<div class="tve-price-box-gutter-width-control"></div>
	<hr>
	<div class="tve-price-box-wrap-control"></div>
	<span class="info-text"><?php echo __( 'If you enable wrapping, the price boxes will not be resizable anymore', 'thrive-cb' ) ?></span>
	<div class="tve-price-box-column-width-control"></div>
</div>
