<div class="pending-no-collapse">
</div>
<div class="tcm-pending-save">
	<span class="tcm-text"><?php echo __( 'Pending' ); ?>&nbsp;&hellip;</span>

	<div class="tcm-pending-error tcm-icon-red tooltip-elem">
		<span class="tooltiptext error-holder"></span>
		<span class="tcm-error-icon"><?php echo __( 'Error' ); ?></span>
	</div>

	<span class="tcm-check">
		<?php tcah()->tcm_icon( 'moderation-status-check', 'tcm-moderation-status-check' ); ?>
	</span>
</div>
