<div class="keyboard-tooltip">
	<p class="esc"><?php echo __( 'Esc to close', Thrive_Comments_Constants::T ); ?>&nbsp;&nbsp;<span class="gray-color">&#10005;</span></p>

	<h3><?php echo __( 'Try Keyboard Navigation', Thrive_Comments_Constants::T ); ?></h3>

	<div class="inner scrollbar-inner">
		<h4><?php echo __( 'Comments List Navigation', Thrive_Comments_Constants::T ); ?></h4>
		<p><span class="icon">&darr;</span>&nbsp;&nbsp;<span class="icon">&uarr;</span>&nbsp;&nbsp;&nbsp;&nbsp;<?php echo __( 'Up and Down Arrow keys to change Active Comment', Thrive_Comments_Constants::T ); ?></p>

		<h4><?php echo __( 'Active Comment Navigation', Thrive_Comments_Constants::T ); ?></h4>
		<p class="one"><span class="icon">&larr;</span>&nbsp;&nbsp;<span class="icon">&rarr;</span>&nbsp;&nbsp;&nbsp;&nbsp; <?php echo __( 'Move the active cursor Horizontally', Thrive_Comments_Constants::T ); ?></p>
		<p class="two"><span class="icon">&uarr;</span>&nbsp;&nbsp;<span class="icon">&darr;</span>&nbsp;&nbsp;&nbsp;&nbsp; <?php echo __( 'Submenu Navigation', Thrive_Comments_Constants::T ); ?></p>

		<h4><?php echo __( 'Active Comment Quick Shortcut Keys', Thrive_Comments_Constants::T ); ?></h4>
		<p class="three last">
			<span><span class="icon">A</span><?php echo __( 'Approve', Thrive_Comments_Constants::T ); ?></span>
			<span><span class="icon">U</span><?php echo __( 'Unapprove', Thrive_Comments_Constants::T ); ?></span>
			<span><span class="icon">E</span><?php echo __( 'Edit', Thrive_Comments_Constants::T ); ?></span>
			<span class="tcm-two-lines last"><span class="icon tcm-tab">TAB</span><span class="tcm-p"><?php echo __( 'Go to next field / button in form', Thrive_Comments_Constants::T ); ?></span></span>
		</p>
		<p class="three last">
			<span><span class="icon">R</span><?php echo __( 'Reply', Thrive_Comments_Constants::T ); ?></span>
			<span><span class="icon">G</span><?php echo __( 'Delegate', Thrive_Comments_Constants::T ); ?></span>
			<span><span class="icon">Z</span><?php echo __( 'Restore', Thrive_Comments_Constants::T ); ?></span>
			<span class="tcm-two-lines last"><span class="icon">N</span><span class="tcm-p"><?php echo __( 'Needs Reply / No Reply Needed', Thrive_Comments_Constants::T ); ?></span></span>
		</p>
		<p class="three last">
			<span><span class="icon">S</span><?php echo __( 'Mark as Spam', Thrive_Comments_Constants::T ); ?></span>
			<span><span class="icon">F</span><?php echo __( 'Feature / Unfeature', Thrive_Comments_Constants::T ); ?></span>
			<span><span class="icon">D</span><?php echo __( 'Move to Trash', Thrive_Comments_Constants::T ); ?></span>

			<# if ( typeof ThriveOvation !== 'undefined' ) { #>
			<span class="last"><span class="icon">T</span><?php echo __( 'Save as Testimonial', Thrive_Comments_Constants::T ); ?></span>
			<# } #>

		</p>

	</div>
</div>

