<div class="keyboard-notification ">
	<span class="esc">&#10005;</span>

	<div class="inner">
		<h3><?php echo __( 'Try Keyboard Navigation', Thrive_Comments_Constants::T ); ?></h3>
		<p><?php echo __( 'Click above or press Ctrl + K to see the keyboard shortcuts available in Thrive Comments Moderation.', Thrive_Comments_Constants::T ); ?></p>

		<input type="checkbox" id="show-keyboard-notification-checkbox"/>
		<label for="show-keyboard-notification-checkbox"><?php echo __( "Don't show again", Thrive_Comments_Constants::T ); ?></label>

		<a href="javascript:void(0)" class="keyboard-notification-close tvd-right"><?php echo __( 'Close', Thrive_Comments_Constants::T ); ?></a>
	</div>
</div>
