<div class="tcb-edit-item-category" id="text">
	<div class="row margin-top-10">
		<div class="col-xs-5">
			<?php echo __( 'Label', 'thrive-apprentice' ); ?>
		</div>
		<div class="col-xs-7">
			<input type="text" class="change input tcb-ce-item-label" data-fn="change_setting" data-fn-input="change_setting" data-setting="label"/>
		</div>
	</div>
	<div class="row margin-top-10">
		<div class="col-xs-5">
			<?php echo __( 'Placeholder', 'thrive-apprentice' ); ?>
		</div>
		<div class="col-xs-7">
			<input type="text" class="change input tcb-ce-item-placeholder" data-fn="change_setting" data-fn-input="change_setting" data-setting="placeholder"/>
		</div>
	</div>
</div>
