<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-apprentice
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden!
}
?>
<div class="theme-empty-post-content-placeholder">
	<h3 style="padding: 0;">
		<?php echo sprintf( __( 'The %s you are previewing has no content', 'thrive-apprentice' ), '<#= contentType #>' ); ?>
	</h3>
	<p>
		<?php echo __( 'You can preview this template with another piece of content by using the content switcher in the upper right corner of the editor.', 'thrive-apprentice' ); ?>
	</p>

	<img src="<?php echo THEME_URL . '/inc/assets/images/empty-post-content-placeholder.png'; ?>" alt="" class="tvd-responsive-img">

	<p>
		<?php echo __( '<b>Please Note:</b> Your \'Content Area\' container will be entirely hidden on lessons that do not have written content or resources, and when no other elements are added to it.', 'thrive-apprentice' ); ?>
	</p>
</div>
