<?php

/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-apprentice
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden!
}
?>

<div class="theme-empty-post-content-placeholder">
	<h3><?php echo __( 'The completion page you are previewing has no content', 'thrive-apprentice' ); ?></h3>
	<p>
		<?php echo __( 'You can preview this template with content by using the switcher in the upper right corner of the editor.', 'thrive-apprentice' ); ?>
	</p>

	<img src="<?php echo THEME_URL . '/inc/assets/images/empty-post-content-placeholder.png'; ?>" alt="" class="tvd-responsive-img">
	<p>
		<?php echo __( '<b>Please note:</b> This content area is uniquely editable per course. Add content to it by clicking ‘edit’ in the Course Completion tab in Thrive Apprentice. If no content is added, this area will be hidden.', 'thrive-apprentice' ) ?>
	</p>
</div>

