<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-apprentice
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden!
}
?>
<div class="mt-6">
	<span class="click open color-menu-item tcb-tva-skin-toggle-control" data-dropdown-base-selector=".tcb-tva-skin-toggle-" data-fn="toggleColorDropdown">
		<i></i> <?php echo __( 'Apprentice Colors', THEME_DOMAIN ); ?>
	</span>
</div>
<div class="tcb-tva-skin-toggle-content">
	<div id="tcb-tva-skin-color-details"></div>
	<div class="tcb-tva-skin-colors-container mt-5"></div>
</div>
