<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-apprentice
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden!
}
?>
<div class="info-link mt-10">
	<span class="info-text">
		<?php echo __( 'This course is currently not published. For your customers to view the details of this course it must be published', 'thrive-apprentice' ); ?>
		&nbsp;<a href="javascript:void(0);" class="inline" target="_blank" rel="noopener"><?php echo __( 'here', 'thrive-apprentice' ); ?></a>
	</span>
</div>
