<div class="control-grid full-width pb-0">
	<span>
		<?php echo esc_html__( 'This sets the viewport region where the parallax effect takes place. Start position is distance from the bottom of viewport. End position is distance from the top.', 'thrive-cb' ); ?>
	</span>
	<a href="https://thrivethemes.com/tkb_item/how-to-use-the-parallax-feature" class="blue-text mt-5" target="_blank">
		<?php echo esc_html__( 'Read the FAQ for more information.', 'thrive-cb' ); ?>
	</a>
</div>