<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-visual-editor
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden!
}

?>

<img class="<?php echo $data['classes']; ?>" alt="<?php echo $data['alt']; ?>"
	 data-css="<?php echo $data['data-css']; ?>" data-id="<?php echo $data['id']; ?>" data-c-f-id="<?php echo $data['name']; ?>"
	 width="<?php echo $data['width']; ?>" height="<?php echo $data['height']; ?>"
	 title="<?php echo $data['title']; ?>" src="<?php echo $data['url']; ?>" <?php echo $data['extra']; ?>>

