<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-visual-editor
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden!
}

?>


<video style="width: 100%;" data-provider="external" class="tcb-responsive-video" controlslist="nodownload" data-c-f-id="<?php echo $data['name']; ?>" data-title="<?php echo $data['title']; ?>" data-id="<?php echo $data['id']; ?>" <?php echo $data['extra']; ?>>
	<source src="<?php echo $data['url']; ?>" type="<?php echo $data['mime_type']; ?>">
</video>

