<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-dashboard
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}
?>

<ul>
	<li class="<#= page == 'global_fields' ? 'tvd-selected' : '' #>">
		<a href="#global_fields">
			<i><?php echo dashboard_icon( 'format-align-justify' ) ?></i><?php _e( 'Global Fields', TVE_DASH_TRANSLATE_DOMAIN ); ?>
		</a>
	</li>
<!--    <li class="<#= page == 'dynamic_fields' ? 'tvd-selected' : '' #>">-->
<!--        <a href="#dynamic_fields">-->
<!--			<i>--><?php //echo dashboard_icon( 'dynamic-list' ) ?><!--</i> --><?php //_e( 'Dynamic Fields', TVE_DASH_TRANSLATE_DOMAIN ); ?>
<!--        </a>-->
<!--    </li>-->
<!--    <li class="<#= page == 'visitor_targeting' ? 'tvd-selected' : '' #>">-->
<!--        <a href="#visitor_targeting">-->
<!--			<i>--><?php //echo dashboard_icon( 'crosshairs-regular' ) ?><!--</i> --><?php //_e( 'Visitor Targeting', TVE_DASH_TRANSLATE_DOMAIN ); ?>
<!--        </a>-->
<!--    </li>-->
</ul>
