<div class="tva-drip-lesson">
	<div class="tva-col-names">
		<div class="tva-drip-lesson-title"><#- lesson.get('post_title') #></div>
		<span class="tva-drip-lesson-type tva-text-capitalize"><#= lesson.get('lesson_type') #> <?php echo __( 'lesson', 'thrive-apprentice' ); ?></span>
	</div>
	<div class="tva-col-conditions">
		<# if ( lesson.isFree() ) { #>
		<div class="tva-tooltip-parent">
			<div class="drip-summary-item tva-drip-free-content">
				<div class="drip-summary-icon"><?php tva_get_svg_icon( 'unlock-alt_light' ); ?></div>
				<div class="drip-summary-text"><?php echo __( 'Free', 'thrive-apprentice' ); ?></div>
			</div>
			<div class="tva-custom-tooltip tva-tooltip-inherited">
				<?php esc_html_e( "This lesson is set as a free preview lesson in the course details tab, and cannot be locked.", 'thrive-apprentice' ); ?>
				<a href="http://help.thrivethemes.com/en/articles/5727555-creating-a-drip-schedule" target="_blank" rel="noopener"><?php echo esc_html__( 'Learn more', 'thrive-apprentice' ); ?></a>
			</div>
		</div>
		<# } else { #>
		<#= view.renderUnlockSummary( lesson.get( 'ID' ) ) #>
		<# } #>
	</div>
	<div class="tva-col-restriction">
		<div class="tva-drip-label mr-20 tva-tooltip-parent">
			<?php esc_html_e( 'INHERIT', 'thrive-apprentice' ); ?>
			<span class="tva-custom-tooltip">
				<?php esc_attr_e( 'This feature is coming soon', 'thrive-apprentice' ); ?>
			</span>
		</div>
	</div>
</div>
