<div class="tva-no-courses tva-student-no-courses tva-flex tva-flex-column">
	<?php tva_get_svg_icon( 'no-courses' ); ?>
	<span class="tva-student-500"><?php echo esc_html__( 'No courses found', 'thrive-apprentice' ); ?></span>
	<span><?php echo esc_html__( 'This student has access to a Thrive Apprentice product which does not restrict any courses 
but may restrict other website content.', 'thrive-apprentice' ); ?></span>
	<span><?php echo esc_html__( 'Completion data is only available when a member has course access.', 'thrive-apprentice' ); ?></span>
</div>
