<div class="tcm-deleted-comment clear-this">
	<div class="deleted-header">
		<div class="moderation-img no-image" data-social-avatar="<#= comment.get('social_avatar') #>" data-email="<#= comment.get('comment_author_email') #>" data-src="<#= comment.get('photo_src') #>" style="background-image: url(<#= comment.get('author_avatar_urls') #>);"></div>
		<div class="deleted-header-text">
			<strong>
				<#= comment.get('author_name') #>
			</strong>
			<span>
				<#= comment.get('formatted_date') #>
			</span>
		</div>
	</div>
	<div class="deleted-text">
		<p class="deleted-info-text tcm-color-ac">
			<# if ( comment.get('status') === 'spam' ) { #>
			<span><?php echo __( 'This comment was marked as spam', Thrive_Comments_Constants::T ) ?></span>
			<# } else { #>
			<span><?php echo __( 'This comment was marked as trash', Thrive_Comments_Constants::T ) ?></span>
			<# } #>
			<a href="#" data-key="z" class="undo-action"><?php echo __( 'Undo', Thrive_Comments_Constants::T ); ?></a>
		</p>

		<p>
			<#= comment.get('comment_content') #>
		</p>
	</div>
</div>
