<div class="tcb-post-list-filter thrv_wrapper"
	 data-filter-option="<#= config.filter_option#>"
	 data-multiple-selection="<#=config.multiple_selection#>"
	 data-filter-type="<#=config.filter_type#>"
	 data-display-option="<#=config.display_option#>"
	 data-all-option="<#=config.all_option#>"
	 data-url-query-key="<#=config.url_query_key#>"
	 data-options-selection="<#=config.options_selection#>"
	 data-default-value="<#=config.default_value #>"
>
</div>