<div class="tcb-video-cover-default-text-wrapper thrv_wrapper thrv_contentbox_shortcode thrv-content-box tve-elem-default-pad tve-draggable tve-droppable" draggable="true">
	<div class="tcb-video-cover-default-text-wrapper-bg tve-content-box-background"></div>
	<div class="tve-cb" style="">
		<div class="thrv_wrapper thrv_text_element tve-draggable tve-droppable tve-froala fr-box">
			<div class="fr-wrapper" dir="auto"><div class="fr-element fr-view" dir="auto" contenteditable="true" spellcheck="true"><p style="text-align: center;" class="tve-droppable"><?php echo __( 'Click to play', 'thrive-cb' ) ?></p></div></div>
		</div>
	</div>
</div>
<div class="tcb-video-cover-default-arrow thrv_wrapper thrv_icon tcb-icon-display tcb-local-vars-root tve-draggable tve-droppable" draggable="true">
	<svg class="tcb-icon" viewBox="0 0 24 24" data-id="icon-undo-solid" data-name="">
		<path d="M12.5,8C9.85,8 7.45,9 5.6,10.6L2,7V16H11L7.38,12.38C8.77,11.22 10.54,10.5 12.5,10.5C16.04,10.5 19.05,12.81 20.1,16L22.47,15.22C21.08,11.03 17.15,8 12.5,8Z"></path>
	</svg>
</div>
<div class="tcb-video-cover-default-play-icon thrv_wrapper thrv_icon tcb-icon-display tcb-local-vars-root tve_evt_manager_listen tve_et_mouseover tve_ea_thrive_animation tve_anim_pulse_grow tve-draggable tve-droppable" data-tcb-events="__TCB_EVENT_[{&quot;t&quot;:&quot;mouseover&quot;,&quot;config&quot;:{&quot;anim&quot;:&quot;pulse_grow&quot;,&quot;loop&quot;:1},&quot;a&quot;:&quot;thrive_animation&quot;}]_TNEVE_BCT__" draggable="true">
	<svg class="tcb-icon" viewBox="0 0 24 24" data-id="icon-play-solid" data-name="">
		<path d="M8,5.14V19.14L19,12.14L8,5.14Z"></path>
	</svg>
</div>
