<hr>
<div class="consent-description mb-10">
	<div class="tcb-modal-tab-item-title mb-5"><?php echo __( 'GDPR requirements', 'thrive-cb' ) ?></div>
	<div class="warning">
		<span><?php echo sprintf( __( 'Define which connections will receive data when the checkbox is %snot ticked%s by the user', 'thrive-cb' ), '<b>','</b>' ); ?></span>
		<a href="https://thrivethemes.com/tkb_item/how-to-set-up-the-gdpr-custom-field-type/" target="_blank">
			<?php echo __( 'Learn more', 'thrive-cb' ) ?>
		</a>
	</div>
</div>
<div class="api-list no-space"></div>
<div class="info-text mandatory-info blue mt-10" style="display: none">
	<?php tcb_icon( 'info' ); ?>
	<?php echo sprintf( __( 'Your GDPR checkbox %swill require%s confirmation to submit the form.', 'thrive-cb' ), '<b>','</b>' ); ?>
</div>

