<div class="sp-color-options">
	<div class="sp-color-info-container">
		<span class="sp-color-info-label">
			<#= title #>
		</span>

		<span class="sp-info-icon click" data-paneltlt-hover data-fn="openTooltip">
			<?php tcb_icon( 'info-circle-solid' ); ?>
		</span>
	</div>

	<div>
		<div class="sp-color-action-container sp-dynamic-color-container">
			<div class="sp-action-icon">
				<?php tcb_icon( 'database-light' ); ?>
			</div>
		</div>
	</div>
</div>
