<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-visual-editor
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden!
}
?>
<div class="tve-blocks-info-wrapper">
	<p class="tve-blocks-tooltip-header"><?php echo __( 'Upgrade to access', 'thrive-cb' ); ?></p>
	<p class="tve-blocks-tooltip-text"><?php echo __( 'Upgrade to the full version of Architect to access this landing page set', 'thrive-cb' ); ?></p>
</div>

