<div class="mt-10 tcb-hidden global-edit-warning" id="global-color-edit-warning">
	<span id="global-color-edit-msg"><?php echo __( 'Careful, you are editing a global color.', 'thrive-cb' ); ?></span>
	<a href="https://thrivethemes.com/tkb_item/how-to-use-the-global-colors-feature/#globalcolor_edit" target="_blank"><?php echo __( 'Learn more', 'thrive-cb' ); ?></a>
</div>
<div class="mt-6">
	<span class="click open color-menu-item tcb-favorites-toggle-control" data-dropdown-base-selector=".tcb-favorites-toggle-" data-fn="toggleColorDropdown">
		<i></i> <?php echo __( 'My Colors', 'thrive-cb' ); ?>
	</span>
</div>
<div class="tcb-favorites-toggle-content">
	<div id="tcb-color-details"></div>
	<div id="tcb-add-color"></div>
	<div class="tcb-saved-colors-container mt-5"></div>
</div>
