<div class="thrv_text_element">
	<section class="fr-dropdown-list fr-link-styles fr-state" data-state="normal">
		<div data-style="__default" class="fr-link-style-item fr-dropdown-item fr-command" data-cls="" data-cmd="linkStyleApply">
			<a class="fr-link-style" href="javascript:void(0)"><?php echo esc_html__( tcb_post()->is_landing_page() ? 'Landing Page Default' : 'Default', 'thrive-cb' ); ?></a>
			<div class="fr-submenu">
				<span class="fr-command" data-style="__default" tabIndex="-1" role="option" data-cmd="linkStyleApply"><?php echo __( 'Apply Link Style', 'thrive-cb' ); ?></span>
				<span class="fr-command" data-style="__default" tabIndex="-1" role="option" data-cmd="linkStyleUpdate"><?php echo __( 'Update Link Style to Match', 'thrive-cb' ); ?></span>
				<span class="fr-command" data-style="__default" tabIndex="-1" role="option" data-cmd="linkStyleDefaultReset"><?php echo __( 'Reset Style', 'thrive-cb' ); ?></span>
			</div>
		</div>
		<#_.each ( linkStyles, function( style, _index ) { #>
		<div class="fr-link-style-item fr-dropdown-item fr-command" data-style="<#=style.id#>" data-cmd="linkStyleApply">
			<a class="fr-link-style <#=style.cls#>" href="javascript:void(0)"><#=style.name#></a>
			<div class="fr-submenu">
				<span class="fr-command" data-style="<#=style.id#>" tabIndex="-1" role="option" data-cmd="linkStyleApply"><?php echo __( 'Apply Link Style', 'thrive-cb' ); ?></span>
				<span class="fr-command" data-style="<#=style.id#>" tabIndex="-1" role="option" data-cmd="linkStyleUpdate"><?php echo __( 'Update Link Style to Match', 'thrive-cb' ); ?></span>
				<span class="fr-command" data-style="<#=style.id#>" data-confirm="<?php echo esc_attr__( 'Are you sure you want to delete this style? This action cannot be undone.', 'thrive-cb' ); ?>" tabIndex="-1" role="option" data-cmd="linkStyleDelete"><?php echo __( 'Delete Link Style', 'thrive-cb' ); ?></span>
			</div>
		</div>
		<# }) #>
		<div class="fr-link-style-item fr-dropdown-item fr-save-link-style">
			<span class="fr-command" data-cmd="linkStyleAddForm"><?php echo esc_html__( 'Save as new style', 'thrive-cb' ); ?></span>
		</div>
	</section>
	<section class="fr-link-style-add fr-form fr-state" data-state="add" style="display: none">
		<div class="fr-form-section">
			<strong><?php echo esc_html__( 'Save link style', 'thrive-cb' ); ?></strong>
		</div>
		<div class="fr-form-section fr-link-style-preview"><a href="javascript:void(0)"><?php echo esc_html__( 'Sample', 'thrive-cb' ); ?></a></div>
		<div class="fr-form-section">
			<input type="text" class="fr-link-style-name" value="Link <#=Math.random()#>" placeholder="<?php echo esc_attr__( 'Link style name', 'thrive-cb' ); ?>">
		</div>
		<div class="fr-action-buttons">
			<button class="fr-command fr-danger fr-remove" role="button" data-cmd="linkStyleCancelAdd" type="button" tabindex="10"><?php echo esc_html__( 'Cancel', 'thrive-cb' ); ?></button>
			<button class="fr-command fr-submit" role="button" data-cmd="linkStyleAdd" type="button" tabindex="9"><?php echo esc_html__( 'Save', 'thrive-cb' ); ?></button>
		</div>
	</section>
</div>