<?php
/**
 * Created by PhpStorm.
 * User: ovidiu
 * Date: 1/12/2019
 * Time: 5:29 PM
 */
?>
<div class="mt-6">
	<span class="click open color-menu-item tcb-templates-toggle-control" data-dropdown-base-selector=".tcb-templates-toggle-" data-fn="toggleGradientDropdown">
		<i></i> <?php echo __( 'Template Gradients', 'thrive-cb' ); ?>
	</span>
</div>
<div class="tcb-templates-toggle-content">
	<div id="templates-gradient-details"></div>
	<div class="templates-gradients-container mt-5"></div>
</div>

