<h5 class="mt-0 tva-label-section-title"><?php esc_html_e( 'Labels & translations', 'thrive-apprentice' ); ?></h5>

<h1 class="tva-main-heading"><?php esc_html_e( 'Call to action buttons', 'thrive-apprentice' ) ?></h1>

<h5 class="mt-20 tva-label-section-title">
	<?php esc_html_e( 'Call to action buttons', 'thrive-apprentice' ); ?>
	<div class="tva-info-icon tva-tooltip-parent tva-mega-tooltip">
		<?php tva_get_svg_icon( 'info-solid' ); ?>
		<div class="tva-custom-tooltip tva-tt-cta">
			<p class="mt-10 mb-10"><strong><?php esc_html_e( 'Buttons help the user navigate around your courses', 'thrive-apprentice' ); ?></strong></p>
			<p class="mb-10"><?php esc_html_e( 'The buttons inside Thrive Apprentice intelligently update so that they reflect the state of the course participant.', 'thrive-apprentice' ); ?></p>
			<p class="mb-10"><?php esc_html_e( 'For example, if a customer doesn’t have access to a course, the button might say “Sign up now“ and, when clicked, will take the user to the purchase page.', 'thrive-apprentice' ); ?></p>
			<p class="mb-10"><?php esc_html_e( 'If the user already has access, the button might say "Start course" and take the user to the first lesson.', 'thrive-apprentice' ); ?></p>
			<p class="m-0">
				<a href="https://help.thrivethemes.com/en/articles/4698654-how-to-use-the-call-to-action-buttons-when-setting-up-thrive-apprentice-dynamic-labels" target="_blank" rel="noopener"><?php esc_html_e( 'Learn more about button behavior in Apprentice', 'thrive-apprentice' ); ?></a>
			</p>
		</div>
	</div>
</h5>
<div id="tva-cta-buttons"></div>
