<h5 class="mt-0 tva-label-section-title"><?php esc_html_e( 'Labels & translations', 'thrive-apprentice' ); ?></h5>

<h1 class="tva-main-heading"><?php esc_html_e( 'Course structure', 'thrive-apprentice' ) ?></h1>

<div class="tva-title-columns tva-flex">
	<div class="tva-label-space"></div>
	<div class="tva-label-input-container"><?php esc_html_e( 'Single', 'thrive-apprentice' ) ?></div>
	<div class="tva-label-input-container"><?php esc_html_e( 'Plural', 'thrive-apprentice' ) ?></div>
</div>

<div id="tva-course-structure"></div>

