<h5 class="mt-0 tva-label-section-title"><?php esc_html_e( 'Labels & translations', 'thrive-apprentice' ); ?></h5>

<h1 class="tva-main-heading"><?php esc_html_e( 'Course navigation', 'thrive-apprentice' ) ?></h1>

<h5 class="mt-15 mb-0 tva-label-section-title"><?php esc_html_e( 'Navigation buttons', 'thrive-apprentice' ) ?></h5>
<div id="tva-course-navigation" class="mt-20"></div>
<h5 class="mt-15 mb-0 tva-label-section-title"><?php esc_html_e( 'Navigation warnings', 'thrive-apprentice' ) ?></h5>
<div id="tva-course-navigation-warnings" class="mt-20"></div>

