<?php

/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-apprentice
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden!
}
?>
<div>
	<span><#= this.title #></span>
	<br>
	<span><?php echo esc_html__( 'This cannot be undone.', 'thrive-apprentice' ); ?></span>
</div>
<div class="tva-flex" style="gap: 10px;">
	<a href="javascript:void(0);" class="click" data-fn="cancel"><?php echo esc_html__( 'No, cancel', 'thrive-apprentice' ); ?></a>
	<a href="javascript:void(0);" class="click" data-fn="confirm"><?php echo esc_html__( 'Yes, delete', 'thrive-apprentice' ); ?></a>
</div>
