<?php

/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-dashboard
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden!
}
?>
<div class="tva-flex tva-flex-row">
	<span class="tva-protected-files-notice-border"></span>
	<p class="ml-30 tva-flex tva-align-center"><?php tva_get_svg_icon( 'exclamation-triangle' ); ?></p>
	<div class="tva-flex tva-flex-column ml-30">
		<span class="tva-protected-files-notice-title"><?php echo __( 'Unsupported web server', 'thrive-apprentice' ); ?></span>
		<span><?php echo __( 'We have detected that your website is hosted on an unsupported web server. This could mean that the Protected files feature does not work as intended and your files may not be protected. Please contact support for guidance.', 'thrive-apprentice' ); ?></span>
		<span>
			<a href="https://help.thrivethemes.com/en/articles/5326423-thrive-suite-system-requirements-and-recommendations" rel="noopener" target="_blank"><?php echo __( 'Learn more', 'thrive-apprentice' ); ?></a>
		</span>
	</div>
</div>
