<div class="pb-6 layout-width">
	<label><#=this.label#></label>
	<div class="control-grid no-space">
		<div class="tve-control tabs mr-10 border"></div>
		<div class="inputs">
			<div class="slider-input has-clear">
				<?php include plugin_dir_path( __FILE__ ) . 'input.phtml'; ?>
			</div>
			<div class="slider-input has-clear">
				<?php include plugin_dir_path( __FILE__ ) . 'input.phtml'; ?>
			</div>
			<div class="slider-input has-clear">
				<?php include plugin_dir_path( __FILE__ ) . 'input.phtml'; ?>
			</div>
		</div>
	</div>
</div>