<div class="tvd-modal-content tcm-keywords-delete">

	<div class="tcm-modal-header">
		<h2><?php echo __( 'Delete badge', Thrive_Comments_Constants::T ); ?></h2>
		<hr>
	</div>

	<div class="tcm-modal-body">

		<h4>
			<?php echo __( 'Are you sure you want to delete the badge "', Thrive_Comments_Constants::T ) ?>
			<#= badge.get('name')#>"?
		</h4>

		<p><?php echo __( 'The badge is eliminated from all the comments.', Thrive_Comments_Constants::T ) ?></p>

	</div>

	<div class="tcm-btm">
		<a href="javascript:void(0)" class="tvd-btn-flat tvd-btn-flat-secondary tvd-btn-flat-dark tvd-modal-close tvd-waves-effect tcm-delete-no"><?php echo __( 'Keep it', Thrive_Comments_Constants::T ) ?></a>
		<a href="javascript:void(0)" class="tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-red tvd-modal-close tvd-right tvd-modal-submit tcm-delete-yes"><?php echo __( 'Delete it', Thrive_Comments_Constants::T ) ?></a>
	</div>

</div>