<div class="control-grid full-width pb-0">
	<span>
		<?php echo esc_html__( 'Lazy loading is recommended for websites with caching, but can cause unwanted layout shifts. Enable uniform display heights to minimize layout shifting.', 'thrive-cb' ); ?>
		<a href="https://help.thrivethemes.com/en/articles/5858891-using-the-advanced-options-of-the-conditional-display-setting" target="_blank">
			<?php echo __( 'Learn more about these options.', 'thrive-cb' ) ?>
		</a>
	</span>
</div>
