<div class="control-grid full-width pb-0">
	<span>
		<?php echo esc_html__( 'Add an option per line', 'thrive-cb' ); ?>
	</span>
	<br>
	<span>
		<?php echo esc_html__( 'You can optionally add a "value" along with your labels by separating them with a comma:', 'thrive-cb' ); ?>
	</span>
	<br>
	<span><?php echo esc_html__( 'Australian Dollar,AUD', 'thrive-cb' ); ?></span>
	<span><?php echo esc_html__( 'United States Dollar,USD', 'thrive-cb' ); ?></span>
	<span><?php echo esc_html__( 'Philippines Pesos,PHP', 'thrive-cb' ); ?></span>
	<span><?php echo esc_html__( 'Malaysian Ringit,MYR', 'thrive-cb' ); ?></span>
	<br>
	<a href="https://thrivethemes.com/tkb_item/using-the-manage-multiple-options-section-when-customizing-the-dropdown-custom-field/" target="_blank">
		<?php echo __( 'Learn more here', 'thrive-cb' ) ?>
	</a>
</div>