<div class="drop-panel tooltip-panel panel-light">
	<div class="popup-content"></div>
	<div class="control-grid pb-0">
		<a class="tve-button learn_more_link btn-apply-gray" href="" target="_blank">
			<?php echo __( 'Show me how >', 'thrive-cb' ); ?>
		</a>

		<div data-fn="onApply" class="click tve-button btn-apply-green"><?php echo __( 'Got It', 'thrive-cb' ); ?></div>

	</div>
	<div class="tooltip-promotion-image"></div>
	<div class="tcb-panel-arrow"></div>
</div>