<div class="tcb-tooltip video-cover-tooltip">
	<div class="tcb-tooltip-text">
		<p class="mb-5">
			<?php echo __( 'Enable the "video cover/ highlight" for better CWV.', 'thrive-cb' ); ?>
		</p>
		<a href="https://help.thrivethemes.com/en/articles/5448025-should-i-use-the-video-cover-thumbnail-option-for-my-video-element" target="_blank">
			<?php echo __( 'Learn why.', 'thrive-cb' ); ?>
		</a>
	</div>

	<div class="tcb-tooltip-image">
		<img src="<?php echo tve_editor_url( 'editor/css/images/video_cover_cta.png' ) ?>" alt="">
	</div>

	<div class="tcb-tooltip-buttons">
		<a href="#" class="tcb-button-dismiss click" data-fn="dismiss">
			<?php echo __( 'GOT IT', 'thrive-cb' ); ?>
		</a>
	</div>

	<div class="tcb-tooltip-close">
		<span class="click" data-fn="dismiss">
			<?php tcb_icon( 'exit' ) ?>
		</span>
	</div>
</div>
