<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-university
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}
?>

<div class="tva-login-delete">
	<p><#- labels.title #></p>

	<div class="tva-flex tva-space-between">
		<a href="javascript:void(0)" class="click" data-fn="cancelRemove">
			<?php echo __( 'Keep this page', 'thrive-apprentice' ) ?>
		</a>
		<a href="javascript:void(0)" class="click" data-fn="confirmRemove">
			<?php echo __( 'Remove this page', 'thrive-apprentice' ) ?>
		</a>
	</div>
</div>
