<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-university
 *
 * To be used as a simple link which does something and requires a confirmation from the user
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}
?>

<div class="tva-create-state">
	<a class="tva-clear-cache tva-flex mt-20 click" href="javascript:void(0)" data-fn="removePage">
		<#= labels.title #>
	</a>
</div>
