<div class="tvd-modal-content">
	<h3 class="tvd-modal-title"><?php esc_html_e( 'Unlock content', 'thrive-apprentice' ); ?></h3>

	<p><?php esc_html_e( 'Selected lessons will be manually unlocked only for this member, granting them immediate access without needing to meet any required drip conditions.', 'thrive-apprentice' ); ?></p>

	<p><?php esc_html_e( 'Would you like to continue?', 'thrive-apprentice' ); ?></p>

</div>
<div class="tva-modal-footer-outer">
	<button type="button" class="tva-modal-btn tvd-modal-close"><?php esc_html_e( 'Cancel', 'thrive-apprentice' ); ?></button>
	<button type="button" class="tva-modal-btn tva-modal-btn-blue click" data-fn="confirm"><?php esc_html_e( 'Yes, unlock content', 'thrive-apprentice' ); ?></button>
</div>
