<div class="tvd-modal-content">
	<h3 class="tvd-modal-title"><?php esc_html_e( 'Reset status', 'thrive-apprentice' ); ?></h3>

	<p><?php esc_html_e( 'Progress and unlock status will be reset for the selected content and member only. This will clear any start and completion dates, and re-lock any content that has drip rules applied. The member will need to progress through their content again.', 'thrive-apprentice' ); ?></p>

	<p><?php esc_html_e( 'Would you like to continue?', 'thrive-apprentice' ); ?></p>

</div>
<div class="tva-modal-footer-outer">
	<button type="button" class="tva-modal-btn tvd-modal-close"><?php esc_html_e( 'Cancel', 'thrive-apprentice' ); ?></button>
	<button type="button" class="tva-modal-btn tva-modal-btn-blue click" data-fn="confirm"><?php esc_html_e( 'Yes, reset lessons', 'thrive-apprentice' ); ?></button>
</div>
