<div class="tvd-modal-content">
	<h3 class="tvd-modal-title"><?php esc_html_e( 'Mark as complete', 'thrive-apprentice' ); ?></h3>

	<p><?php esc_html_e( 'Selected lessons will be manually marked as complete for this member only.', 'thrive-apprentice' ); ?><br>
	<?php esc_html_e( 'This will:', 'thrive-apprentice' ); ?><br>
	&ndash; <?php esc_html_e( 'Unlock the lesson if it is locked via drip campaign', 'thrive-apprentice' ); ?><br>
	&ndash; <?php esc_html_e( 'Set the start date to now (if it is not set already)', 'thrive-apprentice' ); ?><br>
	&ndash; <?php esc_html_e( 'Set the completion date to now (if it is not set already)', 'thrive-apprentice' ); ?></p>

</div>
<div class="tva-modal-footer-outer">
	<button type="button" class="tva-modal-btn tvd-modal-close"><?php esc_html_e( 'Cancel', 'thrive-apprentice' ); ?></button>
	<button type="button" class="tva-modal-btn tva-modal-btn-blue click" data-fn="confirm"><?php esc_html_e( 'Yes, mark as complete', 'thrive-apprentice' ); ?></button>
</div>
