<div class="tvd-modal-content" style="overflow: visible">
	<h3 class="tvd-modal-title"><#= this.title #></h3>
	<div class="tva-content-restriction"></div>
	<div class="tva-flex tva-flex-row tva-space-between mt-50">
		<button type="button" class="click tva-modal-btn tva-modal-btn-close" data-fn="close"><?php echo __( 'Cancel', 'thrive-apprentice' ); ?></button>
		<button type="button" class="click tva-modal-btn tva-modal-btn-green" data-fn="save"><?php echo __( 'Save', 'thrive-apprentice' ) ?></button>
	</div>
</div>
