<div class="tvd-modal-content">
	<h3 class="tvd-modal-title">
		<?php echo esc_html__( 'Are you sure you want to Delete this Chapter?', 'thrive-apprentice' ); ?>
	</h3>
	<p class="mb-0">
		<?php echo esc_html__( 'You are about to delete the selected chapter and all content contained inside. This action cannot be undone.', 'thrive-apprentice' ); ?>
	</p>
</div>
<div class="tva-modal-footer-outer">
	<button type="button" class="tva-modal-btn tvd-modal-close"><?php echo esc_html__( 'No', 'thrive-apprentice' ); ?></button>
	<button type="button" class="tva-modal-btn tva-modal-btn-red click" data-fn="confirm"><?php echo esc_html__( 'Yes', 'thrive-apprentice' ); ?></button>
</div>
