<div class="tvd-modal-content">
	<h3 class="tvd-modal-title">
		<?php echo esc_html__( 'Are you sure you want to delete these items?', 'thrive-apprentice' ); ?>
	</h3>
	<p class="mb-0">
		<?php echo esc_html__( 'You are about to delete the selected items and all content contained inside.', 'thrive-apprentice' ); ?>
	</p>
</div>
<div class="tva-modal-footer-outer">
	<button type="button" class="tva-modal-btn tvd-modal-close"><?php echo esc_html__( 'No, take me back', 'thrive-apprentice' ); ?></button>
	<button type="button" class="tva-modal-btn tva-modal-btn-red tvd-modal-save click" data-fn="confirm"><?php echo esc_html__( 'Yes, delete them', 'thrive-apprentice' ); ?></button>
</div>
