<div>
	<h2><?php echo __( 'Help Corner', 'thrive-apprentice' ); ?></h2>
	<div class="tva-help-container">
		<a href="https://help.thrivethemes.com" rel=noopener target="_blank" class="tva-help-item">
			<div class="tva-svg-icon"><?php tva_get_svg_icon( 'knowledge-base' ); ?></div>
			<div class="item-title">
				<span><?php echo __( 'Knowledge Base', 'thrive-apprentice' ) ?></span>
			</div>
			<div class="item-text">
				<span><?php echo __( 'Search our extensive knowledge base for "how-to" articles and instructions.', 'thrive-apprentice' ) ?></span>
			</div>
		</a>
		<a href="https://thrivethemes.com/university/" rel=noopener target="_blank" class="tva-help-item">
			<div class="tva-svg-icon"><?php tva_get_svg_icon( 'thrive-university' ); ?></div>
			<div class="item-title">
				<span><?php echo __( 'Thrive University', 'thrive-apprentice' ) ?></span>
			</div>
			<div class="item-text">
				<span><?php echo __( 'Take one of our online courses on website building and online marketing.', 'thrive-apprentice' ) ?></span>
			</div>
		</a>
		<a href="https://thrivethemes.com/support" rel=noopener target="_blank" class="tva-help-item">
			<div class="tva-svg-icon"><?php tva_get_svg_icon( 'support' ); ?></div>
			<div class="item-title">
				<span><?php echo __( 'Get Support', 'thrive-apprentice' ) ?></span>
			</div>
			<div class="item-text">
				<span><?php echo __( 'Search our extensive knowledge base for "how-to" articles and instructions.', 'thrive-apprentice' ) ?></span>
			</div>
		</a>
	</div>

</div>
