<div class="tvd-modal-content tva-modal-ch-icon">
	<h3 class="tvd-modal-title"><?php esc_html_e( 'Choose an icon', 'thrive-apprentice' ); ?></h3>

	<div class="tvd-row">
		<input type="text" placeholder="<?php esc_html_e( 'Search icon', 'thrive-apprentice' ); ?>" class="tva-search-icons input" data-fn="search">
	</div>

	<div class="tvd-row tva-icons-list">
		<div class="tva-icons-height">
			<div class="tva-custom-icons">
				<div class="tva-custom-icons-title">
					<h4><?php esc_html_e( 'Custom Icons', 'thrive-apprentice' ); ?></h4>
				</div>
				<div class="tva-custom-icons-list tva-icon-grid"></div>
			</div>
			<h4 class="tva-svg-icons-title"><?php esc_html_e( 'Font Awesome Icons', 'thrive-apprentice' ); ?></h4>
			<div class="tva-font-awesome-icons tva-icon-grid"></div>
		</div>
	</div>

	<div class="tva-modal-footer">
		<button type="button" class="tvd-modal-close tvd-btn-flat tvd-btn-flat-secondary tvd-btn-flat-dark tvd-waves-effect"><?php esc_html_e( 'Cancel', 'thrive-apprentice' ); ?></button>
		<button type="button" data-fn="save" class="tvd-modal-submit click tvd-right tva-disabled tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-green"><?php esc_html_e( 'Select', 'thrive-apprentice' ); ?></button>
	</div>
</div>
