<div class="tvd-modal-content">
	<h3 class="tvd-modal-title"><?php esc_html_e( 'Send certificate to student', 'thrive-apprentice' ); ?></h3>

	<p><?php esc_html_e( 'Send an email containing a download link to the certificate to the student?', 'thrive-apprentice' ); ?><br>

</div>
<div class="tva-modal-footer-outer">
	<button type="button" class="tva-modal-btn tvd-modal-close"><?php esc_html_e( 'Cancel', 'thrive-apprentice' ); ?></button>
	<button type="button" class="tva-modal-btn tva-modal-btn-blue click" data-fn="confirm"><?php esc_html_e( 'Yes, send to student', 'thrive-apprentice' ); ?></button>
</div>
