<div class="thrv_wrapper tve-dynamic-dropdown" data-style="<#= style #>">
	<input type="text" style="position: absolute; opacity: 0;" autocomplete="off" readonly data-placeholder="<#= label #>"/>
	<a class="tve-lg-dropdown-trigger tcb-plain-text" tabindex="-1">
		<span class="tve-disabled-text-inner"><#= label #></span>
		<span class="tve-item-dropdown-trigger">
		<svg xmlns="http://www.w3.org/2000/svg" class="tve-dropdown-icon-up" viewBox="0 0 320 512"><path d="M151.5 347.8L3.5 201c-4.7-4.7-4.7-12.3 0-17l19.8-19.8c4.7-4.7 12.3-4.7 17 0L160 282.7l119.7-118.5c4.7-4.7 12.3-4.7 17 0l19.8 19.8c4.7 4.7 4.7 12.3 0 17l-148 146.8c-4.7 4.7-12.3 4.7-17 0z"></path></svg>
	</span>
	</a>
	<ul class="tve-lg-dropdown-list tve-dynamic-dropdown-editable">
		<li class="tve-dynamic-dropdown-option tve_no_icons tve-dynamic-dropdown-editable" data-value="Option"><span class="tve-input-option-text tcb-plain-text">Option</span></li>
	</ul>
</div>
