<select class="fr-dynamic-link-select" id="fr-dynamic-link-list">
	<option value="tcb_post_the_permalink"><?php echo __( 'Post Link', 'thrive-cb' ); ?></option>
	<option value="tcb_post_archive_link"><?php echo __( 'Post Archive', 'thrive-cb' ); ?></option>
	<option value="tcb_post_author_link"><?php echo __( 'Author Archive', 'thrive-cb' ); ?></option>
	<option value="tcb_post_date_link"><?php echo __( 'Date Archive', 'thrive-cb' ); ?></option>
	<option value="tcb_post_comments_link"><?php echo __( 'Comments Link', 'thrive-cb' ); ?></option>
	<?php do_action( 'tcb_extra_postlist_links' ); ?>
</select>
