<div class="tve_lg_input_container tve_lg_textarea tve_lg_regular_input tve-lg-show-counter tcb-plain-text">
	<textarea class="tcb-plain-text" rows="3" data-min="10" maxlength="350" data-required="1"></textarea>
	<div class="thrv_wrapper thrv_text_element tve-lg-textarea-counter">
		<div class="tcb-plain-text"><span class="tve-fill-text-dynamic" contenteditable="false">0 of 350</span></div>
	</div>
</div>