<div class="tve_s_item tve_s_<#= data.key #> thrv_wrapper"
     data-network="<#= data.network #>"
     data-s="<#= data.key #>"
     data-href="<#= data.href #>"
	 data-name="<#= data.name#>"
>

	<a href="<#= data.href #>" class="<#= data.class #> " <#= data.linkNewTab #> <#= data.linkNoFollow #> <#= data.dataset #> data-id="icon-<#= r.iconsNames[data.network] ? r.iconsNames[data.network] : 'link' #>">
	<span class="tve_s_icon">
			 <#= data.icon #>
		</span>
	</a>
</div>
