<div class="button-item">
	<div class="tve-select-item click" data-value="<#= template.cls #>" data-fn="select">
		<div class="thrv_wrapper thrv-button comment-form-submit <#= template.cls #>">
			<button class="tcb-button-link">
				<span class="tcb-button-texts"><span class="tcb-button-text thrv-inline-text <#= template.cls #>-prtext"><?php echo __( 'Button', 'thrive-theme' ); ?></span></span>
			</button>
		</div>
		<p><#= template.name #></p>
	</div>
</div>
