<# var style = item.get('video_style'); #>
<# var new_question = parseInt( item.get('new_question') ); #>
<div class="tge-video-form tge-video-style-<#= 0 === new_question ? style.selected : TGE_Editor.default_video_style #>">
	<div class="tqb-video-container-responsive">
		<iframe data-provider="youtube" src="//www.youtube.com/embed/<#= item.get( 'video_id' ) #>"
				height="313" width="551" frameborder="0"
				allowfullscreen
				allowtransparency="true"
				style="display: block"></iframe>
	</div>
</div>
