<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-visual-editor
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden!
}
?>
<p class="tooltip-header"><?php echo __( 'Page Blocks and Content Blocks', 'thrive-cb' ); ?></p>
<p class="tooltip-text"><strong style="font-weight: 500;"><?php echo __( 'Together as one. Available Everywhere.', 'thrive-cb' ); ?></strong></p>
<p class="tooltip-text"><?php echo __( 'Page blocks and content blocks have merged into one element, <strong style="font-weight: 500;">Blocks</strong>, to help you create more engaging blogposts and build landing pages faster.', 'thrive-cb' ); ?></p>
