<?php
/**
 * Created by PhpStorm.
 * User: Ovidiu
 * Date: 1/10/2019
 * Time: 9:36 AM
 */
?>

<div class="mt-6">
	<span class="click open color-menu-item tcb-templates-toggle-control" data-dropdown-base-selector=".tcb-templates-toggle-" data-fn="toggleColorDropdown">
		<i></i> <?php echo __( 'Template Colors', 'thrive-cb' ); ?>
	</span>
</div>
<div class="tcb-templates-toggle-content">
	<div id="tcb-template-color-details"></div>
	<div class="tcb-template-colors-container mt-5"></div>
</div>
