<h2 class="ttd-sidebar-branding-header click" data-fn="toggle_dropdown">
	<span><?php echo __( 'Theme Colors', 'thrive-theme' ); ?></span>
	<span class="dropdown-arrow"></span>
</h2>
<div class="ttd-sidebar-branding-block">
	<div id="ttd-skin-palette-container" class="ttd-left-align"></div>
	<div id="ttd-skin-master-vars-container" class="ttd-left-align"></div>
	<div id="ttd-skin-other-vars-container" class="ttd-left-align"></div>
	<div id="ttd-global-vars-container" class="ttd-left-align"></div>
	<div id="ttd-skin-color-picker-overlay" class="click" data-fn="stop_click" style="display: none;">
		<input type="text" id="ttd-skin-color-picker" style="display:none">
	</div>
</div>
