<div class="tvd-modal-content">
	<h3 class="pl-30 tvd-modal-title"><?php echo __( 'Unlock options', TVA_Const::T ); ?></h3>
	<div class="tva-drip-types-container">
		<# if ( this.model.hasInherited() ) { #>
		<div class="tva-content-trigger-locked">
			<?php tva_get_svg_icon( 'lock-alt_light' ); ?>
			<?php esc_html_e( 'This lesson will be unlocked once the parent module has unlocked', TVA_Const::T ); ?>
		</div>
		<div class="tva-trigger-sep mt-15 mb-15">
			<span class="tva-trigger-sep__line"></span>
			<span class="tva-trigger-sep__and"><?php esc_html_e( 'and', TVA_Const::T ); ?></span>
			<span class="tva-trigger-sep__line"></span>
		</div>
		<# } #>
		<p class="tva-drip-unlock">
			<?php esc_html_e( 'Unlock content if', TVA_Const::T ); ?>
			<select data-calculate-width="1" data-bind="condition" class="tva-drip-unlock-select tva-control-inline tva-select-compact" data-container-class="material" data-width="50px">
				<option value="and"><?php esc_html_e( 'all', TVA_Const::T ); ?></option>
				<option value="or"><?php esc_html_e( 'any', TVA_Const::T ); ?></option>
			</select>
			&nbsp;<?php esc_html_e( 'of the following conditions are met', TVA_Const::T ); ?>
		</p>

		<div class="tva-content-triggers">
			<# this.collection.each( function( trigger, index ) { #>
			<div class="tva-content-trigger-item <#=trigger.canRemove() ? '' : ' tva-trigger-disabled'#>">
				<div class="tva-trigger-row tva-flex tva-space-between">
					<div class="tva-trigger-icon drip-trigger-icon-<#=trigger.get('id')#>"><#=TVA.Utils.icon( trigger.icon() ) #></div>
					<div class="tva-trigger-label"><#=trigger.getLabel()#></div>
					<div class="tva-trigger-actions">
						<# if ( trigger.canEdit() ) { #>
						<a href="javascript:void(0)" data-tooltip="<?php esc_attr_e( 'This is a campaign condition, it can only be changed from campaign settings', TVA_Const::T ); ?>" class="click tva-trigger-edit<#=trigger.canRemove() ? '' : ' tvd-tooltipped tva-disabled'#>" data-fn="editTrigger" data-id="<#- trigger.get('id') #>"><?php tva_get_svg_icon( 'pen_light' ); ?></a>
						&nbsp;
						<# } #>
						<a href="javascript:void(0)" data-tooltip="<?php esc_attr_e( 'This is a campaign condition, it can only be removed from campaign settings', TVA_Const::T ); ?>" class="click tva-trigger-remove<#=trigger.canRemove() ? '' : ' tvd-tooltipped tva-disabled'#>" data-fn="removeTrigger" data-index="<#- index #>"><?php tva_get_svg_icon( 'trash-1' ); ?></a>
					</div>
				</div>
			</div>
			<# }, this ) #>
			<# if ( ! this.collection.length ) { #>
			<div class="tva-drip-no-triggers"><p><?php esc_html_e( 'No rules added', TVA_Const::T ); ?></p></div>
			<# } #>
		</div>

		<button class="tva-add-rule<#= this.getAvailableTriggers().length === 0 ? ' tva-rule-disabled' : ''#> click" data-fn="addRule"><span>+</span><?php esc_html_e( 'Add new rule', TVA_Const::T ); ?></button>

		<# if ( this.getAvailableTriggers().length ) { #>
		<div class="tva-drip-trigger tva-new-trigger tva-hide">
			<h4>
				<?php esc_html_e( 'Unlock condition', TVA_Const::T ); ?>
			</h4>
			<div class="tva-icon-trigger">
				<select class="change" data-fn="triggerSelected">
					<option data-icon="drip-campaign-scratch" value="" selected disabled><?php esc_html_e( 'Select a new condition', TVA_Const::T ); ?>&hellip;</option>
					<# _.each( this.getAvailableTriggers(), function( trigger ) { #>
					<option data-icon="<#- trigger.icon #>"<#=trigger.disabled ? ' disabled' : ''#> value="<#-trigger.id#>"><#-trigger.name#></option>
					<# }, this ) #>
				</select>
				<div class="drip-select-icon drip-select-green"><?php tva_get_svg_icon( 'drip-campaign-scratch' ); ?></div>
			</div>
		</div>
		<# } #>
		<div class="tva-trigger-form">
			<div class="tva-trigger-settings"></div>
			<div class="tva-trigger-buttons" style="display: none">
				<button class="tva-drip-cancel click" data-fn="cancelTriggerEdit"><?php tva_get_svg_icon( 'cross' ); ?></button>
				<button class="tva-modal-btn tva-modal-btn-green click" data-fn="saveTriggerData"><?php esc_html_e( 'Add', TVA_Const::T ); ?></button>
			</div>
		</div>

		<div class="tva-drip-content-visibility tva-flex">
			<?php tva_get_svg_icon( 'icon-eye' ); ?>
			<?php esc_html_e( 'Lesson visibility in lesson list when content is locked', TVA_Const::T ); ?>
			&nbsp;
			<select data-calculate-width="1" class="tva-drip-visibility-select tva-select-compact" data-width="160px" data-bind="visibility" data-container-class="material">
				<# if ( this.campaign.get( 'display_locked' ) ) { #>
				<option value="inherited"><?php echo __( 'Inherited (Displayed)', TVA_Const::T ); ?></option>
				<# } else { #>
				<option value="inherited"><?php echo __( 'Inherited (Hidden)', TVA_Const::T ); ?></option>
				<# } #>
				<option value="hidden"><?php esc_html_e( 'Hidden', TVA_Const::T ); ?></option>
				<option value="displayed"><?php esc_html_e( 'Displayed as locked', TVA_Const::T ); ?></option>
			</select>
		</div>
	</div>
	<div class="tvd-modal-btm tva-flex tva-flex-row tva-space-between">
		<button type="button" class="click tva-modal-btn tva-modal-btn-fill-gray" data-fn="close"><?php echo __( 'Cancel', TVA_Const::T ); ?></button>
		<button type="button" class="click tva-modal-btn tva-modal-btn-fill-green tva-disabled" data-fn="save"><?php echo __( 'Save', TVA_Const::T ); ?></button>
	</div>
</div>
