<div class="button-item">
	<div class="tve-select-item click" data-value="<#= template.cls #>" data-fn="select">
		<div class="thrv_wrapper thrv-button <#= template.cls #>">
			<a href="javascript:void(0);" class="tcb-button-link">
				<span class="tcb-button-texts"><span class="tcb-button-text thrv-inline-text <#= template.cls #>-prtext"><?php echo __( 'Button', 'thrive-cb' ); ?></span></span>
			</a>
		</div>
		<p><#= template.name #></p>
	</div>
</div>
