<div class="tva-new-product-cards tva-flex tva-space-between">
	<button class="click" data-fn="addClicked" data-type="courses">
		<?php tva_get_svg_icon( 'book_light' ); ?>
		<?php echo esc_html__( 'Add Courses', 'thrive-apprentice' ); ?>
	</button>
	<button class="click" data-fn="addClicked" data-type="content">
		<?php tva_get_svg_icon( 'copy_light' ); ?>
		<?php echo esc_html__( 'Add Other Content', 'thrive-apprentice' ); ?>
	</button>
</div>
<div class="product-form-wrapper mt-10"></div>
<div class="tva-flex tva-flex-column tva-add-product-rules-wrapper mt-10"></div>
