<div class="tva-flex tva-flex-column">
	<span><?php echo esc_html__( 'Are you sure you want to remove this content from the product?', TVA_Const::T ); ?></span>
	<span class="tva-content-details"></span>
</div>
<a class="click" data-fn="confirm"><?php echo esc_html__( 'Yes, delete', TVA_Const::T ); ?></a>
<a class="click" data-fn="cancel"><?php echo esc_html__( 'No, cancel', TVA_Const::T ); ?></a>
