<div class="tva-flex tva-flex-column tva-add-product-form tva-relative">
	<div class="tva-product-course-form"></div>
	<div class="tva-list-action tva-flex tva-align-center tva-space-center">
		<button class="tva-btn tva-btn-blue tva-add-to-product click" data-fn="addToProduct">
			<# if(this.editMode){ #><?php esc_html_e( 'Save Changes', 'thrive-apprentice' ); ?><# }else{ #><?php esc_html_e( 'Add to product', 'thrive-apprentice' ); ?><# } #>
		</button>
	</div>
</div>
