<div class="tva-flex tva-flex-column">
	<span><?php echo esc_html__( 'Are you sure you want to delete this rule?', 'thrive-apprentice' ); ?></span>
	<span class="tva-content-details"></span>
</div>
<a class="click" data-fn="confirm"><?php echo esc_html__( 'Yes, delete', 'thrive-apprentice' ); ?></a>
<a class="click" data-fn="cancel"><?php echo esc_html__( 'No, cancel', 'thrive-apprentice' ); ?></a>
