<div class="tva-rule-item-container tva-flex tva-space-between">
	<div class="tva-flex click" data-fn="edit">
		<div class="tva-rule-item-content-icon">
			<?php tva_get_svg_icon( 'sticky-note_light' ); ?>
		</div>
		<div class="tva-rule-item-content-type"></div>
		<div class="tva-rule-item-content-data"></div>
	</div>
	<div class="tva-rule-item-buttons">
		<div class="click mr-15" data-fn="edit"><?php tva_get_svg_icon( 'pen_light' ); ?></div>
		<div class="click" data-fn="delete"><?php tva_get_svg_icon( 'trash-1' ); ?></div>
	</div>
</div>
