<div class="tva-rule-header pt-15 pb-15 click" data-fn="toggleItemsList">
	<div class="tva-rule-img <#= model.get('slug') #>">&nbsp;</div>

	<div class="tva-rule-title text"><#= model.get('label') #></div>
	<div class="tva-course-integration-label"></div>

	<div class="tva-rule-status tva-integration-status"></div>

	<div class="tva-rule-toggle">
		<span class="tva-arrow-icon">&nbsp;</span>
	</div>
</div>
<div class="tva-rule-items tva-top-border tva-course-integration-items-wrapper" style="display: none">
	<div class="tva-flex tva-align-center tva-space-between mb-20">
		<span class="tva-rule-label"><#= model.getText() #></span>
	</div>
	<div class="tva-flex tva-notice-card tva-notice-woocommerce tva-flex-column">
		<span><?php tva_get_svg_icon( 'shopping-cart_solid' ); ?></span>
		<p><?php echo esc_html__( 'Thrive Apprentice course access is handled inside WooCommerce Products', 'thrive-apprentice' ); ?></p>
		<a class="text" target="_blank" href="http://help.thrivethemes.com/en/articles/5024001-thrive-apprentice-and-woocommerce-quick-start-guide"><?php echo __( 'See the Thrive Apprentice and WooCommerce quickstart guide', 'thrive-apprentice' ); ?></a>
	</div>
</div>
