<?php tva_get_svg_icon( 'course-overview' ); ?>
<p><?php echo esc_html__( 'You cannot edit the course overview before saving the course!', 'thrive-apprentice' ) ?></p>
<div class="align">
	<a class="tva-page-option tva-flex-mid disabled" href="javascript:void(0)">
		<?php tva_get_svg_icon( 'eye_light', 'mr-10' ); ?>
		<?php echo __( 'View', 'thrive-apprentice' ) ?>
	</a>
	<a class="tva-page-option tva-flex-mid disabled" href="javascript:void(0)">
		<?php tva_get_svg_icon( 'tar-icon', 'mr-10 tva-tar' ); ?>
		<#- TVA.t.settings_tab.login_page.edit_post #>
	</a>
</div>
